import * as _142 from "./abci/types";
import * as _143 from "./crypto/keys";
import * as _144 from "./crypto/proof";
import * as _145 from "./libs/bits/types";
import * as _146 from "./p2p/types";
import * as _147 from "./types/block";
import * as _148 from "./types/evidence";
import * as _149 from "./types/params";
import * as _150 from "./types/types";
import * as _151 from "./types/validator";
import * as _152 from "./version/types";
export declare namespace tendermint {
    const abci: {
        checkTxTypeFromJSON(object: any): _142.CheckTxType;
        checkTxTypeToJSON(object: _142.CheckTxType): string;
        responseOfferSnapshot_ResultFromJSON(object: any): _142.ResponseOfferSnapshot_Result;
        responseOfferSnapshot_ResultToJSON(object: _142.ResponseOfferSnapshot_Result): string;
        responseApplySnapshotChunk_ResultFromJSON(object: any): _142.ResponseApplySnapshotChunk_Result;
        responseApplySnapshotChunk_ResultToJSON(object: _142.ResponseApplySnapshotChunk_Result): string;
        responseProcessProposal_ProposalStatusFromJSON(object: any): _142.ResponseProcessProposal_ProposalStatus;
        responseProcessProposal_ProposalStatusToJSON(object: _142.ResponseProcessProposal_ProposalStatus): string;
        misbehaviorTypeFromJSON(object: any): _142.MisbehaviorType;
        misbehaviorTypeToJSON(object: _142.MisbehaviorType): string;
        CheckTxType: typeof _142.CheckTxType;
        CheckTxTypeSDKType: typeof _142.CheckTxType;
        CheckTxTypeAmino: typeof _142.CheckTxType;
        ResponseOfferSnapshot_Result: typeof _142.ResponseOfferSnapshot_Result;
        ResponseOfferSnapshot_ResultSDKType: typeof _142.ResponseOfferSnapshot_Result;
        ResponseOfferSnapshot_ResultAmino: typeof _142.ResponseOfferSnapshot_Result;
        ResponseApplySnapshotChunk_Result: typeof _142.ResponseApplySnapshotChunk_Result;
        ResponseApplySnapshotChunk_ResultSDKType: typeof _142.ResponseApplySnapshotChunk_Result;
        ResponseApplySnapshotChunk_ResultAmino: typeof _142.ResponseApplySnapshotChunk_Result;
        ResponseProcessProposal_ProposalStatus: typeof _142.ResponseProcessProposal_ProposalStatus;
        ResponseProcessProposal_ProposalStatusSDKType: typeof _142.ResponseProcessProposal_ProposalStatus;
        ResponseProcessProposal_ProposalStatusAmino: typeof _142.ResponseProcessProposal_ProposalStatus;
        MisbehaviorType: typeof _142.MisbehaviorType;
        MisbehaviorTypeSDKType: typeof _142.MisbehaviorType;
        MisbehaviorTypeAmino: typeof _142.MisbehaviorType;
        Request: {
            encode(message: _142.Request, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number | undefined): _142.Request;
            fromJSON(object: any): _142.Request;
            toJSON(message: _142.Request): unknown;
            fromPartial(object: Partial<_142.Request>): _142.Request;
            fromAmino(object: _142.RequestAmino): _142.Request;
            toAmino(message: _142.Request): _142.RequestAmino;
            fromAminoMsg(object: _142.RequestAminoMsg): _142.Request;
            fromProtoMsg(message: _142.RequestProtoMsg): _142.Request;
            toProto(message: _142.Request): Uint8Array;
            toProtoMsg(message: _142.Request): _142.RequestProtoMsg;
        };
        RequestEcho: {
            encode(message: _142.RequestEcho, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number | undefined): _142.RequestEcho;
            fromJSON(object: any): _142.RequestEcho;
            toJSON(message: _142.RequestEcho): unknown;
            fromPartial(object: Partial<_142.RequestEcho>): _142.RequestEcho;
            fromAmino(object: _142.RequestEchoAmino): _142.RequestEcho;
            toAmino(message: _142.RequestEcho): _142.RequestEchoAmino;
            fromAminoMsg(object: _142.RequestEchoAminoMsg): _142.RequestEcho;
            fromProtoMsg(message: _142.RequestEchoProtoMsg): _142.RequestEcho;
            toProto(message: _142.RequestEcho): Uint8Array;
            toProtoMsg(message: _142.RequestEcho): _142.RequestEchoProtoMsg;
        };
        RequestFlush: {
            encode(_: _142.RequestFlush, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number | undefined): _142.RequestFlush;
            fromJSON(_: any): _142.RequestFlush;
            toJSON(_: _142.RequestFlush): unknown;
            fromPartial(_: Partial<_142.RequestFlush>): _142.RequestFlush;
            fromAmino(_: _142.RequestFlushAmino): _142.RequestFlush;
            toAmino(_: _142.RequestFlush): _142.RequestFlushAmino;
            fromAminoMsg(object: _142.RequestFlushAminoMsg): _142.RequestFlush;
            fromProtoMsg(message: _142.RequestFlushProtoMsg): _142.RequestFlush;
            toProto(message: _142.RequestFlush): Uint8Array;
            toProtoMsg(message: _142.RequestFlush): _142.RequestFlushProtoMsg;
        };
        RequestInfo: {
            encode(message: _142.RequestInfo, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number | undefined): _142.RequestInfo;
            fromJSON(object: any): _142.RequestInfo;
            toJSON(message: _142.RequestInfo): unknown;
            fromPartial(object: Partial<_142.RequestInfo>): _142.RequestInfo;
            fromAmino(object: _142.RequestInfoAmino): _142.RequestInfo;
            toAmino(message: _142.RequestInfo): _142.RequestInfoAmino;
            fromAminoMsg(object: _142.RequestInfoAminoMsg): _142.RequestInfo;
            fromProtoMsg(message: _142.RequestInfoProtoMsg): _142.RequestInfo;
            toProto(message: _142.RequestInfo): Uint8Array;
            toProtoMsg(message: _142.RequestInfo): _142.RequestInfoProtoMsg;
        };
        RequestInitChain: {
            encode(message: _142.RequestInitChain, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number | undefined): _142.RequestInitChain;
            fromJSON(object: any): _142.RequestInitChain;
            toJSON(message: _142.RequestInitChain): unknown;
            fromPartial(object: Partial<_142.RequestInitChain>): _142.RequestInitChain;
            fromAmino(object: _142.RequestInitChainAmino): _142.RequestInitChain;
            toAmino(message: _142.RequestInitChain): _142.RequestInitChainAmino;
            fromAminoMsg(object: _142.RequestInitChainAminoMsg): _142.RequestInitChain;
            fromProtoMsg(message: _142.RequestInitChainProtoMsg): _142.RequestInitChain;
            toProto(message: _142.RequestInitChain): Uint8Array;
            toProtoMsg(message: _142.RequestInitChain): _142.RequestInitChainProtoMsg;
        };
        RequestQuery: {
            encode(message: _142.RequestQuery, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number | undefined): _142.RequestQuery;
            fromJSON(object: any): _142.RequestQuery;
            toJSON(message: _142.RequestQuery): unknown;
            fromPartial(object: Partial<_142.RequestQuery>): _142.RequestQuery;
            fromAmino(object: _142.RequestQueryAmino): _142.RequestQuery;
            toAmino(message: _142.RequestQuery): _142.RequestQueryAmino;
            fromAminoMsg(object: _142.RequestQueryAminoMsg): _142.RequestQuery;
            fromProtoMsg(message: _142.RequestQueryProtoMsg): _142.RequestQuery;
            toProto(message: _142.RequestQuery): Uint8Array;
            toProtoMsg(message: _142.RequestQuery): _142.RequestQueryProtoMsg;
        };
        RequestBeginBlock: {
            encode(message: _142.RequestBeginBlock, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number | undefined): _142.RequestBeginBlock;
            fromJSON(object: any): _142.RequestBeginBlock;
            toJSON(message: _142.RequestBeginBlock): unknown;
            fromPartial(object: Partial<_142.RequestBeginBlock>): _142.RequestBeginBlock;
            fromAmino(object: _142.RequestBeginBlockAmino): _142.RequestBeginBlock;
            toAmino(message: _142.RequestBeginBlock): _142.RequestBeginBlockAmino;
            fromAminoMsg(object: _142.RequestBeginBlockAminoMsg): _142.RequestBeginBlock;
            fromProtoMsg(message: _142.RequestBeginBlockProtoMsg): _142.RequestBeginBlock;
            toProto(message: _142.RequestBeginBlock): Uint8Array;
            toProtoMsg(message: _142.RequestBeginBlock): _142.RequestBeginBlockProtoMsg;
        };
        RequestCheckTx: {
            encode(message: _142.RequestCheckTx, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number | undefined): _142.RequestCheckTx;
            fromJSON(object: any): _142.RequestCheckTx;
            toJSON(message: _142.RequestCheckTx): unknown;
            fromPartial(object: Partial<_142.RequestCheckTx>): _142.RequestCheckTx;
            fromAmino(object: _142.RequestCheckTxAmino): _142.RequestCheckTx;
            toAmino(message: _142.RequestCheckTx): _142.RequestCheckTxAmino;
            fromAminoMsg(object: _142.RequestCheckTxAminoMsg): _142.RequestCheckTx;
            fromProtoMsg(message: _142.RequestCheckTxProtoMsg): _142.RequestCheckTx;
            toProto(message: _142.RequestCheckTx): Uint8Array;
            toProtoMsg(message: _142.RequestCheckTx): _142.RequestCheckTxProtoMsg;
        };
        RequestDeliverTx: {
            encode(message: _142.RequestDeliverTx, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number | undefined): _142.RequestDeliverTx;
            fromJSON(object: any): _142.RequestDeliverTx;
            toJSON(message: _142.RequestDeliverTx): unknown;
            fromPartial(object: Partial<_142.RequestDeliverTx>): _142.RequestDeliverTx;
            fromAmino(object: _142.RequestDeliverTxAmino): _142.RequestDeliverTx;
            toAmino(message: _142.RequestDeliverTx): _142.RequestDeliverTxAmino;
            fromAminoMsg(object: _142.RequestDeliverTxAminoMsg): _142.RequestDeliverTx;
            fromProtoMsg(message: _142.RequestDeliverTxProtoMsg): _142.RequestDeliverTx;
            toProto(message: _142.RequestDeliverTx): Uint8Array;
            toProtoMsg(message: _142.RequestDeliverTx): _142.RequestDeliverTxProtoMsg;
        };
        RequestEndBlock: {
            encode(message: _142.RequestEndBlock, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number | undefined): _142.RequestEndBlock;
            fromJSON(object: any): _142.RequestEndBlock;
            toJSON(message: _142.RequestEndBlock): unknown;
            fromPartial(object: Partial<_142.RequestEndBlock>): _142.RequestEndBlock;
            fromAmino(object: _142.RequestEndBlockAmino): _142.RequestEndBlock;
            toAmino(message: _142.RequestEndBlock): _142.RequestEndBlockAmino;
            fromAminoMsg(object: _142.RequestEndBlockAminoMsg): _142.RequestEndBlock;
            fromProtoMsg(message: _142.RequestEndBlockProtoMsg): _142.RequestEndBlock;
            toProto(message: _142.RequestEndBlock): Uint8Array;
            toProtoMsg(message: _142.RequestEndBlock): _142.RequestEndBlockProtoMsg;
        };
        RequestCommit: {
            encode(_: _142.RequestCommit, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number | undefined): _142.RequestCommit;
            fromJSON(_: any): _142.RequestCommit;
            toJSON(_: _142.RequestCommit): unknown;
            fromPartial(_: Partial<_142.RequestCommit>): _142.RequestCommit;
            fromAmino(_: _142.RequestCommitAmino): _142.RequestCommit;
            toAmino(_: _142.RequestCommit): _142.RequestCommitAmino;
            fromAminoMsg(object: _142.RequestCommitAminoMsg): _142.RequestCommit;
            fromProtoMsg(message: _142.RequestCommitProtoMsg): _142.RequestCommit;
            toProto(message: _142.RequestCommit): Uint8Array;
            toProtoMsg(message: _142.RequestCommit): _142.RequestCommitProtoMsg;
        };
        RequestListSnapshots: {
            encode(_: _142.RequestListSnapshots, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number | undefined): _142.RequestListSnapshots;
            fromJSON(_: any): _142.RequestListSnapshots;
            toJSON(_: _142.RequestListSnapshots): unknown;
            fromPartial(_: Partial<_142.RequestListSnapshots>): _142.RequestListSnapshots;
            fromAmino(_: _142.RequestListSnapshotsAmino): _142.RequestListSnapshots;
            toAmino(_: _142.RequestListSnapshots): _142.RequestListSnapshotsAmino;
            fromAminoMsg(object: _142.RequestListSnapshotsAminoMsg): _142.RequestListSnapshots;
            fromProtoMsg(message: _142.RequestListSnapshotsProtoMsg): _142.RequestListSnapshots;
            toProto(message: _142.RequestListSnapshots): Uint8Array;
            toProtoMsg(message: _142.RequestListSnapshots): _142.RequestListSnapshotsProtoMsg;
        };
        RequestOfferSnapshot: {
            encode(message: _142.RequestOfferSnapshot, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number | undefined): _142.RequestOfferSnapshot;
            fromJSON(object: any): _142.RequestOfferSnapshot;
            toJSON(message: _142.RequestOfferSnapshot): unknown;
            fromPartial(object: Partial<_142.RequestOfferSnapshot>): _142.RequestOfferSnapshot;
            fromAmino(object: _142.RequestOfferSnapshotAmino): _142.RequestOfferSnapshot;
            toAmino(message: _142.RequestOfferSnapshot): _142.RequestOfferSnapshotAmino;
            fromAminoMsg(object: _142.RequestOfferSnapshotAminoMsg): _142.RequestOfferSnapshot;
            fromProtoMsg(message: _142.RequestOfferSnapshotProtoMsg): _142.RequestOfferSnapshot;
            toProto(message: _142.RequestOfferSnapshot): Uint8Array;
            toProtoMsg(message: _142.RequestOfferSnapshot): _142.RequestOfferSnapshotProtoMsg;
        };
        RequestLoadSnapshotChunk: {
            encode(message: _142.RequestLoadSnapshotChunk, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number | undefined): _142.RequestLoadSnapshotChunk;
            fromJSON(object: any): _142.RequestLoadSnapshotChunk;
            toJSON(message: _142.RequestLoadSnapshotChunk): unknown;
            fromPartial(object: Partial<_142.RequestLoadSnapshotChunk>): _142.RequestLoadSnapshotChunk;
            fromAmino(object: _142.RequestLoadSnapshotChunkAmino): _142.RequestLoadSnapshotChunk;
            toAmino(message: _142.RequestLoadSnapshotChunk): _142.RequestLoadSnapshotChunkAmino;
            fromAminoMsg(object: _142.RequestLoadSnapshotChunkAminoMsg): _142.RequestLoadSnapshotChunk;
            fromProtoMsg(message: _142.RequestLoadSnapshotChunkProtoMsg): _142.RequestLoadSnapshotChunk;
            toProto(message: _142.RequestLoadSnapshotChunk): Uint8Array;
            toProtoMsg(message: _142.RequestLoadSnapshotChunk): _142.RequestLoadSnapshotChunkProtoMsg;
        };
        RequestApplySnapshotChunk: {
            encode(message: _142.RequestApplySnapshotChunk, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number | undefined): _142.RequestApplySnapshotChunk;
            fromJSON(object: any): _142.RequestApplySnapshotChunk;
            toJSON(message: _142.RequestApplySnapshotChunk): unknown;
            fromPartial(object: Partial<_142.RequestApplySnapshotChunk>): _142.RequestApplySnapshotChunk;
            fromAmino(object: _142.RequestApplySnapshotChunkAmino): _142.RequestApplySnapshotChunk;
            toAmino(message: _142.RequestApplySnapshotChunk): _142.RequestApplySnapshotChunkAmino;
            fromAminoMsg(object: _142.RequestApplySnapshotChunkAminoMsg): _142.RequestApplySnapshotChunk;
            fromProtoMsg(message: _142.RequestApplySnapshotChunkProtoMsg): _142.RequestApplySnapshotChunk;
            toProto(message: _142.RequestApplySnapshotChunk): Uint8Array;
            toProtoMsg(message: _142.RequestApplySnapshotChunk): _142.RequestApplySnapshotChunkProtoMsg;
        };
        RequestPrepareProposal: {
            encode(message: _142.RequestPrepareProposal, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number | undefined): _142.RequestPrepareProposal;
            fromJSON(object: any): _142.RequestPrepareProposal;
            toJSON(message: _142.RequestPrepareProposal): unknown;
            fromPartial(object: Partial<_142.RequestPrepareProposal>): _142.RequestPrepareProposal;
            fromAmino(object: _142.RequestPrepareProposalAmino): _142.RequestPrepareProposal;
            toAmino(message: _142.RequestPrepareProposal): _142.RequestPrepareProposalAmino;
            fromAminoMsg(object: _142.RequestPrepareProposalAminoMsg): _142.RequestPrepareProposal;
            fromProtoMsg(message: _142.RequestPrepareProposalProtoMsg): _142.RequestPrepareProposal;
            toProto(message: _142.RequestPrepareProposal): Uint8Array;
            toProtoMsg(message: _142.RequestPrepareProposal): _142.RequestPrepareProposalProtoMsg;
        };
        RequestProcessProposal: {
            encode(message: _142.RequestProcessProposal, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number | undefined): _142.RequestProcessProposal;
            fromJSON(object: any): _142.RequestProcessProposal;
            toJSON(message: _142.RequestProcessProposal): unknown;
            fromPartial(object: Partial<_142.RequestProcessProposal>): _142.RequestProcessProposal;
            fromAmino(object: _142.RequestProcessProposalAmino): _142.RequestProcessProposal;
            toAmino(message: _142.RequestProcessProposal): _142.RequestProcessProposalAmino;
            fromAminoMsg(object: _142.RequestProcessProposalAminoMsg): _142.RequestProcessProposal;
            fromProtoMsg(message: _142.RequestProcessProposalProtoMsg): _142.RequestProcessProposal;
            toProto(message: _142.RequestProcessProposal): Uint8Array;
            toProtoMsg(message: _142.RequestProcessProposal): _142.RequestProcessProposalProtoMsg;
        };
        Response: {
            encode(message: _142.Response, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number | undefined): _142.Response;
            fromJSON(object: any): _142.Response;
            toJSON(message: _142.Response): unknown;
            fromPartial(object: Partial<_142.Response>): _142.Response;
            fromAmino(object: _142.ResponseAmino): _142.Response;
            toAmino(message: _142.Response): _142.ResponseAmino;
            fromAminoMsg(object: _142.ResponseAminoMsg): _142.Response;
            fromProtoMsg(message: _142.ResponseProtoMsg): _142.Response;
            toProto(message: _142.Response): Uint8Array;
            toProtoMsg(message: _142.Response): _142.ResponseProtoMsg;
        };
        ResponseException: {
            encode(message: _142.ResponseException, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number | undefined): _142.ResponseException;
            fromJSON(object: any): _142.ResponseException;
            toJSON(message: _142.ResponseException): unknown;
            fromPartial(object: Partial<_142.ResponseException>): _142.ResponseException;
            fromAmino(object: _142.ResponseExceptionAmino): _142.ResponseException;
            toAmino(message: _142.ResponseException): _142.ResponseExceptionAmino;
            fromAminoMsg(object: _142.ResponseExceptionAminoMsg): _142.ResponseException;
            fromProtoMsg(message: _142.ResponseExceptionProtoMsg): _142.ResponseException;
            toProto(message: _142.ResponseException): Uint8Array;
            toProtoMsg(message: _142.ResponseException): _142.ResponseExceptionProtoMsg;
        };
        ResponseEcho: {
            encode(message: _142.ResponseEcho, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number | undefined): _142.ResponseEcho;
            fromJSON(object: any): _142.ResponseEcho;
            toJSON(message: _142.ResponseEcho): unknown;
            fromPartial(object: Partial<_142.ResponseEcho>): _142.ResponseEcho;
            fromAmino(object: _142.ResponseEchoAmino): _142.ResponseEcho;
            toAmino(message: _142.ResponseEcho): _142.ResponseEchoAmino;
            fromAminoMsg(object: _142.ResponseEchoAminoMsg): _142.ResponseEcho;
            fromProtoMsg(message: _142.ResponseEchoProtoMsg): _142.ResponseEcho;
            toProto(message: _142.ResponseEcho): Uint8Array;
            toProtoMsg(message: _142.ResponseEcho): _142.ResponseEchoProtoMsg;
        };
        ResponseFlush: {
            encode(_: _142.ResponseFlush, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number | undefined): _142.ResponseFlush;
            fromJSON(_: any): _142.ResponseFlush;
            toJSON(_: _142.ResponseFlush): unknown;
            fromPartial(_: Partial<_142.ResponseFlush>): _142.ResponseFlush;
            fromAmino(_: _142.ResponseFlushAmino): _142.ResponseFlush;
            toAmino(_: _142.ResponseFlush): _142.ResponseFlushAmino;
            fromAminoMsg(object: _142.ResponseFlushAminoMsg): _142.ResponseFlush;
            fromProtoMsg(message: _142.ResponseFlushProtoMsg): _142.ResponseFlush;
            toProto(message: _142.ResponseFlush): Uint8Array;
            toProtoMsg(message: _142.ResponseFlush): _142.ResponseFlushProtoMsg;
        };
        ResponseInfo: {
            encode(message: _142.ResponseInfo, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number | undefined): _142.ResponseInfo;
            fromJSON(object: any): _142.ResponseInfo;
            toJSON(message: _142.ResponseInfo): unknown;
            fromPartial(object: Partial<_142.ResponseInfo>): _142.ResponseInfo;
            fromAmino(object: _142.ResponseInfoAmino): _142.ResponseInfo;
            toAmino(message: _142.ResponseInfo): _142.ResponseInfoAmino;
            fromAminoMsg(object: _142.ResponseInfoAminoMsg): _142.ResponseInfo;
            fromProtoMsg(message: _142.ResponseInfoProtoMsg): _142.ResponseInfo;
            toProto(message: _142.ResponseInfo): Uint8Array;
            toProtoMsg(message: _142.ResponseInfo): _142.ResponseInfoProtoMsg;
        };
        ResponseInitChain: {
            encode(message: _142.ResponseInitChain, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number | undefined): _142.ResponseInitChain;
            fromJSON(object: any): _142.ResponseInitChain;
            toJSON(message: _142.ResponseInitChain): unknown;
            fromPartial(object: Partial<_142.ResponseInitChain>): _142.ResponseInitChain;
            fromAmino(object: _142.ResponseInitChainAmino): _142.ResponseInitChain;
            toAmino(message: _142.ResponseInitChain): _142.ResponseInitChainAmino;
            fromAminoMsg(object: _142.ResponseInitChainAminoMsg): _142.ResponseInitChain;
            fromProtoMsg(message: _142.ResponseInitChainProtoMsg): _142.ResponseInitChain;
            toProto(message: _142.ResponseInitChain): Uint8Array;
            toProtoMsg(message: _142.ResponseInitChain): _142.ResponseInitChainProtoMsg;
        };
        ResponseQuery: {
            encode(message: _142.ResponseQuery, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number | undefined): _142.ResponseQuery;
            fromJSON(object: any): _142.ResponseQuery;
            toJSON(message: _142.ResponseQuery): unknown;
            fromPartial(object: Partial<_142.ResponseQuery>): _142.ResponseQuery;
            fromAmino(object: _142.ResponseQueryAmino): _142.ResponseQuery;
            toAmino(message: _142.ResponseQuery): _142.ResponseQueryAmino;
            fromAminoMsg(object: _142.ResponseQueryAminoMsg): _142.ResponseQuery;
            fromProtoMsg(message: _142.ResponseQueryProtoMsg): _142.ResponseQuery;
            toProto(message: _142.ResponseQuery): Uint8Array;
            toProtoMsg(message: _142.ResponseQuery): _142.ResponseQueryProtoMsg;
        };
        ResponseBeginBlock: {
            encode(message: _142.ResponseBeginBlock, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number | undefined): _142.ResponseBeginBlock;
            fromJSON(object: any): _142.ResponseBeginBlock;
            toJSON(message: _142.ResponseBeginBlock): unknown;
            fromPartial(object: Partial<_142.ResponseBeginBlock>): _142.ResponseBeginBlock;
            fromAmino(object: _142.ResponseBeginBlockAmino): _142.ResponseBeginBlock;
            toAmino(message: _142.ResponseBeginBlock): _142.ResponseBeginBlockAmino;
            fromAminoMsg(object: _142.ResponseBeginBlockAminoMsg): _142.ResponseBeginBlock;
            fromProtoMsg(message: _142.ResponseBeginBlockProtoMsg): _142.ResponseBeginBlock;
            toProto(message: _142.ResponseBeginBlock): Uint8Array;
            toProtoMsg(message: _142.ResponseBeginBlock): _142.ResponseBeginBlockProtoMsg;
        };
        ResponseCheckTx: {
            encode(message: _142.ResponseCheckTx, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number | undefined): _142.ResponseCheckTx;
            fromJSON(object: any): _142.ResponseCheckTx;
            toJSON(message: _142.ResponseCheckTx): unknown;
            fromPartial(object: Partial<_142.ResponseCheckTx>): _142.ResponseCheckTx;
            fromAmino(object: _142.ResponseCheckTxAmino): _142.ResponseCheckTx;
            toAmino(message: _142.ResponseCheckTx): _142.ResponseCheckTxAmino;
            fromAminoMsg(object: _142.ResponseCheckTxAminoMsg): _142.ResponseCheckTx;
            fromProtoMsg(message: _142.ResponseCheckTxProtoMsg): _142.ResponseCheckTx;
            toProto(message: _142.ResponseCheckTx): Uint8Array;
            toProtoMsg(message: _142.ResponseCheckTx): _142.ResponseCheckTxProtoMsg;
        };
        ResponseDeliverTx: {
            encode(message: _142.ResponseDeliverTx, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number | undefined): _142.ResponseDeliverTx;
            fromJSON(object: any): _142.ResponseDeliverTx;
            toJSON(message: _142.ResponseDeliverTx): unknown;
            fromPartial(object: Partial<_142.ResponseDeliverTx>): _142.ResponseDeliverTx;
            fromAmino(object: _142.ResponseDeliverTxAmino): _142.ResponseDeliverTx;
            toAmino(message: _142.ResponseDeliverTx): _142.ResponseDeliverTxAmino;
            fromAminoMsg(object: _142.ResponseDeliverTxAminoMsg): _142.ResponseDeliverTx;
            fromProtoMsg(message: _142.ResponseDeliverTxProtoMsg): _142.ResponseDeliverTx;
            toProto(message: _142.ResponseDeliverTx): Uint8Array;
            toProtoMsg(message: _142.ResponseDeliverTx): _142.ResponseDeliverTxProtoMsg;
        };
        ResponseEndBlock: {
            encode(message: _142.ResponseEndBlock, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number | undefined): _142.ResponseEndBlock;
            fromJSON(object: any): _142.ResponseEndBlock;
            toJSON(message: _142.ResponseEndBlock): unknown;
            fromPartial(object: Partial<_142.ResponseEndBlock>): _142.ResponseEndBlock;
            fromAmino(object: _142.ResponseEndBlockAmino): _142.ResponseEndBlock;
            toAmino(message: _142.ResponseEndBlock): _142.ResponseEndBlockAmino;
            fromAminoMsg(object: _142.ResponseEndBlockAminoMsg): _142.ResponseEndBlock;
            fromProtoMsg(message: _142.ResponseEndBlockProtoMsg): _142.ResponseEndBlock;
            toProto(message: _142.ResponseEndBlock): Uint8Array;
            toProtoMsg(message: _142.ResponseEndBlock): _142.ResponseEndBlockProtoMsg;
        };
        ResponseCommit: {
            encode(message: _142.ResponseCommit, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number | undefined): _142.ResponseCommit;
            fromJSON(object: any): _142.ResponseCommit;
            toJSON(message: _142.ResponseCommit): unknown;
            fromPartial(object: Partial<_142.ResponseCommit>): _142.ResponseCommit;
            fromAmino(object: _142.ResponseCommitAmino): _142.ResponseCommit;
            toAmino(message: _142.ResponseCommit): _142.ResponseCommitAmino;
            fromAminoMsg(object: _142.ResponseCommitAminoMsg): _142.ResponseCommit;
            fromProtoMsg(message: _142.ResponseCommitProtoMsg): _142.ResponseCommit;
            toProto(message: _142.ResponseCommit): Uint8Array;
            toProtoMsg(message: _142.ResponseCommit): _142.ResponseCommitProtoMsg;
        };
        ResponseListSnapshots: {
            encode(message: _142.ResponseListSnapshots, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number | undefined): _142.ResponseListSnapshots;
            fromJSON(object: any): _142.ResponseListSnapshots;
            toJSON(message: _142.ResponseListSnapshots): unknown;
            fromPartial(object: Partial<_142.ResponseListSnapshots>): _142.ResponseListSnapshots;
            fromAmino(object: _142.ResponseListSnapshotsAmino): _142.ResponseListSnapshots;
            toAmino(message: _142.ResponseListSnapshots): _142.ResponseListSnapshotsAmino;
            fromAminoMsg(object: _142.ResponseListSnapshotsAminoMsg): _142.ResponseListSnapshots;
            fromProtoMsg(message: _142.ResponseListSnapshotsProtoMsg): _142.ResponseListSnapshots;
            toProto(message: _142.ResponseListSnapshots): Uint8Array;
            toProtoMsg(message: _142.ResponseListSnapshots): _142.ResponseListSnapshotsProtoMsg;
        };
        ResponseOfferSnapshot: {
            encode(message: _142.ResponseOfferSnapshot, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number | undefined): _142.ResponseOfferSnapshot;
            fromJSON(object: any): _142.ResponseOfferSnapshot;
            toJSON(message: _142.ResponseOfferSnapshot): unknown;
            fromPartial(object: Partial<_142.ResponseOfferSnapshot>): _142.ResponseOfferSnapshot;
            fromAmino(object: _142.ResponseOfferSnapshotAmino): _142.ResponseOfferSnapshot;
            toAmino(message: _142.ResponseOfferSnapshot): _142.ResponseOfferSnapshotAmino;
            fromAminoMsg(object: _142.ResponseOfferSnapshotAminoMsg): _142.ResponseOfferSnapshot;
            fromProtoMsg(message: _142.ResponseOfferSnapshotProtoMsg): _142.ResponseOfferSnapshot;
            toProto(message: _142.ResponseOfferSnapshot): Uint8Array;
            toProtoMsg(message: _142.ResponseOfferSnapshot): _142.ResponseOfferSnapshotProtoMsg;
        };
        ResponseLoadSnapshotChunk: {
            encode(message: _142.ResponseLoadSnapshotChunk, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number | undefined): _142.ResponseLoadSnapshotChunk;
            fromJSON(object: any): _142.ResponseLoadSnapshotChunk;
            toJSON(message: _142.ResponseLoadSnapshotChunk): unknown;
            fromPartial(object: Partial<_142.ResponseLoadSnapshotChunk>): _142.ResponseLoadSnapshotChunk;
            fromAmino(object: _142.ResponseLoadSnapshotChunkAmino): _142.ResponseLoadSnapshotChunk;
            toAmino(message: _142.ResponseLoadSnapshotChunk): _142.ResponseLoadSnapshotChunkAmino;
            fromAminoMsg(object: _142.ResponseLoadSnapshotChunkAminoMsg): _142.ResponseLoadSnapshotChunk;
            fromProtoMsg(message: _142.ResponseLoadSnapshotChunkProtoMsg): _142.ResponseLoadSnapshotChunk;
            toProto(message: _142.ResponseLoadSnapshotChunk): Uint8Array;
            toProtoMsg(message: _142.ResponseLoadSnapshotChunk): _142.ResponseLoadSnapshotChunkProtoMsg;
        };
        ResponseApplySnapshotChunk: {
            encode(message: _142.ResponseApplySnapshotChunk, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number | undefined): _142.ResponseApplySnapshotChunk;
            fromJSON(object: any): _142.ResponseApplySnapshotChunk;
            toJSON(message: _142.ResponseApplySnapshotChunk): unknown;
            fromPartial(object: Partial<_142.ResponseApplySnapshotChunk>): _142.ResponseApplySnapshotChunk;
            fromAmino(object: _142.ResponseApplySnapshotChunkAmino): _142.ResponseApplySnapshotChunk;
            toAmino(message: _142.ResponseApplySnapshotChunk): _142.ResponseApplySnapshotChunkAmino;
            fromAminoMsg(object: _142.ResponseApplySnapshotChunkAminoMsg): _142.ResponseApplySnapshotChunk;
            fromProtoMsg(message: _142.ResponseApplySnapshotChunkProtoMsg): _142.ResponseApplySnapshotChunk;
            toProto(message: _142.ResponseApplySnapshotChunk): Uint8Array;
            toProtoMsg(message: _142.ResponseApplySnapshotChunk): _142.ResponseApplySnapshotChunkProtoMsg;
        };
        ResponsePrepareProposal: {
            encode(message: _142.ResponsePrepareProposal, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number | undefined): _142.ResponsePrepareProposal;
            fromJSON(object: any): _142.ResponsePrepareProposal;
            toJSON(message: _142.ResponsePrepareProposal): unknown;
            fromPartial(object: Partial<_142.ResponsePrepareProposal>): _142.ResponsePrepareProposal;
            fromAmino(object: _142.ResponsePrepareProposalAmino): _142.ResponsePrepareProposal;
            toAmino(message: _142.ResponsePrepareProposal): _142.ResponsePrepareProposalAmino;
            fromAminoMsg(object: _142.ResponsePrepareProposalAminoMsg): _142.ResponsePrepareProposal;
            fromProtoMsg(message: _142.ResponsePrepareProposalProtoMsg): _142.ResponsePrepareProposal;
            toProto(message: _142.ResponsePrepareProposal): Uint8Array;
            toProtoMsg(message: _142.ResponsePrepareProposal): _142.ResponsePrepareProposalProtoMsg;
        };
        ResponseProcessProposal: {
            encode(message: _142.ResponseProcessProposal, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number | undefined): _142.ResponseProcessProposal;
            fromJSON(object: any): _142.ResponseProcessProposal;
            toJSON(message: _142.ResponseProcessProposal): unknown;
            fromPartial(object: Partial<_142.ResponseProcessProposal>): _142.ResponseProcessProposal;
            fromAmino(object: _142.ResponseProcessProposalAmino): _142.ResponseProcessProposal;
            toAmino(message: _142.ResponseProcessProposal): _142.ResponseProcessProposalAmino;
            fromAminoMsg(object: _142.ResponseProcessProposalAminoMsg): _142.ResponseProcessProposal;
            fromProtoMsg(message: _142.ResponseProcessProposalProtoMsg): _142.ResponseProcessProposal;
            toProto(message: _142.ResponseProcessProposal): Uint8Array;
            toProtoMsg(message: _142.ResponseProcessProposal): _142.ResponseProcessProposalProtoMsg;
        };
        CommitInfo: {
            encode(message: _142.CommitInfo, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number | undefined): _142.CommitInfo;
            fromJSON(object: any): _142.CommitInfo;
            toJSON(message: _142.CommitInfo): unknown;
            fromPartial(object: Partial<_142.CommitInfo>): _142.CommitInfo;
            fromAmino(object: _142.CommitInfoAmino): _142.CommitInfo;
            toAmino(message: _142.CommitInfo): _142.CommitInfoAmino;
            fromAminoMsg(object: _142.CommitInfoAminoMsg): _142.CommitInfo;
            fromProtoMsg(message: _142.CommitInfoProtoMsg): _142.CommitInfo;
            toProto(message: _142.CommitInfo): Uint8Array;
            toProtoMsg(message: _142.CommitInfo): _142.CommitInfoProtoMsg;
        };
        ExtendedCommitInfo: {
            encode(message: _142.ExtendedCommitInfo, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number | undefined): _142.ExtendedCommitInfo;
            fromJSON(object: any): _142.ExtendedCommitInfo;
            toJSON(message: _142.ExtendedCommitInfo): unknown;
            fromPartial(object: Partial<_142.ExtendedCommitInfo>): _142.ExtendedCommitInfo;
            fromAmino(object: _142.ExtendedCommitInfoAmino): _142.ExtendedCommitInfo;
            toAmino(message: _142.ExtendedCommitInfo): _142.ExtendedCommitInfoAmino;
            fromAminoMsg(object: _142.ExtendedCommitInfoAminoMsg): _142.ExtendedCommitInfo;
            fromProtoMsg(message: _142.ExtendedCommitInfoProtoMsg): _142.ExtendedCommitInfo;
            toProto(message: _142.ExtendedCommitInfo): Uint8Array;
            toProtoMsg(message: _142.ExtendedCommitInfo): _142.ExtendedCommitInfoProtoMsg;
        };
        Event: {
            encode(message: _142.Event, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number | undefined): _142.Event;
            fromJSON(object: any): _142.Event;
            toJSON(message: _142.Event): unknown;
            fromPartial(object: Partial<_142.Event>): _142.Event;
            fromAmino(object: _142.EventAmino): _142.Event;
            toAmino(message: _142.Event): _142.EventAmino;
            fromAminoMsg(object: _142.EventAminoMsg): _142.Event;
            fromProtoMsg(message: _142.EventProtoMsg): _142.Event;
            toProto(message: _142.Event): Uint8Array;
            toProtoMsg(message: _142.Event): _142.EventProtoMsg;
        };
        EventAttribute: {
            encode(message: _142.EventAttribute, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number | undefined): _142.EventAttribute;
            fromJSON(object: any): _142.EventAttribute;
            toJSON(message: _142.EventAttribute): unknown;
            fromPartial(object: Partial<_142.EventAttribute>): _142.EventAttribute;
            fromAmino(object: _142.EventAttributeAmino): _142.EventAttribute;
            toAmino(message: _142.EventAttribute): _142.EventAttributeAmino;
            fromAminoMsg(object: _142.EventAttributeAminoMsg): _142.EventAttribute;
            fromProtoMsg(message: _142.EventAttributeProtoMsg): _142.EventAttribute;
            toProto(message: _142.EventAttribute): Uint8Array;
            toProtoMsg(message: _142.EventAttribute): _142.EventAttributeProtoMsg;
        };
        TxResult: {
            encode(message: _142.TxResult, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number | undefined): _142.TxResult;
            fromJSON(object: any): _142.TxResult;
            toJSON(message: _142.TxResult): unknown;
            fromPartial(object: Partial<_142.TxResult>): _142.TxResult;
            fromAmino(object: _142.TxResultAmino): _142.TxResult;
            toAmino(message: _142.TxResult): _142.TxResultAmino;
            fromAminoMsg(object: _142.TxResultAminoMsg): _142.TxResult;
            fromProtoMsg(message: _142.TxResultProtoMsg): _142.TxResult;
            toProto(message: _142.TxResult): Uint8Array;
            toProtoMsg(message: _142.TxResult): _142.TxResultProtoMsg;
        };
        Validator: {
            encode(message: _142.Validator, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number | undefined): _142.Validator;
            fromJSON(object: any): _142.Validator;
            toJSON(message: _142.Validator): unknown;
            fromPartial(object: Partial<_142.Validator>): _142.Validator;
            fromAmino(object: _142.ValidatorAmino): _142.Validator;
            toAmino(message: _142.Validator): _142.ValidatorAmino;
            fromAminoMsg(object: _142.ValidatorAminoMsg): _142.Validator;
            fromProtoMsg(message: _142.ValidatorProtoMsg): _142.Validator;
            toProto(message: _142.Validator): Uint8Array;
            toProtoMsg(message: _142.Validator): _142.ValidatorProtoMsg;
        };
        ValidatorUpdate: {
            encode(message: _142.ValidatorUpdate, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number | undefined): _142.ValidatorUpdate;
            fromJSON(object: any): _142.ValidatorUpdate;
            toJSON(message: _142.ValidatorUpdate): unknown;
            fromPartial(object: Partial<_142.ValidatorUpdate>): _142.ValidatorUpdate;
            fromAmino(object: _142.ValidatorUpdateAmino): _142.ValidatorUpdate;
            toAmino(message: _142.ValidatorUpdate): _142.ValidatorUpdateAmino;
            fromAminoMsg(object: _142.ValidatorUpdateAminoMsg): _142.ValidatorUpdate;
            fromProtoMsg(message: _142.ValidatorUpdateProtoMsg): _142.ValidatorUpdate;
            toProto(message: _142.ValidatorUpdate): Uint8Array;
            toProtoMsg(message: _142.ValidatorUpdate): _142.ValidatorUpdateProtoMsg;
        };
        VoteInfo: {
            encode(message: _142.VoteInfo, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number | undefined): _142.VoteInfo;
            fromJSON(object: any): _142.VoteInfo;
            toJSON(message: _142.VoteInfo): unknown;
            fromPartial(object: Partial<_142.VoteInfo>): _142.VoteInfo;
            fromAmino(object: _142.VoteInfoAmino): _142.VoteInfo;
            toAmino(message: _142.VoteInfo): _142.VoteInfoAmino;
            fromAminoMsg(object: _142.VoteInfoAminoMsg): _142.VoteInfo;
            fromProtoMsg(message: _142.VoteInfoProtoMsg): _142.VoteInfo;
            toProto(message: _142.VoteInfo): Uint8Array;
            toProtoMsg(message: _142.VoteInfo): _142.VoteInfoProtoMsg;
        };
        ExtendedVoteInfo: {
            encode(message: _142.ExtendedVoteInfo, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number | undefined): _142.ExtendedVoteInfo;
            fromJSON(object: any): _142.ExtendedVoteInfo;
            toJSON(message: _142.ExtendedVoteInfo): unknown;
            fromPartial(object: Partial<_142.ExtendedVoteInfo>): _142.ExtendedVoteInfo;
            fromAmino(object: _142.ExtendedVoteInfoAmino): _142.ExtendedVoteInfo;
            toAmino(message: _142.ExtendedVoteInfo): _142.ExtendedVoteInfoAmino;
            fromAminoMsg(object: _142.ExtendedVoteInfoAminoMsg): _142.ExtendedVoteInfo;
            fromProtoMsg(message: _142.ExtendedVoteInfoProtoMsg): _142.ExtendedVoteInfo;
            toProto(message: _142.ExtendedVoteInfo): Uint8Array;
            toProtoMsg(message: _142.ExtendedVoteInfo): _142.ExtendedVoteInfoProtoMsg;
        };
        Misbehavior: {
            encode(message: _142.Misbehavior, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number | undefined): _142.Misbehavior;
            fromJSON(object: any): _142.Misbehavior;
            toJSON(message: _142.Misbehavior): unknown;
            fromPartial(object: Partial<_142.Misbehavior>): _142.Misbehavior;
            fromAmino(object: _142.MisbehaviorAmino): _142.Misbehavior;
            toAmino(message: _142.Misbehavior): _142.MisbehaviorAmino;
            fromAminoMsg(object: _142.MisbehaviorAminoMsg): _142.Misbehavior;
            fromProtoMsg(message: _142.MisbehaviorProtoMsg): _142.Misbehavior;
            toProto(message: _142.Misbehavior): Uint8Array;
            toProtoMsg(message: _142.Misbehavior): _142.MisbehaviorProtoMsg;
        };
        Snapshot: {
            encode(message: _142.Snapshot, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number | undefined): _142.Snapshot;
            fromJSON(object: any): _142.Snapshot;
            toJSON(message: _142.Snapshot): unknown;
            fromPartial(object: Partial<_142.Snapshot>): _142.Snapshot;
            fromAmino(object: _142.SnapshotAmino): _142.Snapshot;
            toAmino(message: _142.Snapshot): _142.SnapshotAmino;
            fromAminoMsg(object: _142.SnapshotAminoMsg): _142.Snapshot;
            fromProtoMsg(message: _142.SnapshotProtoMsg): _142.Snapshot;
            toProto(message: _142.Snapshot): Uint8Array;
            toProtoMsg(message: _142.Snapshot): _142.SnapshotProtoMsg;
        };
    };
    const crypto: {
        Proof: {
            encode(message: _144.Proof, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number | undefined): _144.Proof;
            fromJSON(object: any): _144.Proof;
            toJSON(message: _144.Proof): unknown;
            fromPartial(object: Partial<_144.Proof>): _144.Proof;
            fromAmino(object: _144.ProofAmino): _144.Proof;
            toAmino(message: _144.Proof): _144.ProofAmino;
            fromAminoMsg(object: _144.ProofAminoMsg): _144.Proof;
            fromProtoMsg(message: _144.ProofProtoMsg): _144.Proof;
            toProto(message: _144.Proof): Uint8Array;
            toProtoMsg(message: _144.Proof): _144.ProofProtoMsg;
        };
        ValueOp: {
            encode(message: _144.ValueOp, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number | undefined): _144.ValueOp;
            fromJSON(object: any): _144.ValueOp;
            toJSON(message: _144.ValueOp): unknown;
            fromPartial(object: Partial<_144.ValueOp>): _144.ValueOp;
            fromAmino(object: _144.ValueOpAmino): _144.ValueOp;
            toAmino(message: _144.ValueOp): _144.ValueOpAmino;
            fromAminoMsg(object: _144.ValueOpAminoMsg): _144.ValueOp;
            fromProtoMsg(message: _144.ValueOpProtoMsg): _144.ValueOp;
            toProto(message: _144.ValueOp): Uint8Array;
            toProtoMsg(message: _144.ValueOp): _144.ValueOpProtoMsg;
        };
        DominoOp: {
            encode(message: _144.DominoOp, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number | undefined): _144.DominoOp;
            fromJSON(object: any): _144.DominoOp;
            toJSON(message: _144.DominoOp): unknown;
            fromPartial(object: Partial<_144.DominoOp>): _144.DominoOp;
            fromAmino(object: _144.DominoOpAmino): _144.DominoOp;
            toAmino(message: _144.DominoOp): _144.DominoOpAmino;
            fromAminoMsg(object: _144.DominoOpAminoMsg): _144.DominoOp;
            fromProtoMsg(message: _144.DominoOpProtoMsg): _144.DominoOp;
            toProto(message: _144.DominoOp): Uint8Array;
            toProtoMsg(message: _144.DominoOp): _144.DominoOpProtoMsg;
        };
        ProofOp: {
            encode(message: _144.ProofOp, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number | undefined): _144.ProofOp;
            fromJSON(object: any): _144.ProofOp;
            toJSON(message: _144.ProofOp): unknown;
            fromPartial(object: Partial<_144.ProofOp>): _144.ProofOp;
            fromAmino(object: _144.ProofOpAmino): _144.ProofOp;
            toAmino(message: _144.ProofOp): _144.ProofOpAmino;
            fromAminoMsg(object: _144.ProofOpAminoMsg): _144.ProofOp;
            fromProtoMsg(message: _144.ProofOpProtoMsg): _144.ProofOp;
            toProto(message: _144.ProofOp): Uint8Array;
            toProtoMsg(message: _144.ProofOp): _144.ProofOpProtoMsg;
        };
        ProofOps: {
            encode(message: _144.ProofOps, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number | undefined): _144.ProofOps;
            fromJSON(object: any): _144.ProofOps;
            toJSON(message: _144.ProofOps): unknown;
            fromPartial(object: Partial<_144.ProofOps>): _144.ProofOps;
            fromAmino(object: _144.ProofOpsAmino): _144.ProofOps;
            toAmino(message: _144.ProofOps): _144.ProofOpsAmino;
            fromAminoMsg(object: _144.ProofOpsAminoMsg): _144.ProofOps;
            fromProtoMsg(message: _144.ProofOpsProtoMsg): _144.ProofOps;
            toProto(message: _144.ProofOps): Uint8Array;
            toProtoMsg(message: _144.ProofOps): _144.ProofOpsProtoMsg;
        };
        PublicKey: {
            encode(message: _143.PublicKey, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number | undefined): _143.PublicKey;
            fromJSON(object: any): _143.PublicKey;
            toJSON(message: _143.PublicKey): unknown;
            fromPartial(object: Partial<_143.PublicKey>): _143.PublicKey;
            fromAmino(object: _143.PublicKeyAmino): _143.PublicKey;
            toAmino(message: _143.PublicKey): _143.PublicKeyAmino;
            fromAminoMsg(object: _143.PublicKeyAminoMsg): _143.PublicKey;
            fromProtoMsg(message: _143.PublicKeyProtoMsg): _143.PublicKey;
            toProto(message: _143.PublicKey): Uint8Array;
            toProtoMsg(message: _143.PublicKey): _143.PublicKeyProtoMsg;
        };
    };
    namespace libs {
        const bits: {
            BitArray: {
                encode(message: _145.BitArray, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
                decode(input: Uint8Array | import("protobufjs").Reader, length?: number | undefined): _145.BitArray;
                fromJSON(object: any): _145.BitArray;
                toJSON(message: _145.BitArray): unknown;
                fromPartial(object: Partial<_145.BitArray>): _145.BitArray;
                fromAmino(object: _145.BitArrayAmino): _145.BitArray;
                toAmino(message: _145.BitArray): _145.BitArrayAmino;
                fromAminoMsg(object: _145.BitArrayAminoMsg): _145.BitArray;
                fromProtoMsg(message: _145.BitArrayProtoMsg): _145.BitArray;
                toProto(message: _145.BitArray): Uint8Array;
                toProtoMsg(message: _145.BitArray): _145.BitArrayProtoMsg;
            };
        };
    }
    const p2p: {
        NetAddress: {
            encode(message: _146.NetAddress, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number | undefined): _146.NetAddress;
            fromJSON(object: any): _146.NetAddress;
            toJSON(message: _146.NetAddress): unknown;
            fromPartial(object: Partial<_146.NetAddress>): _146.NetAddress;
            fromAmino(object: _146.NetAddressAmino): _146.NetAddress;
            toAmino(message: _146.NetAddress): _146.NetAddressAmino;
            fromAminoMsg(object: _146.NetAddressAminoMsg): _146.NetAddress;
            fromProtoMsg(message: _146.NetAddressProtoMsg): _146.NetAddress;
            toProto(message: _146.NetAddress): Uint8Array;
            toProtoMsg(message: _146.NetAddress): _146.NetAddressProtoMsg;
        };
        ProtocolVersion: {
            encode(message: _146.ProtocolVersion, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number | undefined): _146.ProtocolVersion;
            fromJSON(object: any): _146.ProtocolVersion;
            toJSON(message: _146.ProtocolVersion): unknown;
            fromPartial(object: Partial<_146.ProtocolVersion>): _146.ProtocolVersion;
            fromAmino(object: _146.ProtocolVersionAmino): _146.ProtocolVersion;
            toAmino(message: _146.ProtocolVersion): _146.ProtocolVersionAmino;
            fromAminoMsg(object: _146.ProtocolVersionAminoMsg): _146.ProtocolVersion;
            fromProtoMsg(message: _146.ProtocolVersionProtoMsg): _146.ProtocolVersion;
            toProto(message: _146.ProtocolVersion): Uint8Array;
            toProtoMsg(message: _146.ProtocolVersion): _146.ProtocolVersionProtoMsg;
        };
        DefaultNodeInfo: {
            encode(message: _146.DefaultNodeInfo, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number | undefined): _146.DefaultNodeInfo;
            fromJSON(object: any): _146.DefaultNodeInfo;
            toJSON(message: _146.DefaultNodeInfo): unknown;
            fromPartial(object: Partial<_146.DefaultNodeInfo>): _146.DefaultNodeInfo;
            fromAmino(object: _146.DefaultNodeInfoAmino): _146.DefaultNodeInfo;
            toAmino(message: _146.DefaultNodeInfo): _146.DefaultNodeInfoAmino;
            fromAminoMsg(object: _146.DefaultNodeInfoAminoMsg): _146.DefaultNodeInfo;
            fromProtoMsg(message: _146.DefaultNodeInfoProtoMsg): _146.DefaultNodeInfo;
            toProto(message: _146.DefaultNodeInfo): Uint8Array;
            toProtoMsg(message: _146.DefaultNodeInfo): _146.DefaultNodeInfoProtoMsg;
        };
        DefaultNodeInfoOther: {
            encode(message: _146.DefaultNodeInfoOther, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number | undefined): _146.DefaultNodeInfoOther;
            fromJSON(object: any): _146.DefaultNodeInfoOther;
            toJSON(message: _146.DefaultNodeInfoOther): unknown;
            fromPartial(object: Partial<_146.DefaultNodeInfoOther>): _146.DefaultNodeInfoOther;
            fromAmino(object: _146.DefaultNodeInfoOtherAmino): _146.DefaultNodeInfoOther;
            toAmino(message: _146.DefaultNodeInfoOther): _146.DefaultNodeInfoOtherAmino;
            fromAminoMsg(object: _146.DefaultNodeInfoOtherAminoMsg): _146.DefaultNodeInfoOther;
            fromProtoMsg(message: _146.DefaultNodeInfoOtherProtoMsg): _146.DefaultNodeInfoOther;
            toProto(message: _146.DefaultNodeInfoOther): Uint8Array;
            toProtoMsg(message: _146.DefaultNodeInfoOther): _146.DefaultNodeInfoOtherProtoMsg;
        };
    };
    const types: {
        ValidatorSet: {
            encode(message: _151.ValidatorSet, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number | undefined): _151.ValidatorSet;
            fromJSON(object: any): _151.ValidatorSet;
            toJSON(message: _151.ValidatorSet): unknown;
            fromPartial(object: Partial<_151.ValidatorSet>): _151.ValidatorSet;
            fromAmino(object: _151.ValidatorSetAmino): _151.ValidatorSet;
            toAmino(message: _151.ValidatorSet): _151.ValidatorSetAmino;
            fromAminoMsg(object: _151.ValidatorSetAminoMsg): _151.ValidatorSet;
            fromProtoMsg(message: _151.ValidatorSetProtoMsg): _151.ValidatorSet;
            toProto(message: _151.ValidatorSet): Uint8Array;
            toProtoMsg(message: _151.ValidatorSet): _151.ValidatorSetProtoMsg;
        };
        Validator: {
            encode(message: _151.Validator, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number | undefined): _151.Validator;
            fromJSON(object: any): _151.Validator;
            toJSON(message: _151.Validator): unknown;
            fromPartial(object: Partial<_151.Validator>): _151.Validator;
            fromAmino(object: _151.ValidatorAmino): _151.Validator;
            toAmino(message: _151.Validator): _151.ValidatorAmino;
            fromAminoMsg(object: _151.ValidatorAminoMsg): _151.Validator;
            fromProtoMsg(message: _151.ValidatorProtoMsg): _151.Validator;
            toProto(message: _151.Validator): Uint8Array;
            toProtoMsg(message: _151.Validator): _151.ValidatorProtoMsg;
        };
        SimpleValidator: {
            encode(message: _151.SimpleValidator, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number | undefined): _151.SimpleValidator;
            fromJSON(object: any): _151.SimpleValidator;
            toJSON(message: _151.SimpleValidator): unknown;
            fromPartial(object: Partial<_151.SimpleValidator>): _151.SimpleValidator;
            fromAmino(object: _151.SimpleValidatorAmino): _151.SimpleValidator;
            toAmino(message: _151.SimpleValidator): _151.SimpleValidatorAmino;
            fromAminoMsg(object: _151.SimpleValidatorAminoMsg): _151.SimpleValidator;
            fromProtoMsg(message: _151.SimpleValidatorProtoMsg): _151.SimpleValidator;
            toProto(message: _151.SimpleValidator): Uint8Array;
            toProtoMsg(message: _151.SimpleValidator): _151.SimpleValidatorProtoMsg;
        };
        blockIDFlagFromJSON(object: any): _150.BlockIDFlag;
        blockIDFlagToJSON(object: _150.BlockIDFlag): string;
        signedMsgTypeFromJSON(object: any): _150.SignedMsgType;
        signedMsgTypeToJSON(object: _150.SignedMsgType): string;
        BlockIDFlag: typeof _150.BlockIDFlag;
        BlockIDFlagSDKType: typeof _150.BlockIDFlag;
        BlockIDFlagAmino: typeof _150.BlockIDFlag;
        SignedMsgType: typeof _150.SignedMsgType;
        SignedMsgTypeSDKType: typeof _150.SignedMsgType;
        SignedMsgTypeAmino: typeof _150.SignedMsgType;
        PartSetHeader: {
            encode(message: _150.PartSetHeader, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number | undefined): _150.PartSetHeader;
            fromJSON(object: any): _150.PartSetHeader;
            toJSON(message: _150.PartSetHeader): unknown;
            fromPartial(object: Partial<_150.PartSetHeader>): _150.PartSetHeader;
            fromAmino(object: _150.PartSetHeaderAmino): _150.PartSetHeader;
            toAmino(message: _150.PartSetHeader): _150.PartSetHeaderAmino;
            fromAminoMsg(object: _150.PartSetHeaderAminoMsg): _150.PartSetHeader;
            fromProtoMsg(message: _150.PartSetHeaderProtoMsg): _150.PartSetHeader;
            toProto(message: _150.PartSetHeader): Uint8Array;
            toProtoMsg(message: _150.PartSetHeader): _150.PartSetHeaderProtoMsg;
        };
        Part: {
            encode(message: _150.Part, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number | undefined): _150.Part;
            fromJSON(object: any): _150.Part;
            toJSON(message: _150.Part): unknown;
            fromPartial(object: Partial<_150.Part>): _150.Part;
            fromAmino(object: _150.PartAmino): _150.Part;
            toAmino(message: _150.Part): _150.PartAmino;
            fromAminoMsg(object: _150.PartAminoMsg): _150.Part;
            fromProtoMsg(message: _150.PartProtoMsg): _150.Part;
            toProto(message: _150.Part): Uint8Array;
            toProtoMsg(message: _150.Part): _150.PartProtoMsg;
        };
        BlockID: {
            encode(message: _150.BlockID, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number | undefined): _150.BlockID;
            fromJSON(object: any): _150.BlockID;
            toJSON(message: _150.BlockID): unknown;
            fromPartial(object: Partial<_150.BlockID>): _150.BlockID;
            fromAmino(object: _150.BlockIDAmino): _150.BlockID;
            toAmino(message: _150.BlockID): _150.BlockIDAmino;
            fromAminoMsg(object: _150.BlockIDAminoMsg): _150.BlockID;
            fromProtoMsg(message: _150.BlockIDProtoMsg): _150.BlockID;
            toProto(message: _150.BlockID): Uint8Array;
            toProtoMsg(message: _150.BlockID): _150.BlockIDProtoMsg;
        };
        Header: {
            encode(message: _150.Header, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number | undefined): _150.Header;
            fromJSON(object: any): _150.Header;
            toJSON(message: _150.Header): unknown;
            fromPartial(object: Partial<_150.Header>): _150.Header;
            fromAmino(object: _150.HeaderAmino): _150.Header;
            toAmino(message: _150.Header): _150.HeaderAmino;
            fromAminoMsg(object: _150.HeaderAminoMsg): _150.Header;
            fromProtoMsg(message: _150.HeaderProtoMsg): _150.Header;
            toProto(message: _150.Header): Uint8Array;
            toProtoMsg(message: _150.Header): _150.HeaderProtoMsg;
        };
        Data: {
            encode(message: _150.Data, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number | undefined): _150.Data;
            fromJSON(object: any): _150.Data;
            toJSON(message: _150.Data): unknown;
            fromPartial(object: Partial<_150.Data>): _150.Data;
            fromAmino(object: _150.DataAmino): _150.Data;
            toAmino(message: _150.Data): _150.DataAmino;
            fromAminoMsg(object: _150.DataAminoMsg): _150.Data;
            fromProtoMsg(message: _150.DataProtoMsg): _150.Data;
            toProto(message: _150.Data): Uint8Array;
            toProtoMsg(message: _150.Data): _150.DataProtoMsg;
        };
        Vote: {
            encode(message: _150.Vote, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number | undefined): _150.Vote;
            fromJSON(object: any): _150.Vote;
            toJSON(message: _150.Vote): unknown;
            fromPartial(object: Partial<_150.Vote>): _150.Vote;
            fromAmino(object: _150.VoteAmino): _150.Vote;
            toAmino(message: _150.Vote): _150.VoteAmino;
            fromAminoMsg(object: _150.VoteAminoMsg): _150.Vote;
            fromProtoMsg(message: _150.VoteProtoMsg): _150.Vote;
            toProto(message: _150.Vote): Uint8Array;
            toProtoMsg(message: _150.Vote): _150.VoteProtoMsg;
        };
        Commit: {
            encode(message: _150.Commit, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number | undefined): _150.Commit;
            fromJSON(object: any): _150.Commit;
            toJSON(message: _150.Commit): unknown;
            fromPartial(object: Partial<_150.Commit>): _150.Commit;
            fromAmino(object: _150.CommitAmino): _150.Commit;
            toAmino(message: _150.Commit): _150.CommitAmino;
            fromAminoMsg(object: _150.CommitAminoMsg): _150.Commit;
            fromProtoMsg(message: _150.CommitProtoMsg): _150.Commit;
            toProto(message: _150.Commit): Uint8Array;
            toProtoMsg(message: _150.Commit): _150.CommitProtoMsg;
        };
        CommitSig: {
            encode(message: _150.CommitSig, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number | undefined): _150.CommitSig;
            fromJSON(object: any): _150.CommitSig;
            toJSON(message: _150.CommitSig): unknown;
            fromPartial(object: Partial<_150.CommitSig>): _150.CommitSig;
            fromAmino(object: _150.CommitSigAmino): _150.CommitSig;
            toAmino(message: _150.CommitSig): _150.CommitSigAmino;
            fromAminoMsg(object: _150.CommitSigAminoMsg): _150.CommitSig;
            fromProtoMsg(message: _150.CommitSigProtoMsg): _150.CommitSig;
            toProto(message: _150.CommitSig): Uint8Array;
            toProtoMsg(message: _150.CommitSig): _150.CommitSigProtoMsg;
        };
        Proposal: {
            encode(message: _150.Proposal, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number | undefined): _150.Proposal;
            fromJSON(object: any): _150.Proposal;
            toJSON(message: _150.Proposal): unknown;
            fromPartial(object: Partial<_150.Proposal>): _150.Proposal;
            fromAmino(object: _150.ProposalAmino): _150.Proposal;
            toAmino(message: _150.Proposal): _150.ProposalAmino;
            fromAminoMsg(object: _150.ProposalAminoMsg): _150.Proposal;
            fromProtoMsg(message: _150.ProposalProtoMsg): _150.Proposal;
            toProto(message: _150.Proposal): Uint8Array;
            toProtoMsg(message: _150.Proposal): _150.ProposalProtoMsg;
        };
        SignedHeader: {
            encode(message: _150.SignedHeader, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number | undefined): _150.SignedHeader;
            fromJSON(object: any): _150.SignedHeader;
            toJSON(message: _150.SignedHeader): unknown;
            fromPartial(object: Partial<_150.SignedHeader>): _150.SignedHeader;
            fromAmino(object: _150.SignedHeaderAmino): _150.SignedHeader;
            toAmino(message: _150.SignedHeader): _150.SignedHeaderAmino;
            fromAminoMsg(object: _150.SignedHeaderAminoMsg): _150.SignedHeader;
            fromProtoMsg(message: _150.SignedHeaderProtoMsg): _150.SignedHeader;
            toProto(message: _150.SignedHeader): Uint8Array;
            toProtoMsg(message: _150.SignedHeader): _150.SignedHeaderProtoMsg;
        };
        LightBlock: {
            encode(message: _150.LightBlock, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number | undefined): _150.LightBlock;
            fromJSON(object: any): _150.LightBlock;
            toJSON(message: _150.LightBlock): unknown;
            fromPartial(object: Partial<_150.LightBlock>): _150.LightBlock;
            fromAmino(object: _150.LightBlockAmino): _150.LightBlock;
            toAmino(message: _150.LightBlock): _150.LightBlockAmino;
            fromAminoMsg(object: _150.LightBlockAminoMsg): _150.LightBlock;
            fromProtoMsg(message: _150.LightBlockProtoMsg): _150.LightBlock;
            toProto(message: _150.LightBlock): Uint8Array;
            toProtoMsg(message: _150.LightBlock): _150.LightBlockProtoMsg;
        };
        BlockMeta: {
            encode(message: _150.BlockMeta, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number | undefined): _150.BlockMeta;
            fromJSON(object: any): _150.BlockMeta;
            toJSON(message: _150.BlockMeta): unknown;
            fromPartial(object: Partial<_150.BlockMeta>): _150.BlockMeta;
            fromAmino(object: _150.BlockMetaAmino): _150.BlockMeta;
            toAmino(message: _150.BlockMeta): _150.BlockMetaAmino;
            fromAminoMsg(object: _150.BlockMetaAminoMsg): _150.BlockMeta;
            fromProtoMsg(message: _150.BlockMetaProtoMsg): _150.BlockMeta;
            toProto(message: _150.BlockMeta): Uint8Array;
            toProtoMsg(message: _150.BlockMeta): _150.BlockMetaProtoMsg;
        };
        TxProof: {
            encode(message: _150.TxProof, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number | undefined): _150.TxProof;
            fromJSON(object: any): _150.TxProof;
            toJSON(message: _150.TxProof): unknown;
            fromPartial(object: Partial<_150.TxProof>): _150.TxProof;
            fromAmino(object: _150.TxProofAmino): _150.TxProof;
            toAmino(message: _150.TxProof): _150.TxProofAmino;
            fromAminoMsg(object: _150.TxProofAminoMsg): _150.TxProof;
            fromProtoMsg(message: _150.TxProofProtoMsg): _150.TxProof;
            toProto(message: _150.TxProof): Uint8Array;
            toProtoMsg(message: _150.TxProof): _150.TxProofProtoMsg;
        };
        ConsensusParams: {
            encode(message: _149.ConsensusParams, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number | undefined): _149.ConsensusParams;
            fromJSON(object: any): _149.ConsensusParams;
            toJSON(message: _149.ConsensusParams): unknown;
            fromPartial(object: Partial<_149.ConsensusParams>): _149.ConsensusParams;
            fromAmino(object: _149.ConsensusParamsAmino): _149.ConsensusParams;
            toAmino(message: _149.ConsensusParams): _149.ConsensusParamsAmino;
            fromAminoMsg(object: _149.ConsensusParamsAminoMsg): _149.ConsensusParams;
            fromProtoMsg(message: _149.ConsensusParamsProtoMsg): _149.ConsensusParams;
            toProto(message: _149.ConsensusParams): Uint8Array;
            toProtoMsg(message: _149.ConsensusParams): _149.ConsensusParamsProtoMsg;
        };
        BlockParams: {
            encode(message: _149.BlockParams, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number | undefined): _149.BlockParams;
            fromJSON(object: any): _149.BlockParams;
            toJSON(message: _149.BlockParams): unknown;
            fromPartial(object: Partial<_149.BlockParams>): _149.BlockParams;
            fromAmino(object: _149.BlockParamsAmino): _149.BlockParams;
            toAmino(message: _149.BlockParams): _149.BlockParamsAmino;
            fromAminoMsg(object: _149.BlockParamsAminoMsg): _149.BlockParams;
            fromProtoMsg(message: _149.BlockParamsProtoMsg): _149.BlockParams;
            toProto(message: _149.BlockParams): Uint8Array;
            toProtoMsg(message: _149.BlockParams): _149.BlockParamsProtoMsg;
        };
        EvidenceParams: {
            encode(message: _149.EvidenceParams, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number | undefined): _149.EvidenceParams;
            fromJSON(object: any): _149.EvidenceParams;
            toJSON(message: _149.EvidenceParams): unknown;
            fromPartial(object: Partial<_149.EvidenceParams>): _149.EvidenceParams;
            fromAmino(object: _149.EvidenceParamsAmino): _149.EvidenceParams;
            toAmino(message: _149.EvidenceParams): _149.EvidenceParamsAmino;
            fromAminoMsg(object: _149.EvidenceParamsAminoMsg): _149.EvidenceParams;
            fromProtoMsg(message: _149.EvidenceParamsProtoMsg): _149.EvidenceParams;
            toProto(message: _149.EvidenceParams): Uint8Array;
            toProtoMsg(message: _149.EvidenceParams): _149.EvidenceParamsProtoMsg;
        };
        ValidatorParams: {
            encode(message: _149.ValidatorParams, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number | undefined): _149.ValidatorParams;
            fromJSON(object: any): _149.ValidatorParams;
            toJSON(message: _149.ValidatorParams): unknown;
            fromPartial(object: Partial<_149.ValidatorParams>): _149.ValidatorParams;
            fromAmino(object: _149.ValidatorParamsAmino): _149.ValidatorParams;
            toAmino(message: _149.ValidatorParams): _149.ValidatorParamsAmino;
            fromAminoMsg(object: _149.ValidatorParamsAminoMsg): _149.ValidatorParams;
            fromProtoMsg(message: _149.ValidatorParamsProtoMsg): _149.ValidatorParams;
            toProto(message: _149.ValidatorParams): Uint8Array;
            toProtoMsg(message: _149.ValidatorParams): _149.ValidatorParamsProtoMsg;
        };
        VersionParams: {
            encode(message: _149.VersionParams, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number | undefined): _149.VersionParams;
            fromJSON(object: any): _149.VersionParams;
            toJSON(message: _149.VersionParams): unknown;
            fromPartial(object: Partial<_149.VersionParams>): _149.VersionParams;
            fromAmino(object: _149.VersionParamsAmino): _149.VersionParams;
            toAmino(message: _149.VersionParams): _149.VersionParamsAmino;
            fromAminoMsg(object: _149.VersionParamsAminoMsg): _149.VersionParams;
            fromProtoMsg(message: _149.VersionParamsProtoMsg): _149.VersionParams;
            toProto(message: _149.VersionParams): Uint8Array;
            toProtoMsg(message: _149.VersionParams): _149.VersionParamsProtoMsg;
        };
        HashedParams: {
            encode(message: _149.HashedParams, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number | undefined): _149.HashedParams;
            fromJSON(object: any): _149.HashedParams;
            toJSON(message: _149.HashedParams): unknown;
            fromPartial(object: Partial<_149.HashedParams>): _149.HashedParams;
            fromAmino(object: _149.HashedParamsAmino): _149.HashedParams;
            toAmino(message: _149.HashedParams): _149.HashedParamsAmino;
            fromAminoMsg(object: _149.HashedParamsAminoMsg): _149.HashedParams;
            fromProtoMsg(message: _149.HashedParamsProtoMsg): _149.HashedParams;
            toProto(message: _149.HashedParams): Uint8Array;
            toProtoMsg(message: _149.HashedParams): _149.HashedParamsProtoMsg;
        };
        Evidence: {
            encode(message: _148.Evidence, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number | undefined): _148.Evidence;
            fromJSON(object: any): _148.Evidence;
            toJSON(message: _148.Evidence): unknown;
            fromPartial(object: Partial<_148.Evidence>): _148.Evidence;
            fromAmino(object: _148.EvidenceAmino): _148.Evidence;
            toAmino(message: _148.Evidence): _148.EvidenceAmino;
            fromAminoMsg(object: _148.EvidenceAminoMsg): _148.Evidence;
            fromProtoMsg(message: _148.EvidenceProtoMsg): _148.Evidence;
            toProto(message: _148.Evidence): Uint8Array;
            toProtoMsg(message: _148.Evidence): _148.EvidenceProtoMsg;
        };
        DuplicateVoteEvidence: {
            encode(message: _148.DuplicateVoteEvidence, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number | undefined): _148.DuplicateVoteEvidence;
            fromJSON(object: any): _148.DuplicateVoteEvidence;
            toJSON(message: _148.DuplicateVoteEvidence): unknown;
            fromPartial(object: Partial<_148.DuplicateVoteEvidence>): _148.DuplicateVoteEvidence;
            fromAmino(object: _148.DuplicateVoteEvidenceAmino): _148.DuplicateVoteEvidence;
            toAmino(message: _148.DuplicateVoteEvidence): _148.DuplicateVoteEvidenceAmino;
            fromAminoMsg(object: _148.DuplicateVoteEvidenceAminoMsg): _148.DuplicateVoteEvidence;
            fromProtoMsg(message: _148.DuplicateVoteEvidenceProtoMsg): _148.DuplicateVoteEvidence;
            toProto(message: _148.DuplicateVoteEvidence): Uint8Array;
            toProtoMsg(message: _148.DuplicateVoteEvidence): _148.DuplicateVoteEvidenceProtoMsg;
        };
        LightClientAttackEvidence: {
            encode(message: _148.LightClientAttackEvidence, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number | undefined): _148.LightClientAttackEvidence;
            fromJSON(object: any): _148.LightClientAttackEvidence;
            toJSON(message: _148.LightClientAttackEvidence): unknown;
            fromPartial(object: Partial<_148.LightClientAttackEvidence>): _148.LightClientAttackEvidence;
            fromAmino(object: _148.LightClientAttackEvidenceAmino): _148.LightClientAttackEvidence;
            toAmino(message: _148.LightClientAttackEvidence): _148.LightClientAttackEvidenceAmino;
            fromAminoMsg(object: _148.LightClientAttackEvidenceAminoMsg): _148.LightClientAttackEvidence;
            fromProtoMsg(message: _148.LightClientAttackEvidenceProtoMsg): _148.LightClientAttackEvidence;
            toProto(message: _148.LightClientAttackEvidence): Uint8Array;
            toProtoMsg(message: _148.LightClientAttackEvidence): _148.LightClientAttackEvidenceProtoMsg;
        };
        EvidenceList: {
            encode(message: _148.EvidenceList, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number | undefined): _148.EvidenceList;
            fromJSON(object: any): _148.EvidenceList;
            toJSON(message: _148.EvidenceList): unknown;
            fromPartial(object: Partial<_148.EvidenceList>): _148.EvidenceList;
            fromAmino(object: _148.EvidenceListAmino): _148.EvidenceList;
            toAmino(message: _148.EvidenceList): _148.EvidenceListAmino;
            fromAminoMsg(object: _148.EvidenceListAminoMsg): _148.EvidenceList;
            fromProtoMsg(message: _148.EvidenceListProtoMsg): _148.EvidenceList;
            toProto(message: _148.EvidenceList): Uint8Array;
            toProtoMsg(message: _148.EvidenceList): _148.EvidenceListProtoMsg;
        };
        Block: {
            encode(message: _147.Block, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number | undefined): _147.Block;
            fromJSON(object: any): _147.Block;
            toJSON(message: _147.Block): unknown;
            fromPartial(object: Partial<_147.Block>): _147.Block;
            fromAmino(object: _147.BlockAmino): _147.Block;
            toAmino(message: _147.Block): _147.BlockAmino;
            fromAminoMsg(object: _147.BlockAminoMsg): _147.Block;
            fromProtoMsg(message: _147.BlockProtoMsg): _147.Block;
            toProto(message: _147.Block): Uint8Array;
            toProtoMsg(message: _147.Block): _147.BlockProtoMsg;
        };
    };
    const version: {
        App: {
            encode(message: _152.App, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number | undefined): _152.App;
            fromJSON(object: any): _152.App;
            toJSON(message: _152.App): unknown;
            fromPartial(object: Partial<_152.App>): _152.App;
            fromAmino(object: _152.AppAmino): _152.App;
            toAmino(message: _152.App): _152.AppAmino;
            fromAminoMsg(object: _152.AppAminoMsg): _152.App;
            fromProtoMsg(message: _152.AppProtoMsg): _152.App;
            toProto(message: _152.App): Uint8Array;
            toProtoMsg(message: _152.App): _152.AppProtoMsg;
        };
        Consensus: {
            encode(message: _152.Consensus, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number | undefined): _152.Consensus;
            fromJSON(object: any): _152.Consensus;
            toJSON(message: _152.Consensus): unknown;
            fromPartial(object: Partial<_152.Consensus>): _152.Consensus;
            fromAmino(object: _152.ConsensusAmino): _152.Consensus;
            toAmino(message: _152.Consensus): _152.ConsensusAmino;
            fromAminoMsg(object: _152.ConsensusAminoMsg): _152.Consensus;
            fromProtoMsg(message: _152.ConsensusProtoMsg): _152.Consensus;
            toProto(message: _152.Consensus): Uint8Array;
            toProtoMsg(message: _152.Consensus): _152.ConsensusProtoMsg;
        };
    };
}
