import * as _141 from "./abci/types";
import * as _142 from "./crypto/keys";
import * as _143 from "./crypto/proof";
import * as _144 from "./libs/bits/types";
import * as _145 from "./p2p/types";
import * as _146 from "./types/block";
import * as _147 from "./types/evidence";
import * as _148 from "./types/params";
import * as _149 from "./types/types";
import * as _150 from "./types/validator";
import * as _151 from "./version/types";
export declare namespace tendermint {
    const abci: {
        checkTxTypeFromJSON(object: any): _141.CheckTxType;
        checkTxTypeToJSON(object: _141.CheckTxType): string;
        responseOfferSnapshot_ResultFromJSON(object: any): _141.ResponseOfferSnapshot_Result;
        responseOfferSnapshot_ResultToJSON(object: _141.ResponseOfferSnapshot_Result): string;
        responseApplySnapshotChunk_ResultFromJSON(object: any): _141.ResponseApplySnapshotChunk_Result;
        responseApplySnapshotChunk_ResultToJSON(object: _141.ResponseApplySnapshotChunk_Result): string;
        responseProcessProposal_ProposalStatusFromJSON(object: any): _141.ResponseProcessProposal_ProposalStatus;
        responseProcessProposal_ProposalStatusToJSON(object: _141.ResponseProcessProposal_ProposalStatus): string;
        misbehaviorTypeFromJSON(object: any): _141.MisbehaviorType;
        misbehaviorTypeToJSON(object: _141.MisbehaviorType): string;
        CheckTxType: typeof _141.CheckTxType;
        CheckTxTypeSDKType: typeof _141.CheckTxType;
        CheckTxTypeAmino: typeof _141.CheckTxType;
        ResponseOfferSnapshot_Result: typeof _141.ResponseOfferSnapshot_Result;
        ResponseOfferSnapshot_ResultSDKType: typeof _141.ResponseOfferSnapshot_Result;
        ResponseOfferSnapshot_ResultAmino: typeof _141.ResponseOfferSnapshot_Result;
        ResponseApplySnapshotChunk_Result: typeof _141.ResponseApplySnapshotChunk_Result;
        ResponseApplySnapshotChunk_ResultSDKType: typeof _141.ResponseApplySnapshotChunk_Result;
        ResponseApplySnapshotChunk_ResultAmino: typeof _141.ResponseApplySnapshotChunk_Result;
        ResponseProcessProposal_ProposalStatus: typeof _141.ResponseProcessProposal_ProposalStatus;
        ResponseProcessProposal_ProposalStatusSDKType: typeof _141.ResponseProcessProposal_ProposalStatus;
        ResponseProcessProposal_ProposalStatusAmino: typeof _141.ResponseProcessProposal_ProposalStatus;
        MisbehaviorType: typeof _141.MisbehaviorType;
        MisbehaviorTypeSDKType: typeof _141.MisbehaviorType;
        MisbehaviorTypeAmino: typeof _141.MisbehaviorType;
        Request: {
            typeUrl: string;
            encode(message: _141.Request, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number | undefined): _141.Request;
            fromJSON(object: any): _141.Request;
            toJSON(message: _141.Request): unknown;
            fromPartial(object: Partial<_141.Request>): _141.Request;
            fromAmino(object: _141.RequestAmino): _141.Request;
            toAmino(message: _141.Request): _141.RequestAmino;
            fromAminoMsg(object: _141.RequestAminoMsg): _141.Request;
            fromProtoMsg(message: _141.RequestProtoMsg): _141.Request;
            toProto(message: _141.Request): Uint8Array;
            toProtoMsg(message: _141.Request): _141.RequestProtoMsg;
        };
        RequestEcho: {
            typeUrl: string;
            encode(message: _141.RequestEcho, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number | undefined): _141.RequestEcho;
            fromJSON(object: any): _141.RequestEcho;
            toJSON(message: _141.RequestEcho): unknown;
            fromPartial(object: Partial<_141.RequestEcho>): _141.RequestEcho;
            fromAmino(object: _141.RequestEchoAmino): _141.RequestEcho;
            toAmino(message: _141.RequestEcho): _141.RequestEchoAmino;
            fromAminoMsg(object: _141.RequestEchoAminoMsg): _141.RequestEcho;
            fromProtoMsg(message: _141.RequestEchoProtoMsg): _141.RequestEcho;
            toProto(message: _141.RequestEcho): Uint8Array;
            toProtoMsg(message: _141.RequestEcho): _141.RequestEchoProtoMsg;
        };
        RequestFlush: {
            typeUrl: string;
            encode(_: _141.RequestFlush, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number | undefined): _141.RequestFlush;
            fromJSON(_: any): _141.RequestFlush;
            toJSON(_: _141.RequestFlush): unknown;
            fromPartial(_: Partial<_141.RequestFlush>): _141.RequestFlush;
            fromAmino(_: _141.RequestFlushAmino): _141.RequestFlush;
            toAmino(_: _141.RequestFlush): _141.RequestFlushAmino;
            fromAminoMsg(object: _141.RequestFlushAminoMsg): _141.RequestFlush;
            fromProtoMsg(message: _141.RequestFlushProtoMsg): _141.RequestFlush;
            toProto(message: _141.RequestFlush): Uint8Array;
            toProtoMsg(message: _141.RequestFlush): _141.RequestFlushProtoMsg;
        };
        RequestInfo: {
            typeUrl: string;
            encode(message: _141.RequestInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number | undefined): _141.RequestInfo;
            fromJSON(object: any): _141.RequestInfo;
            toJSON(message: _141.RequestInfo): unknown;
            fromPartial(object: Partial<_141.RequestInfo>): _141.RequestInfo;
            fromAmino(object: _141.RequestInfoAmino): _141.RequestInfo;
            toAmino(message: _141.RequestInfo): _141.RequestInfoAmino;
            fromAminoMsg(object: _141.RequestInfoAminoMsg): _141.RequestInfo;
            fromProtoMsg(message: _141.RequestInfoProtoMsg): _141.RequestInfo;
            toProto(message: _141.RequestInfo): Uint8Array;
            toProtoMsg(message: _141.RequestInfo): _141.RequestInfoProtoMsg;
        };
        RequestInitChain: {
            typeUrl: string;
            encode(message: _141.RequestInitChain, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number | undefined): _141.RequestInitChain;
            fromJSON(object: any): _141.RequestInitChain;
            toJSON(message: _141.RequestInitChain): unknown;
            fromPartial(object: Partial<_141.RequestInitChain>): _141.RequestInitChain;
            fromAmino(object: _141.RequestInitChainAmino): _141.RequestInitChain;
            toAmino(message: _141.RequestInitChain): _141.RequestInitChainAmino;
            fromAminoMsg(object: _141.RequestInitChainAminoMsg): _141.RequestInitChain;
            fromProtoMsg(message: _141.RequestInitChainProtoMsg): _141.RequestInitChain;
            toProto(message: _141.RequestInitChain): Uint8Array;
            toProtoMsg(message: _141.RequestInitChain): _141.RequestInitChainProtoMsg;
        };
        RequestQuery: {
            typeUrl: string;
            encode(message: _141.RequestQuery, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number | undefined): _141.RequestQuery;
            fromJSON(object: any): _141.RequestQuery;
            toJSON(message: _141.RequestQuery): unknown;
            fromPartial(object: Partial<_141.RequestQuery>): _141.RequestQuery;
            fromAmino(object: _141.RequestQueryAmino): _141.RequestQuery;
            toAmino(message: _141.RequestQuery): _141.RequestQueryAmino;
            fromAminoMsg(object: _141.RequestQueryAminoMsg): _141.RequestQuery;
            fromProtoMsg(message: _141.RequestQueryProtoMsg): _141.RequestQuery;
            toProto(message: _141.RequestQuery): Uint8Array;
            toProtoMsg(message: _141.RequestQuery): _141.RequestQueryProtoMsg;
        };
        RequestBeginBlock: {
            typeUrl: string;
            encode(message: _141.RequestBeginBlock, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number | undefined): _141.RequestBeginBlock;
            fromJSON(object: any): _141.RequestBeginBlock;
            toJSON(message: _141.RequestBeginBlock): unknown;
            fromPartial(object: Partial<_141.RequestBeginBlock>): _141.RequestBeginBlock;
            fromAmino(object: _141.RequestBeginBlockAmino): _141.RequestBeginBlock;
            toAmino(message: _141.RequestBeginBlock): _141.RequestBeginBlockAmino;
            fromAminoMsg(object: _141.RequestBeginBlockAminoMsg): _141.RequestBeginBlock;
            fromProtoMsg(message: _141.RequestBeginBlockProtoMsg): _141.RequestBeginBlock;
            toProto(message: _141.RequestBeginBlock): Uint8Array;
            toProtoMsg(message: _141.RequestBeginBlock): _141.RequestBeginBlockProtoMsg;
        };
        RequestCheckTx: {
            typeUrl: string;
            encode(message: _141.RequestCheckTx, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number | undefined): _141.RequestCheckTx;
            fromJSON(object: any): _141.RequestCheckTx;
            toJSON(message: _141.RequestCheckTx): unknown;
            fromPartial(object: Partial<_141.RequestCheckTx>): _141.RequestCheckTx;
            fromAmino(object: _141.RequestCheckTxAmino): _141.RequestCheckTx;
            toAmino(message: _141.RequestCheckTx): _141.RequestCheckTxAmino;
            fromAminoMsg(object: _141.RequestCheckTxAminoMsg): _141.RequestCheckTx;
            fromProtoMsg(message: _141.RequestCheckTxProtoMsg): _141.RequestCheckTx;
            toProto(message: _141.RequestCheckTx): Uint8Array;
            toProtoMsg(message: _141.RequestCheckTx): _141.RequestCheckTxProtoMsg;
        };
        RequestDeliverTx: {
            typeUrl: string;
            encode(message: _141.RequestDeliverTx, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number | undefined): _141.RequestDeliverTx;
            fromJSON(object: any): _141.RequestDeliverTx;
            toJSON(message: _141.RequestDeliverTx): unknown;
            fromPartial(object: Partial<_141.RequestDeliverTx>): _141.RequestDeliverTx;
            fromAmino(object: _141.RequestDeliverTxAmino): _141.RequestDeliverTx;
            toAmino(message: _141.RequestDeliverTx): _141.RequestDeliverTxAmino;
            fromAminoMsg(object: _141.RequestDeliverTxAminoMsg): _141.RequestDeliverTx;
            fromProtoMsg(message: _141.RequestDeliverTxProtoMsg): _141.RequestDeliverTx;
            toProto(message: _141.RequestDeliverTx): Uint8Array;
            toProtoMsg(message: _141.RequestDeliverTx): _141.RequestDeliverTxProtoMsg;
        };
        RequestEndBlock: {
            typeUrl: string;
            encode(message: _141.RequestEndBlock, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number | undefined): _141.RequestEndBlock;
            fromJSON(object: any): _141.RequestEndBlock;
            toJSON(message: _141.RequestEndBlock): unknown;
            fromPartial(object: Partial<_141.RequestEndBlock>): _141.RequestEndBlock;
            fromAmino(object: _141.RequestEndBlockAmino): _141.RequestEndBlock;
            toAmino(message: _141.RequestEndBlock): _141.RequestEndBlockAmino;
            fromAminoMsg(object: _141.RequestEndBlockAminoMsg): _141.RequestEndBlock;
            fromProtoMsg(message: _141.RequestEndBlockProtoMsg): _141.RequestEndBlock;
            toProto(message: _141.RequestEndBlock): Uint8Array;
            toProtoMsg(message: _141.RequestEndBlock): _141.RequestEndBlockProtoMsg;
        };
        RequestCommit: {
            typeUrl: string;
            encode(_: _141.RequestCommit, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number | undefined): _141.RequestCommit;
            fromJSON(_: any): _141.RequestCommit;
            toJSON(_: _141.RequestCommit): unknown;
            fromPartial(_: Partial<_141.RequestCommit>): _141.RequestCommit;
            fromAmino(_: _141.RequestCommitAmino): _141.RequestCommit;
            toAmino(_: _141.RequestCommit): _141.RequestCommitAmino;
            fromAminoMsg(object: _141.RequestCommitAminoMsg): _141.RequestCommit;
            fromProtoMsg(message: _141.RequestCommitProtoMsg): _141.RequestCommit;
            toProto(message: _141.RequestCommit): Uint8Array;
            toProtoMsg(message: _141.RequestCommit): _141.RequestCommitProtoMsg;
        };
        RequestListSnapshots: {
            typeUrl: string;
            encode(_: _141.RequestListSnapshots, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number | undefined): _141.RequestListSnapshots;
            fromJSON(_: any): _141.RequestListSnapshots;
            toJSON(_: _141.RequestListSnapshots): unknown;
            fromPartial(_: Partial<_141.RequestListSnapshots>): _141.RequestListSnapshots;
            fromAmino(_: _141.RequestListSnapshotsAmino): _141.RequestListSnapshots;
            toAmino(_: _141.RequestListSnapshots): _141.RequestListSnapshotsAmino;
            fromAminoMsg(object: _141.RequestListSnapshotsAminoMsg): _141.RequestListSnapshots;
            fromProtoMsg(message: _141.RequestListSnapshotsProtoMsg): _141.RequestListSnapshots;
            toProto(message: _141.RequestListSnapshots): Uint8Array;
            toProtoMsg(message: _141.RequestListSnapshots): _141.RequestListSnapshotsProtoMsg;
        };
        RequestOfferSnapshot: {
            typeUrl: string;
            encode(message: _141.RequestOfferSnapshot, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number | undefined): _141.RequestOfferSnapshot;
            fromJSON(object: any): _141.RequestOfferSnapshot;
            toJSON(message: _141.RequestOfferSnapshot): unknown;
            fromPartial(object: Partial<_141.RequestOfferSnapshot>): _141.RequestOfferSnapshot;
            fromAmino(object: _141.RequestOfferSnapshotAmino): _141.RequestOfferSnapshot;
            toAmino(message: _141.RequestOfferSnapshot): _141.RequestOfferSnapshotAmino;
            fromAminoMsg(object: _141.RequestOfferSnapshotAminoMsg): _141.RequestOfferSnapshot;
            fromProtoMsg(message: _141.RequestOfferSnapshotProtoMsg): _141.RequestOfferSnapshot;
            toProto(message: _141.RequestOfferSnapshot): Uint8Array;
            toProtoMsg(message: _141.RequestOfferSnapshot): _141.RequestOfferSnapshotProtoMsg;
        };
        RequestLoadSnapshotChunk: {
            typeUrl: string;
            encode(message: _141.RequestLoadSnapshotChunk, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number | undefined): _141.RequestLoadSnapshotChunk;
            fromJSON(object: any): _141.RequestLoadSnapshotChunk;
            toJSON(message: _141.RequestLoadSnapshotChunk): unknown;
            fromPartial(object: Partial<_141.RequestLoadSnapshotChunk>): _141.RequestLoadSnapshotChunk;
            fromAmino(object: _141.RequestLoadSnapshotChunkAmino): _141.RequestLoadSnapshotChunk;
            toAmino(message: _141.RequestLoadSnapshotChunk): _141.RequestLoadSnapshotChunkAmino;
            fromAminoMsg(object: _141.RequestLoadSnapshotChunkAminoMsg): _141.RequestLoadSnapshotChunk;
            fromProtoMsg(message: _141.RequestLoadSnapshotChunkProtoMsg): _141.RequestLoadSnapshotChunk;
            toProto(message: _141.RequestLoadSnapshotChunk): Uint8Array;
            toProtoMsg(message: _141.RequestLoadSnapshotChunk): _141.RequestLoadSnapshotChunkProtoMsg;
        };
        RequestApplySnapshotChunk: {
            typeUrl: string;
            encode(message: _141.RequestApplySnapshotChunk, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number | undefined): _141.RequestApplySnapshotChunk;
            fromJSON(object: any): _141.RequestApplySnapshotChunk;
            toJSON(message: _141.RequestApplySnapshotChunk): unknown;
            fromPartial(object: Partial<_141.RequestApplySnapshotChunk>): _141.RequestApplySnapshotChunk;
            fromAmino(object: _141.RequestApplySnapshotChunkAmino): _141.RequestApplySnapshotChunk;
            toAmino(message: _141.RequestApplySnapshotChunk): _141.RequestApplySnapshotChunkAmino;
            fromAminoMsg(object: _141.RequestApplySnapshotChunkAminoMsg): _141.RequestApplySnapshotChunk;
            fromProtoMsg(message: _141.RequestApplySnapshotChunkProtoMsg): _141.RequestApplySnapshotChunk;
            toProto(message: _141.RequestApplySnapshotChunk): Uint8Array;
            toProtoMsg(message: _141.RequestApplySnapshotChunk): _141.RequestApplySnapshotChunkProtoMsg;
        };
        RequestPrepareProposal: {
            typeUrl: string;
            encode(message: _141.RequestPrepareProposal, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number | undefined): _141.RequestPrepareProposal;
            fromJSON(object: any): _141.RequestPrepareProposal;
            toJSON(message: _141.RequestPrepareProposal): unknown;
            fromPartial(object: Partial<_141.RequestPrepareProposal>): _141.RequestPrepareProposal;
            fromAmino(object: _141.RequestPrepareProposalAmino): _141.RequestPrepareProposal;
            toAmino(message: _141.RequestPrepareProposal): _141.RequestPrepareProposalAmino;
            fromAminoMsg(object: _141.RequestPrepareProposalAminoMsg): _141.RequestPrepareProposal;
            fromProtoMsg(message: _141.RequestPrepareProposalProtoMsg): _141.RequestPrepareProposal;
            toProto(message: _141.RequestPrepareProposal): Uint8Array;
            toProtoMsg(message: _141.RequestPrepareProposal): _141.RequestPrepareProposalProtoMsg;
        };
        RequestProcessProposal: {
            typeUrl: string;
            encode(message: _141.RequestProcessProposal, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number | undefined): _141.RequestProcessProposal;
            fromJSON(object: any): _141.RequestProcessProposal;
            toJSON(message: _141.RequestProcessProposal): unknown;
            fromPartial(object: Partial<_141.RequestProcessProposal>): _141.RequestProcessProposal;
            fromAmino(object: _141.RequestProcessProposalAmino): _141.RequestProcessProposal;
            toAmino(message: _141.RequestProcessProposal): _141.RequestProcessProposalAmino;
            fromAminoMsg(object: _141.RequestProcessProposalAminoMsg): _141.RequestProcessProposal;
            fromProtoMsg(message: _141.RequestProcessProposalProtoMsg): _141.RequestProcessProposal;
            toProto(message: _141.RequestProcessProposal): Uint8Array;
            toProtoMsg(message: _141.RequestProcessProposal): _141.RequestProcessProposalProtoMsg;
        };
        Response: {
            typeUrl: string;
            encode(message: _141.Response, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number | undefined): _141.Response;
            fromJSON(object: any): _141.Response;
            toJSON(message: _141.Response): unknown;
            fromPartial(object: Partial<_141.Response>): _141.Response;
            fromAmino(object: _141.ResponseAmino): _141.Response;
            toAmino(message: _141.Response): _141.ResponseAmino;
            fromAminoMsg(object: _141.ResponseAminoMsg): _141.Response;
            fromProtoMsg(message: _141.ResponseProtoMsg): _141.Response;
            toProto(message: _141.Response): Uint8Array;
            toProtoMsg(message: _141.Response): _141.ResponseProtoMsg;
        };
        ResponseException: {
            typeUrl: string;
            encode(message: _141.ResponseException, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number | undefined): _141.ResponseException;
            fromJSON(object: any): _141.ResponseException;
            toJSON(message: _141.ResponseException): unknown;
            fromPartial(object: Partial<_141.ResponseException>): _141.ResponseException;
            fromAmino(object: _141.ResponseExceptionAmino): _141.ResponseException;
            toAmino(message: _141.ResponseException): _141.ResponseExceptionAmino;
            fromAminoMsg(object: _141.ResponseExceptionAminoMsg): _141.ResponseException;
            fromProtoMsg(message: _141.ResponseExceptionProtoMsg): _141.ResponseException;
            toProto(message: _141.ResponseException): Uint8Array;
            toProtoMsg(message: _141.ResponseException): _141.ResponseExceptionProtoMsg;
        };
        ResponseEcho: {
            typeUrl: string;
            encode(message: _141.ResponseEcho, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number | undefined): _141.ResponseEcho;
            fromJSON(object: any): _141.ResponseEcho;
            toJSON(message: _141.ResponseEcho): unknown;
            fromPartial(object: Partial<_141.ResponseEcho>): _141.ResponseEcho;
            fromAmino(object: _141.ResponseEchoAmino): _141.ResponseEcho;
            toAmino(message: _141.ResponseEcho): _141.ResponseEchoAmino;
            fromAminoMsg(object: _141.ResponseEchoAminoMsg): _141.ResponseEcho;
            fromProtoMsg(message: _141.ResponseEchoProtoMsg): _141.ResponseEcho;
            toProto(message: _141.ResponseEcho): Uint8Array;
            toProtoMsg(message: _141.ResponseEcho): _141.ResponseEchoProtoMsg;
        };
        ResponseFlush: {
            typeUrl: string;
            encode(_: _141.ResponseFlush, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number | undefined): _141.ResponseFlush;
            fromJSON(_: any): _141.ResponseFlush;
            toJSON(_: _141.ResponseFlush): unknown;
            fromPartial(_: Partial<_141.ResponseFlush>): _141.ResponseFlush;
            fromAmino(_: _141.ResponseFlushAmino): _141.ResponseFlush;
            toAmino(_: _141.ResponseFlush): _141.ResponseFlushAmino;
            fromAminoMsg(object: _141.ResponseFlushAminoMsg): _141.ResponseFlush;
            fromProtoMsg(message: _141.ResponseFlushProtoMsg): _141.ResponseFlush;
            toProto(message: _141.ResponseFlush): Uint8Array;
            toProtoMsg(message: _141.ResponseFlush): _141.ResponseFlushProtoMsg;
        };
        ResponseInfo: {
            typeUrl: string;
            encode(message: _141.ResponseInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number | undefined): _141.ResponseInfo;
            fromJSON(object: any): _141.ResponseInfo;
            toJSON(message: _141.ResponseInfo): unknown;
            fromPartial(object: Partial<_141.ResponseInfo>): _141.ResponseInfo;
            fromAmino(object: _141.ResponseInfoAmino): _141.ResponseInfo;
            toAmino(message: _141.ResponseInfo): _141.ResponseInfoAmino;
            fromAminoMsg(object: _141.ResponseInfoAminoMsg): _141.ResponseInfo;
            fromProtoMsg(message: _141.ResponseInfoProtoMsg): _141.ResponseInfo;
            toProto(message: _141.ResponseInfo): Uint8Array;
            toProtoMsg(message: _141.ResponseInfo): _141.ResponseInfoProtoMsg;
        };
        ResponseInitChain: {
            typeUrl: string;
            encode(message: _141.ResponseInitChain, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number | undefined): _141.ResponseInitChain;
            fromJSON(object: any): _141.ResponseInitChain;
            toJSON(message: _141.ResponseInitChain): unknown;
            fromPartial(object: Partial<_141.ResponseInitChain>): _141.ResponseInitChain;
            fromAmino(object: _141.ResponseInitChainAmino): _141.ResponseInitChain;
            toAmino(message: _141.ResponseInitChain): _141.ResponseInitChainAmino;
            fromAminoMsg(object: _141.ResponseInitChainAminoMsg): _141.ResponseInitChain;
            fromProtoMsg(message: _141.ResponseInitChainProtoMsg): _141.ResponseInitChain;
            toProto(message: _141.ResponseInitChain): Uint8Array;
            toProtoMsg(message: _141.ResponseInitChain): _141.ResponseInitChainProtoMsg;
        };
        ResponseQuery: {
            typeUrl: string;
            encode(message: _141.ResponseQuery, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number | undefined): _141.ResponseQuery;
            fromJSON(object: any): _141.ResponseQuery;
            toJSON(message: _141.ResponseQuery): unknown;
            fromPartial(object: Partial<_141.ResponseQuery>): _141.ResponseQuery;
            fromAmino(object: _141.ResponseQueryAmino): _141.ResponseQuery;
            toAmino(message: _141.ResponseQuery): _141.ResponseQueryAmino;
            fromAminoMsg(object: _141.ResponseQueryAminoMsg): _141.ResponseQuery;
            fromProtoMsg(message: _141.ResponseQueryProtoMsg): _141.ResponseQuery;
            toProto(message: _141.ResponseQuery): Uint8Array;
            toProtoMsg(message: _141.ResponseQuery): _141.ResponseQueryProtoMsg;
        };
        ResponseBeginBlock: {
            typeUrl: string;
            encode(message: _141.ResponseBeginBlock, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number | undefined): _141.ResponseBeginBlock;
            fromJSON(object: any): _141.ResponseBeginBlock;
            toJSON(message: _141.ResponseBeginBlock): unknown;
            fromPartial(object: Partial<_141.ResponseBeginBlock>): _141.ResponseBeginBlock;
            fromAmino(object: _141.ResponseBeginBlockAmino): _141.ResponseBeginBlock;
            toAmino(message: _141.ResponseBeginBlock): _141.ResponseBeginBlockAmino;
            fromAminoMsg(object: _141.ResponseBeginBlockAminoMsg): _141.ResponseBeginBlock;
            fromProtoMsg(message: _141.ResponseBeginBlockProtoMsg): _141.ResponseBeginBlock;
            toProto(message: _141.ResponseBeginBlock): Uint8Array;
            toProtoMsg(message: _141.ResponseBeginBlock): _141.ResponseBeginBlockProtoMsg;
        };
        ResponseCheckTx: {
            typeUrl: string;
            encode(message: _141.ResponseCheckTx, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number | undefined): _141.ResponseCheckTx;
            fromJSON(object: any): _141.ResponseCheckTx;
            toJSON(message: _141.ResponseCheckTx): unknown;
            fromPartial(object: Partial<_141.ResponseCheckTx>): _141.ResponseCheckTx;
            fromAmino(object: _141.ResponseCheckTxAmino): _141.ResponseCheckTx;
            toAmino(message: _141.ResponseCheckTx): _141.ResponseCheckTxAmino;
            fromAminoMsg(object: _141.ResponseCheckTxAminoMsg): _141.ResponseCheckTx;
            fromProtoMsg(message: _141.ResponseCheckTxProtoMsg): _141.ResponseCheckTx;
            toProto(message: _141.ResponseCheckTx): Uint8Array;
            toProtoMsg(message: _141.ResponseCheckTx): _141.ResponseCheckTxProtoMsg;
        };
        ResponseDeliverTx: {
            typeUrl: string;
            encode(message: _141.ResponseDeliverTx, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number | undefined): _141.ResponseDeliverTx;
            fromJSON(object: any): _141.ResponseDeliverTx;
            toJSON(message: _141.ResponseDeliverTx): unknown;
            fromPartial(object: Partial<_141.ResponseDeliverTx>): _141.ResponseDeliverTx;
            fromAmino(object: _141.ResponseDeliverTxAmino): _141.ResponseDeliverTx;
            toAmino(message: _141.ResponseDeliverTx): _141.ResponseDeliverTxAmino;
            fromAminoMsg(object: _141.ResponseDeliverTxAminoMsg): _141.ResponseDeliverTx;
            fromProtoMsg(message: _141.ResponseDeliverTxProtoMsg): _141.ResponseDeliverTx;
            toProto(message: _141.ResponseDeliverTx): Uint8Array;
            toProtoMsg(message: _141.ResponseDeliverTx): _141.ResponseDeliverTxProtoMsg;
        };
        ResponseEndBlock: {
            typeUrl: string;
            encode(message: _141.ResponseEndBlock, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number | undefined): _141.ResponseEndBlock;
            fromJSON(object: any): _141.ResponseEndBlock;
            toJSON(message: _141.ResponseEndBlock): unknown;
            fromPartial(object: Partial<_141.ResponseEndBlock>): _141.ResponseEndBlock;
            fromAmino(object: _141.ResponseEndBlockAmino): _141.ResponseEndBlock;
            toAmino(message: _141.ResponseEndBlock): _141.ResponseEndBlockAmino;
            fromAminoMsg(object: _141.ResponseEndBlockAminoMsg): _141.ResponseEndBlock;
            fromProtoMsg(message: _141.ResponseEndBlockProtoMsg): _141.ResponseEndBlock;
            toProto(message: _141.ResponseEndBlock): Uint8Array;
            toProtoMsg(message: _141.ResponseEndBlock): _141.ResponseEndBlockProtoMsg;
        };
        ResponseCommit: {
            typeUrl: string;
            encode(message: _141.ResponseCommit, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number | undefined): _141.ResponseCommit;
            fromJSON(object: any): _141.ResponseCommit;
            toJSON(message: _141.ResponseCommit): unknown;
            fromPartial(object: Partial<_141.ResponseCommit>): _141.ResponseCommit;
            fromAmino(object: _141.ResponseCommitAmino): _141.ResponseCommit;
            toAmino(message: _141.ResponseCommit): _141.ResponseCommitAmino;
            fromAminoMsg(object: _141.ResponseCommitAminoMsg): _141.ResponseCommit;
            fromProtoMsg(message: _141.ResponseCommitProtoMsg): _141.ResponseCommit;
            toProto(message: _141.ResponseCommit): Uint8Array;
            toProtoMsg(message: _141.ResponseCommit): _141.ResponseCommitProtoMsg;
        };
        ResponseListSnapshots: {
            typeUrl: string;
            encode(message: _141.ResponseListSnapshots, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number | undefined): _141.ResponseListSnapshots;
            fromJSON(object: any): _141.ResponseListSnapshots;
            toJSON(message: _141.ResponseListSnapshots): unknown;
            fromPartial(object: Partial<_141.ResponseListSnapshots>): _141.ResponseListSnapshots;
            fromAmino(object: _141.ResponseListSnapshotsAmino): _141.ResponseListSnapshots;
            toAmino(message: _141.ResponseListSnapshots): _141.ResponseListSnapshotsAmino;
            fromAminoMsg(object: _141.ResponseListSnapshotsAminoMsg): _141.ResponseListSnapshots;
            fromProtoMsg(message: _141.ResponseListSnapshotsProtoMsg): _141.ResponseListSnapshots;
            toProto(message: _141.ResponseListSnapshots): Uint8Array;
            toProtoMsg(message: _141.ResponseListSnapshots): _141.ResponseListSnapshotsProtoMsg;
        };
        ResponseOfferSnapshot: {
            typeUrl: string;
            encode(message: _141.ResponseOfferSnapshot, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number | undefined): _141.ResponseOfferSnapshot;
            fromJSON(object: any): _141.ResponseOfferSnapshot;
            toJSON(message: _141.ResponseOfferSnapshot): unknown;
            fromPartial(object: Partial<_141.ResponseOfferSnapshot>): _141.ResponseOfferSnapshot;
            fromAmino(object: _141.ResponseOfferSnapshotAmino): _141.ResponseOfferSnapshot;
            toAmino(message: _141.ResponseOfferSnapshot): _141.ResponseOfferSnapshotAmino;
            fromAminoMsg(object: _141.ResponseOfferSnapshotAminoMsg): _141.ResponseOfferSnapshot;
            fromProtoMsg(message: _141.ResponseOfferSnapshotProtoMsg): _141.ResponseOfferSnapshot;
            toProto(message: _141.ResponseOfferSnapshot): Uint8Array;
            toProtoMsg(message: _141.ResponseOfferSnapshot): _141.ResponseOfferSnapshotProtoMsg;
        };
        ResponseLoadSnapshotChunk: {
            typeUrl: string;
            encode(message: _141.ResponseLoadSnapshotChunk, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number | undefined): _141.ResponseLoadSnapshotChunk;
            fromJSON(object: any): _141.ResponseLoadSnapshotChunk;
            toJSON(message: _141.ResponseLoadSnapshotChunk): unknown;
            fromPartial(object: Partial<_141.ResponseLoadSnapshotChunk>): _141.ResponseLoadSnapshotChunk;
            fromAmino(object: _141.ResponseLoadSnapshotChunkAmino): _141.ResponseLoadSnapshotChunk;
            toAmino(message: _141.ResponseLoadSnapshotChunk): _141.ResponseLoadSnapshotChunkAmino;
            fromAminoMsg(object: _141.ResponseLoadSnapshotChunkAminoMsg): _141.ResponseLoadSnapshotChunk;
            fromProtoMsg(message: _141.ResponseLoadSnapshotChunkProtoMsg): _141.ResponseLoadSnapshotChunk;
            toProto(message: _141.ResponseLoadSnapshotChunk): Uint8Array;
            toProtoMsg(message: _141.ResponseLoadSnapshotChunk): _141.ResponseLoadSnapshotChunkProtoMsg;
        };
        ResponseApplySnapshotChunk: {
            typeUrl: string;
            encode(message: _141.ResponseApplySnapshotChunk, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number | undefined): _141.ResponseApplySnapshotChunk;
            fromJSON(object: any): _141.ResponseApplySnapshotChunk;
            toJSON(message: _141.ResponseApplySnapshotChunk): unknown;
            fromPartial(object: Partial<_141.ResponseApplySnapshotChunk>): _141.ResponseApplySnapshotChunk;
            fromAmino(object: _141.ResponseApplySnapshotChunkAmino): _141.ResponseApplySnapshotChunk;
            toAmino(message: _141.ResponseApplySnapshotChunk): _141.ResponseApplySnapshotChunkAmino;
            fromAminoMsg(object: _141.ResponseApplySnapshotChunkAminoMsg): _141.ResponseApplySnapshotChunk;
            fromProtoMsg(message: _141.ResponseApplySnapshotChunkProtoMsg): _141.ResponseApplySnapshotChunk;
            toProto(message: _141.ResponseApplySnapshotChunk): Uint8Array;
            toProtoMsg(message: _141.ResponseApplySnapshotChunk): _141.ResponseApplySnapshotChunkProtoMsg;
        };
        ResponsePrepareProposal: {
            typeUrl: string;
            encode(message: _141.ResponsePrepareProposal, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number | undefined): _141.ResponsePrepareProposal;
            fromJSON(object: any): _141.ResponsePrepareProposal;
            toJSON(message: _141.ResponsePrepareProposal): unknown;
            fromPartial(object: Partial<_141.ResponsePrepareProposal>): _141.ResponsePrepareProposal;
            fromAmino(object: _141.ResponsePrepareProposalAmino): _141.ResponsePrepareProposal;
            toAmino(message: _141.ResponsePrepareProposal): _141.ResponsePrepareProposalAmino;
            fromAminoMsg(object: _141.ResponsePrepareProposalAminoMsg): _141.ResponsePrepareProposal;
            fromProtoMsg(message: _141.ResponsePrepareProposalProtoMsg): _141.ResponsePrepareProposal;
            toProto(message: _141.ResponsePrepareProposal): Uint8Array;
            toProtoMsg(message: _141.ResponsePrepareProposal): _141.ResponsePrepareProposalProtoMsg;
        };
        ResponseProcessProposal: {
            typeUrl: string;
            encode(message: _141.ResponseProcessProposal, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number | undefined): _141.ResponseProcessProposal;
            fromJSON(object: any): _141.ResponseProcessProposal;
            toJSON(message: _141.ResponseProcessProposal): unknown;
            fromPartial(object: Partial<_141.ResponseProcessProposal>): _141.ResponseProcessProposal;
            fromAmino(object: _141.ResponseProcessProposalAmino): _141.ResponseProcessProposal;
            toAmino(message: _141.ResponseProcessProposal): _141.ResponseProcessProposalAmino;
            fromAminoMsg(object: _141.ResponseProcessProposalAminoMsg): _141.ResponseProcessProposal;
            fromProtoMsg(message: _141.ResponseProcessProposalProtoMsg): _141.ResponseProcessProposal;
            toProto(message: _141.ResponseProcessProposal): Uint8Array;
            toProtoMsg(message: _141.ResponseProcessProposal): _141.ResponseProcessProposalProtoMsg;
        };
        CommitInfo: {
            typeUrl: string;
            encode(message: _141.CommitInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number | undefined): _141.CommitInfo;
            fromJSON(object: any): _141.CommitInfo;
            toJSON(message: _141.CommitInfo): unknown;
            fromPartial(object: Partial<_141.CommitInfo>): _141.CommitInfo;
            fromAmino(object: _141.CommitInfoAmino): _141.CommitInfo;
            toAmino(message: _141.CommitInfo): _141.CommitInfoAmino;
            fromAminoMsg(object: _141.CommitInfoAminoMsg): _141.CommitInfo;
            fromProtoMsg(message: _141.CommitInfoProtoMsg): _141.CommitInfo;
            toProto(message: _141.CommitInfo): Uint8Array;
            toProtoMsg(message: _141.CommitInfo): _141.CommitInfoProtoMsg;
        };
        ExtendedCommitInfo: {
            typeUrl: string;
            encode(message: _141.ExtendedCommitInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number | undefined): _141.ExtendedCommitInfo;
            fromJSON(object: any): _141.ExtendedCommitInfo;
            toJSON(message: _141.ExtendedCommitInfo): unknown;
            fromPartial(object: Partial<_141.ExtendedCommitInfo>): _141.ExtendedCommitInfo;
            fromAmino(object: _141.ExtendedCommitInfoAmino): _141.ExtendedCommitInfo;
            toAmino(message: _141.ExtendedCommitInfo): _141.ExtendedCommitInfoAmino;
            fromAminoMsg(object: _141.ExtendedCommitInfoAminoMsg): _141.ExtendedCommitInfo;
            fromProtoMsg(message: _141.ExtendedCommitInfoProtoMsg): _141.ExtendedCommitInfo;
            toProto(message: _141.ExtendedCommitInfo): Uint8Array;
            toProtoMsg(message: _141.ExtendedCommitInfo): _141.ExtendedCommitInfoProtoMsg;
        };
        Event: {
            typeUrl: string;
            encode(message: _141.Event, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number | undefined): _141.Event;
            fromJSON(object: any): _141.Event;
            toJSON(message: _141.Event): unknown;
            fromPartial(object: Partial<_141.Event>): _141.Event;
            fromAmino(object: _141.EventAmino): _141.Event;
            toAmino(message: _141.Event): _141.EventAmino;
            fromAminoMsg(object: _141.EventAminoMsg): _141.Event;
            fromProtoMsg(message: _141.EventProtoMsg): _141.Event;
            toProto(message: _141.Event): Uint8Array;
            toProtoMsg(message: _141.Event): _141.EventProtoMsg;
        };
        EventAttribute: {
            typeUrl: string;
            encode(message: _141.EventAttribute, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number | undefined): _141.EventAttribute;
            fromJSON(object: any): _141.EventAttribute;
            toJSON(message: _141.EventAttribute): unknown;
            fromPartial(object: Partial<_141.EventAttribute>): _141.EventAttribute;
            fromAmino(object: _141.EventAttributeAmino): _141.EventAttribute;
            toAmino(message: _141.EventAttribute): _141.EventAttributeAmino;
            fromAminoMsg(object: _141.EventAttributeAminoMsg): _141.EventAttribute;
            fromProtoMsg(message: _141.EventAttributeProtoMsg): _141.EventAttribute;
            toProto(message: _141.EventAttribute): Uint8Array;
            toProtoMsg(message: _141.EventAttribute): _141.EventAttributeProtoMsg;
        };
        TxResult: {
            typeUrl: string;
            encode(message: _141.TxResult, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number | undefined): _141.TxResult;
            fromJSON(object: any): _141.TxResult;
            toJSON(message: _141.TxResult): unknown;
            fromPartial(object: Partial<_141.TxResult>): _141.TxResult;
            fromAmino(object: _141.TxResultAmino): _141.TxResult;
            toAmino(message: _141.TxResult): _141.TxResultAmino;
            fromAminoMsg(object: _141.TxResultAminoMsg): _141.TxResult;
            fromProtoMsg(message: _141.TxResultProtoMsg): _141.TxResult;
            toProto(message: _141.TxResult): Uint8Array;
            toProtoMsg(message: _141.TxResult): _141.TxResultProtoMsg;
        };
        Validator: {
            typeUrl: string;
            encode(message: _141.Validator, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number | undefined): _141.Validator;
            fromJSON(object: any): _141.Validator;
            toJSON(message: _141.Validator): unknown;
            fromPartial(object: Partial<_141.Validator>): _141.Validator;
            fromAmino(object: _141.ValidatorAmino): _141.Validator;
            toAmino(message: _141.Validator): _141.ValidatorAmino;
            fromAminoMsg(object: _141.ValidatorAminoMsg): _141.Validator;
            fromProtoMsg(message: _141.ValidatorProtoMsg): _141.Validator;
            toProto(message: _141.Validator): Uint8Array;
            toProtoMsg(message: _141.Validator): _141.ValidatorProtoMsg;
        };
        ValidatorUpdate: {
            typeUrl: string;
            encode(message: _141.ValidatorUpdate, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number | undefined): _141.ValidatorUpdate;
            fromJSON(object: any): _141.ValidatorUpdate;
            toJSON(message: _141.ValidatorUpdate): unknown;
            fromPartial(object: Partial<_141.ValidatorUpdate>): _141.ValidatorUpdate;
            fromAmino(object: _141.ValidatorUpdateAmino): _141.ValidatorUpdate;
            toAmino(message: _141.ValidatorUpdate): _141.ValidatorUpdateAmino;
            fromAminoMsg(object: _141.ValidatorUpdateAminoMsg): _141.ValidatorUpdate;
            fromProtoMsg(message: _141.ValidatorUpdateProtoMsg): _141.ValidatorUpdate;
            toProto(message: _141.ValidatorUpdate): Uint8Array;
            toProtoMsg(message: _141.ValidatorUpdate): _141.ValidatorUpdateProtoMsg;
        };
        VoteInfo: {
            typeUrl: string;
            encode(message: _141.VoteInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number | undefined): _141.VoteInfo;
            fromJSON(object: any): _141.VoteInfo;
            toJSON(message: _141.VoteInfo): unknown;
            fromPartial(object: Partial<_141.VoteInfo>): _141.VoteInfo;
            fromAmino(object: _141.VoteInfoAmino): _141.VoteInfo;
            toAmino(message: _141.VoteInfo): _141.VoteInfoAmino;
            fromAminoMsg(object: _141.VoteInfoAminoMsg): _141.VoteInfo;
            fromProtoMsg(message: _141.VoteInfoProtoMsg): _141.VoteInfo;
            toProto(message: _141.VoteInfo): Uint8Array;
            toProtoMsg(message: _141.VoteInfo): _141.VoteInfoProtoMsg;
        };
        ExtendedVoteInfo: {
            typeUrl: string;
            encode(message: _141.ExtendedVoteInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number | undefined): _141.ExtendedVoteInfo;
            fromJSON(object: any): _141.ExtendedVoteInfo;
            toJSON(message: _141.ExtendedVoteInfo): unknown;
            fromPartial(object: Partial<_141.ExtendedVoteInfo>): _141.ExtendedVoteInfo;
            fromAmino(object: _141.ExtendedVoteInfoAmino): _141.ExtendedVoteInfo;
            toAmino(message: _141.ExtendedVoteInfo): _141.ExtendedVoteInfoAmino;
            fromAminoMsg(object: _141.ExtendedVoteInfoAminoMsg): _141.ExtendedVoteInfo;
            fromProtoMsg(message: _141.ExtendedVoteInfoProtoMsg): _141.ExtendedVoteInfo;
            toProto(message: _141.ExtendedVoteInfo): Uint8Array;
            toProtoMsg(message: _141.ExtendedVoteInfo): _141.ExtendedVoteInfoProtoMsg;
        };
        Misbehavior: {
            typeUrl: string;
            encode(message: _141.Misbehavior, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number | undefined): _141.Misbehavior;
            fromJSON(object: any): _141.Misbehavior;
            toJSON(message: _141.Misbehavior): unknown;
            fromPartial(object: Partial<_141.Misbehavior>): _141.Misbehavior;
            fromAmino(object: _141.MisbehaviorAmino): _141.Misbehavior;
            toAmino(message: _141.Misbehavior): _141.MisbehaviorAmino;
            fromAminoMsg(object: _141.MisbehaviorAminoMsg): _141.Misbehavior;
            fromProtoMsg(message: _141.MisbehaviorProtoMsg): _141.Misbehavior;
            toProto(message: _141.Misbehavior): Uint8Array;
            toProtoMsg(message: _141.Misbehavior): _141.MisbehaviorProtoMsg;
        };
        Snapshot: {
            typeUrl: string;
            encode(message: _141.Snapshot, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number | undefined): _141.Snapshot;
            fromJSON(object: any): _141.Snapshot;
            toJSON(message: _141.Snapshot): unknown;
            fromPartial(object: Partial<_141.Snapshot>): _141.Snapshot;
            fromAmino(object: _141.SnapshotAmino): _141.Snapshot;
            toAmino(message: _141.Snapshot): _141.SnapshotAmino;
            fromAminoMsg(object: _141.SnapshotAminoMsg): _141.Snapshot;
            fromProtoMsg(message: _141.SnapshotProtoMsg): _141.Snapshot;
            toProto(message: _141.Snapshot): Uint8Array;
            toProtoMsg(message: _141.Snapshot): _141.SnapshotProtoMsg;
        };
    };
    const crypto: {
        Proof: {
            typeUrl: string;
            encode(message: _143.Proof, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number | undefined): _143.Proof;
            fromJSON(object: any): _143.Proof;
            toJSON(message: _143.Proof): unknown;
            fromPartial(object: Partial<_143.Proof>): _143.Proof;
            fromAmino(object: _143.ProofAmino): _143.Proof;
            toAmino(message: _143.Proof): _143.ProofAmino;
            fromAminoMsg(object: _143.ProofAminoMsg): _143.Proof;
            fromProtoMsg(message: _143.ProofProtoMsg): _143.Proof;
            toProto(message: _143.Proof): Uint8Array;
            toProtoMsg(message: _143.Proof): _143.ProofProtoMsg;
        };
        ValueOp: {
            typeUrl: string;
            encode(message: _143.ValueOp, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number | undefined): _143.ValueOp;
            fromJSON(object: any): _143.ValueOp;
            toJSON(message: _143.ValueOp): unknown;
            fromPartial(object: Partial<_143.ValueOp>): _143.ValueOp;
            fromAmino(object: _143.ValueOpAmino): _143.ValueOp;
            toAmino(message: _143.ValueOp): _143.ValueOpAmino;
            fromAminoMsg(object: _143.ValueOpAminoMsg): _143.ValueOp;
            fromProtoMsg(message: _143.ValueOpProtoMsg): _143.ValueOp;
            toProto(message: _143.ValueOp): Uint8Array;
            toProtoMsg(message: _143.ValueOp): _143.ValueOpProtoMsg;
        };
        DominoOp: {
            typeUrl: string;
            encode(message: _143.DominoOp, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number | undefined): _143.DominoOp;
            fromJSON(object: any): _143.DominoOp;
            toJSON(message: _143.DominoOp): unknown;
            fromPartial(object: Partial<_143.DominoOp>): _143.DominoOp;
            fromAmino(object: _143.DominoOpAmino): _143.DominoOp;
            toAmino(message: _143.DominoOp): _143.DominoOpAmino;
            fromAminoMsg(object: _143.DominoOpAminoMsg): _143.DominoOp;
            fromProtoMsg(message: _143.DominoOpProtoMsg): _143.DominoOp;
            toProto(message: _143.DominoOp): Uint8Array;
            toProtoMsg(message: _143.DominoOp): _143.DominoOpProtoMsg;
        };
        ProofOp: {
            typeUrl: string;
            encode(message: _143.ProofOp, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number | undefined): _143.ProofOp;
            fromJSON(object: any): _143.ProofOp;
            toJSON(message: _143.ProofOp): unknown;
            fromPartial(object: Partial<_143.ProofOp>): _143.ProofOp;
            fromAmino(object: _143.ProofOpAmino): _143.ProofOp;
            toAmino(message: _143.ProofOp): _143.ProofOpAmino;
            fromAminoMsg(object: _143.ProofOpAminoMsg): _143.ProofOp;
            fromProtoMsg(message: _143.ProofOpProtoMsg): _143.ProofOp;
            toProto(message: _143.ProofOp): Uint8Array;
            toProtoMsg(message: _143.ProofOp): _143.ProofOpProtoMsg;
        };
        ProofOps: {
            typeUrl: string;
            encode(message: _143.ProofOps, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number | undefined): _143.ProofOps;
            fromJSON(object: any): _143.ProofOps;
            toJSON(message: _143.ProofOps): unknown;
            fromPartial(object: Partial<_143.ProofOps>): _143.ProofOps;
            fromAmino(object: _143.ProofOpsAmino): _143.ProofOps;
            toAmino(message: _143.ProofOps): _143.ProofOpsAmino;
            fromAminoMsg(object: _143.ProofOpsAminoMsg): _143.ProofOps;
            fromProtoMsg(message: _143.ProofOpsProtoMsg): _143.ProofOps;
            toProto(message: _143.ProofOps): Uint8Array;
            toProtoMsg(message: _143.ProofOps): _143.ProofOpsProtoMsg;
        };
        PublicKey: {
            typeUrl: string;
            encode(message: _142.PublicKey, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number | undefined): _142.PublicKey;
            fromJSON(object: any): _142.PublicKey;
            toJSON(message: _142.PublicKey): unknown;
            fromPartial(object: Partial<_142.PublicKey>): _142.PublicKey;
            fromAmino(object: _142.PublicKeyAmino): _142.PublicKey;
            toAmino(message: _142.PublicKey): _142.PublicKeyAmino;
            fromAminoMsg(object: _142.PublicKeyAminoMsg): _142.PublicKey;
            fromProtoMsg(message: _142.PublicKeyProtoMsg): _142.PublicKey;
            toProto(message: _142.PublicKey): Uint8Array;
            toProtoMsg(message: _142.PublicKey): _142.PublicKeyProtoMsg;
        };
    };
    namespace libs {
        const bits: {
            BitArray: {
                typeUrl: string;
                encode(message: _144.BitArray, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
                decode(input: Uint8Array | import("..").BinaryReader, length?: number | undefined): _144.BitArray;
                fromJSON(object: any): _144.BitArray;
                toJSON(message: _144.BitArray): unknown;
                fromPartial(object: Partial<_144.BitArray>): _144.BitArray;
                fromAmino(object: _144.BitArrayAmino): _144.BitArray;
                toAmino(message: _144.BitArray): _144.BitArrayAmino;
                fromAminoMsg(object: _144.BitArrayAminoMsg): _144.BitArray;
                fromProtoMsg(message: _144.BitArrayProtoMsg): _144.BitArray;
                toProto(message: _144.BitArray): Uint8Array;
                toProtoMsg(message: _144.BitArray): _144.BitArrayProtoMsg;
            };
        };
    }
    const p2p: {
        NetAddress: {
            typeUrl: string;
            encode(message: _145.NetAddress, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number | undefined): _145.NetAddress;
            fromJSON(object: any): _145.NetAddress;
            toJSON(message: _145.NetAddress): unknown;
            fromPartial(object: Partial<_145.NetAddress>): _145.NetAddress;
            fromAmino(object: _145.NetAddressAmino): _145.NetAddress;
            toAmino(message: _145.NetAddress): _145.NetAddressAmino;
            fromAminoMsg(object: _145.NetAddressAminoMsg): _145.NetAddress;
            fromProtoMsg(message: _145.NetAddressProtoMsg): _145.NetAddress;
            toProto(message: _145.NetAddress): Uint8Array;
            toProtoMsg(message: _145.NetAddress): _145.NetAddressProtoMsg;
        };
        ProtocolVersion: {
            typeUrl: string;
            encode(message: _145.ProtocolVersion, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number | undefined): _145.ProtocolVersion;
            fromJSON(object: any): _145.ProtocolVersion;
            toJSON(message: _145.ProtocolVersion): unknown;
            fromPartial(object: Partial<_145.ProtocolVersion>): _145.ProtocolVersion;
            fromAmino(object: _145.ProtocolVersionAmino): _145.ProtocolVersion;
            toAmino(message: _145.ProtocolVersion): _145.ProtocolVersionAmino;
            fromAminoMsg(object: _145.ProtocolVersionAminoMsg): _145.ProtocolVersion;
            fromProtoMsg(message: _145.ProtocolVersionProtoMsg): _145.ProtocolVersion;
            toProto(message: _145.ProtocolVersion): Uint8Array;
            toProtoMsg(message: _145.ProtocolVersion): _145.ProtocolVersionProtoMsg;
        };
        DefaultNodeInfo: {
            typeUrl: string;
            encode(message: _145.DefaultNodeInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number | undefined): _145.DefaultNodeInfo;
            fromJSON(object: any): _145.DefaultNodeInfo;
            toJSON(message: _145.DefaultNodeInfo): unknown;
            fromPartial(object: Partial<_145.DefaultNodeInfo>): _145.DefaultNodeInfo;
            fromAmino(object: _145.DefaultNodeInfoAmino): _145.DefaultNodeInfo;
            toAmino(message: _145.DefaultNodeInfo): _145.DefaultNodeInfoAmino;
            fromAminoMsg(object: _145.DefaultNodeInfoAminoMsg): _145.DefaultNodeInfo;
            fromProtoMsg(message: _145.DefaultNodeInfoProtoMsg): _145.DefaultNodeInfo;
            toProto(message: _145.DefaultNodeInfo): Uint8Array;
            toProtoMsg(message: _145.DefaultNodeInfo): _145.DefaultNodeInfoProtoMsg;
        };
        DefaultNodeInfoOther: {
            typeUrl: string;
            encode(message: _145.DefaultNodeInfoOther, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number | undefined): _145.DefaultNodeInfoOther;
            fromJSON(object: any): _145.DefaultNodeInfoOther;
            toJSON(message: _145.DefaultNodeInfoOther): unknown;
            fromPartial(object: Partial<_145.DefaultNodeInfoOther>): _145.DefaultNodeInfoOther;
            fromAmino(object: _145.DefaultNodeInfoOtherAmino): _145.DefaultNodeInfoOther;
            toAmino(message: _145.DefaultNodeInfoOther): _145.DefaultNodeInfoOtherAmino;
            fromAminoMsg(object: _145.DefaultNodeInfoOtherAminoMsg): _145.DefaultNodeInfoOther;
            fromProtoMsg(message: _145.DefaultNodeInfoOtherProtoMsg): _145.DefaultNodeInfoOther;
            toProto(message: _145.DefaultNodeInfoOther): Uint8Array;
            toProtoMsg(message: _145.DefaultNodeInfoOther): _145.DefaultNodeInfoOtherProtoMsg;
        };
    };
    const types: {
        ValidatorSet: {
            typeUrl: string;
            encode(message: _150.ValidatorSet, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number | undefined): _150.ValidatorSet;
            fromJSON(object: any): _150.ValidatorSet;
            toJSON(message: _150.ValidatorSet): unknown;
            fromPartial(object: Partial<_150.ValidatorSet>): _150.ValidatorSet;
            fromAmino(object: _150.ValidatorSetAmino): _150.ValidatorSet;
            toAmino(message: _150.ValidatorSet): _150.ValidatorSetAmino;
            fromAminoMsg(object: _150.ValidatorSetAminoMsg): _150.ValidatorSet;
            fromProtoMsg(message: _150.ValidatorSetProtoMsg): _150.ValidatorSet;
            toProto(message: _150.ValidatorSet): Uint8Array;
            toProtoMsg(message: _150.ValidatorSet): _150.ValidatorSetProtoMsg;
        };
        Validator: {
            typeUrl: string;
            encode(message: _150.Validator, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number | undefined): _150.Validator;
            fromJSON(object: any): _150.Validator;
            toJSON(message: _150.Validator): unknown;
            fromPartial(object: Partial<_150.Validator>): _150.Validator;
            fromAmino(object: _150.ValidatorAmino): _150.Validator;
            toAmino(message: _150.Validator): _150.ValidatorAmino;
            fromAminoMsg(object: _150.ValidatorAminoMsg): _150.Validator;
            fromProtoMsg(message: _150.ValidatorProtoMsg): _150.Validator;
            toProto(message: _150.Validator): Uint8Array;
            toProtoMsg(message: _150.Validator): _150.ValidatorProtoMsg;
        };
        SimpleValidator: {
            typeUrl: string;
            encode(message: _150.SimpleValidator, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number | undefined): _150.SimpleValidator;
            fromJSON(object: any): _150.SimpleValidator;
            toJSON(message: _150.SimpleValidator): unknown;
            fromPartial(object: Partial<_150.SimpleValidator>): _150.SimpleValidator;
            fromAmino(object: _150.SimpleValidatorAmino): _150.SimpleValidator;
            toAmino(message: _150.SimpleValidator): _150.SimpleValidatorAmino;
            fromAminoMsg(object: _150.SimpleValidatorAminoMsg): _150.SimpleValidator;
            fromProtoMsg(message: _150.SimpleValidatorProtoMsg): _150.SimpleValidator;
            toProto(message: _150.SimpleValidator): Uint8Array;
            toProtoMsg(message: _150.SimpleValidator): _150.SimpleValidatorProtoMsg;
        };
        blockIDFlagFromJSON(object: any): _149.BlockIDFlag;
        blockIDFlagToJSON(object: _149.BlockIDFlag): string;
        signedMsgTypeFromJSON(object: any): _149.SignedMsgType;
        signedMsgTypeToJSON(object: _149.SignedMsgType): string;
        BlockIDFlag: typeof _149.BlockIDFlag;
        BlockIDFlagSDKType: typeof _149.BlockIDFlag;
        BlockIDFlagAmino: typeof _149.BlockIDFlag;
        SignedMsgType: typeof _149.SignedMsgType;
        SignedMsgTypeSDKType: typeof _149.SignedMsgType;
        SignedMsgTypeAmino: typeof _149.SignedMsgType;
        PartSetHeader: {
            typeUrl: string;
            encode(message: _149.PartSetHeader, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number | undefined): _149.PartSetHeader;
            fromJSON(object: any): _149.PartSetHeader;
            toJSON(message: _149.PartSetHeader): unknown;
            fromPartial(object: Partial<_149.PartSetHeader>): _149.PartSetHeader;
            fromAmino(object: _149.PartSetHeaderAmino): _149.PartSetHeader;
            toAmino(message: _149.PartSetHeader): _149.PartSetHeaderAmino;
            fromAminoMsg(object: _149.PartSetHeaderAminoMsg): _149.PartSetHeader;
            fromProtoMsg(message: _149.PartSetHeaderProtoMsg): _149.PartSetHeader;
            toProto(message: _149.PartSetHeader): Uint8Array;
            toProtoMsg(message: _149.PartSetHeader): _149.PartSetHeaderProtoMsg;
        };
        Part: {
            typeUrl: string;
            encode(message: _149.Part, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number | undefined): _149.Part;
            fromJSON(object: any): _149.Part;
            toJSON(message: _149.Part): unknown;
            fromPartial(object: Partial<_149.Part>): _149.Part;
            fromAmino(object: _149.PartAmino): _149.Part;
            toAmino(message: _149.Part): _149.PartAmino;
            fromAminoMsg(object: _149.PartAminoMsg): _149.Part;
            fromProtoMsg(message: _149.PartProtoMsg): _149.Part;
            toProto(message: _149.Part): Uint8Array;
            toProtoMsg(message: _149.Part): _149.PartProtoMsg;
        };
        BlockID: {
            typeUrl: string;
            encode(message: _149.BlockID, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number | undefined): _149.BlockID;
            fromJSON(object: any): _149.BlockID;
            toJSON(message: _149.BlockID): unknown;
            fromPartial(object: Partial<_149.BlockID>): _149.BlockID;
            fromAmino(object: _149.BlockIDAmino): _149.BlockID;
            toAmino(message: _149.BlockID): _149.BlockIDAmino;
            fromAminoMsg(object: _149.BlockIDAminoMsg): _149.BlockID;
            fromProtoMsg(message: _149.BlockIDProtoMsg): _149.BlockID;
            toProto(message: _149.BlockID): Uint8Array;
            toProtoMsg(message: _149.BlockID): _149.BlockIDProtoMsg;
        };
        Header: {
            typeUrl: string;
            encode(message: _149.Header, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number | undefined): _149.Header;
            fromJSON(object: any): _149.Header;
            toJSON(message: _149.Header): unknown;
            fromPartial(object: Partial<_149.Header>): _149.Header;
            fromAmino(object: _149.HeaderAmino): _149.Header;
            toAmino(message: _149.Header): _149.HeaderAmino;
            fromAminoMsg(object: _149.HeaderAminoMsg): _149.Header;
            fromProtoMsg(message: _149.HeaderProtoMsg): _149.Header;
            toProto(message: _149.Header): Uint8Array;
            toProtoMsg(message: _149.Header): _149.HeaderProtoMsg;
        };
        Data: {
            typeUrl: string;
            encode(message: _149.Data, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number | undefined): _149.Data;
            fromJSON(object: any): _149.Data;
            toJSON(message: _149.Data): unknown;
            fromPartial(object: Partial<_149.Data>): _149.Data;
            fromAmino(object: _149.DataAmino): _149.Data;
            toAmino(message: _149.Data): _149.DataAmino;
            fromAminoMsg(object: _149.DataAminoMsg): _149.Data;
            fromProtoMsg(message: _149.DataProtoMsg): _149.Data;
            toProto(message: _149.Data): Uint8Array;
            toProtoMsg(message: _149.Data): _149.DataProtoMsg;
        };
        Vote: {
            typeUrl: string;
            encode(message: _149.Vote, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number | undefined): _149.Vote;
            fromJSON(object: any): _149.Vote;
            toJSON(message: _149.Vote): unknown;
            fromPartial(object: Partial<_149.Vote>): _149.Vote;
            fromAmino(object: _149.VoteAmino): _149.Vote;
            toAmino(message: _149.Vote): _149.VoteAmino;
            fromAminoMsg(object: _149.VoteAminoMsg): _149.Vote;
            fromProtoMsg(message: _149.VoteProtoMsg): _149.Vote;
            toProto(message: _149.Vote): Uint8Array;
            toProtoMsg(message: _149.Vote): _149.VoteProtoMsg;
        };
        Commit: {
            typeUrl: string;
            encode(message: _149.Commit, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number | undefined): _149.Commit;
            fromJSON(object: any): _149.Commit;
            toJSON(message: _149.Commit): unknown;
            fromPartial(object: Partial<_149.Commit>): _149.Commit;
            fromAmino(object: _149.CommitAmino): _149.Commit;
            toAmino(message: _149.Commit): _149.CommitAmino;
            fromAminoMsg(object: _149.CommitAminoMsg): _149.Commit;
            fromProtoMsg(message: _149.CommitProtoMsg): _149.Commit;
            toProto(message: _149.Commit): Uint8Array;
            toProtoMsg(message: _149.Commit): _149.CommitProtoMsg;
        };
        CommitSig: {
            typeUrl: string;
            encode(message: _149.CommitSig, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number | undefined): _149.CommitSig;
            fromJSON(object: any): _149.CommitSig;
            toJSON(message: _149.CommitSig): unknown;
            fromPartial(object: Partial<_149.CommitSig>): _149.CommitSig;
            fromAmino(object: _149.CommitSigAmino): _149.CommitSig;
            toAmino(message: _149.CommitSig): _149.CommitSigAmino;
            fromAminoMsg(object: _149.CommitSigAminoMsg): _149.CommitSig;
            fromProtoMsg(message: _149.CommitSigProtoMsg): _149.CommitSig;
            toProto(message: _149.CommitSig): Uint8Array;
            toProtoMsg(message: _149.CommitSig): _149.CommitSigProtoMsg;
        };
        Proposal: {
            typeUrl: string;
            encode(message: _149.Proposal, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number | undefined): _149.Proposal;
            fromJSON(object: any): _149.Proposal;
            toJSON(message: _149.Proposal): unknown;
            fromPartial(object: Partial<_149.Proposal>): _149.Proposal;
            fromAmino(object: _149.ProposalAmino): _149.Proposal;
            toAmino(message: _149.Proposal): _149.ProposalAmino;
            fromAminoMsg(object: _149.ProposalAminoMsg): _149.Proposal;
            fromProtoMsg(message: _149.ProposalProtoMsg): _149.Proposal;
            toProto(message: _149.Proposal): Uint8Array;
            toProtoMsg(message: _149.Proposal): _149.ProposalProtoMsg;
        };
        SignedHeader: {
            typeUrl: string;
            encode(message: _149.SignedHeader, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number | undefined): _149.SignedHeader;
            fromJSON(object: any): _149.SignedHeader;
            toJSON(message: _149.SignedHeader): unknown;
            fromPartial(object: Partial<_149.SignedHeader>): _149.SignedHeader;
            fromAmino(object: _149.SignedHeaderAmino): _149.SignedHeader;
            toAmino(message: _149.SignedHeader): _149.SignedHeaderAmino;
            fromAminoMsg(object: _149.SignedHeaderAminoMsg): _149.SignedHeader;
            fromProtoMsg(message: _149.SignedHeaderProtoMsg): _149.SignedHeader;
            toProto(message: _149.SignedHeader): Uint8Array;
            toProtoMsg(message: _149.SignedHeader): _149.SignedHeaderProtoMsg;
        };
        LightBlock: {
            typeUrl: string;
            encode(message: _149.LightBlock, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number | undefined): _149.LightBlock;
            fromJSON(object: any): _149.LightBlock;
            toJSON(message: _149.LightBlock): unknown;
            fromPartial(object: Partial<_149.LightBlock>): _149.LightBlock;
            fromAmino(object: _149.LightBlockAmino): _149.LightBlock;
            toAmino(message: _149.LightBlock): _149.LightBlockAmino;
            fromAminoMsg(object: _149.LightBlockAminoMsg): _149.LightBlock;
            fromProtoMsg(message: _149.LightBlockProtoMsg): _149.LightBlock;
            toProto(message: _149.LightBlock): Uint8Array;
            toProtoMsg(message: _149.LightBlock): _149.LightBlockProtoMsg;
        };
        BlockMeta: {
            typeUrl: string;
            encode(message: _149.BlockMeta, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number | undefined): _149.BlockMeta;
            fromJSON(object: any): _149.BlockMeta;
            toJSON(message: _149.BlockMeta): unknown;
            fromPartial(object: Partial<_149.BlockMeta>): _149.BlockMeta;
            fromAmino(object: _149.BlockMetaAmino): _149.BlockMeta;
            toAmino(message: _149.BlockMeta): _149.BlockMetaAmino;
            fromAminoMsg(object: _149.BlockMetaAminoMsg): _149.BlockMeta;
            fromProtoMsg(message: _149.BlockMetaProtoMsg): _149.BlockMeta;
            toProto(message: _149.BlockMeta): Uint8Array;
            toProtoMsg(message: _149.BlockMeta): _149.BlockMetaProtoMsg;
        };
        TxProof: {
            typeUrl: string;
            encode(message: _149.TxProof, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number | undefined): _149.TxProof;
            fromJSON(object: any): _149.TxProof;
            toJSON(message: _149.TxProof): unknown;
            fromPartial(object: Partial<_149.TxProof>): _149.TxProof;
            fromAmino(object: _149.TxProofAmino): _149.TxProof;
            toAmino(message: _149.TxProof): _149.TxProofAmino;
            fromAminoMsg(object: _149.TxProofAminoMsg): _149.TxProof;
            fromProtoMsg(message: _149.TxProofProtoMsg): _149.TxProof;
            toProto(message: _149.TxProof): Uint8Array;
            toProtoMsg(message: _149.TxProof): _149.TxProofProtoMsg;
        };
        ConsensusParams: {
            typeUrl: string;
            encode(message: _148.ConsensusParams, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number | undefined): _148.ConsensusParams;
            fromJSON(object: any): _148.ConsensusParams;
            toJSON(message: _148.ConsensusParams): unknown;
            fromPartial(object: Partial<_148.ConsensusParams>): _148.ConsensusParams;
            fromAmino(object: _148.ConsensusParamsAmino): _148.ConsensusParams;
            toAmino(message: _148.ConsensusParams): _148.ConsensusParamsAmino;
            fromAminoMsg(object: _148.ConsensusParamsAminoMsg): _148.ConsensusParams;
            fromProtoMsg(message: _148.ConsensusParamsProtoMsg): _148.ConsensusParams;
            toProto(message: _148.ConsensusParams): Uint8Array;
            toProtoMsg(message: _148.ConsensusParams): _148.ConsensusParamsProtoMsg;
        };
        BlockParams: {
            typeUrl: string;
            encode(message: _148.BlockParams, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number | undefined): _148.BlockParams;
            fromJSON(object: any): _148.BlockParams;
            toJSON(message: _148.BlockParams): unknown;
            fromPartial(object: Partial<_148.BlockParams>): _148.BlockParams;
            fromAmino(object: _148.BlockParamsAmino): _148.BlockParams;
            toAmino(message: _148.BlockParams): _148.BlockParamsAmino;
            fromAminoMsg(object: _148.BlockParamsAminoMsg): _148.BlockParams;
            fromProtoMsg(message: _148.BlockParamsProtoMsg): _148.BlockParams;
            toProto(message: _148.BlockParams): Uint8Array;
            toProtoMsg(message: _148.BlockParams): _148.BlockParamsProtoMsg;
        };
        EvidenceParams: {
            typeUrl: string;
            encode(message: _148.EvidenceParams, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number | undefined): _148.EvidenceParams;
            fromJSON(object: any): _148.EvidenceParams;
            toJSON(message: _148.EvidenceParams): unknown;
            fromPartial(object: Partial<_148.EvidenceParams>): _148.EvidenceParams;
            fromAmino(object: _148.EvidenceParamsAmino): _148.EvidenceParams;
            toAmino(message: _148.EvidenceParams): _148.EvidenceParamsAmino;
            fromAminoMsg(object: _148.EvidenceParamsAminoMsg): _148.EvidenceParams;
            fromProtoMsg(message: _148.EvidenceParamsProtoMsg): _148.EvidenceParams;
            toProto(message: _148.EvidenceParams): Uint8Array;
            toProtoMsg(message: _148.EvidenceParams): _148.EvidenceParamsProtoMsg;
        };
        ValidatorParams: {
            typeUrl: string;
            encode(message: _148.ValidatorParams, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number | undefined): _148.ValidatorParams;
            fromJSON(object: any): _148.ValidatorParams;
            toJSON(message: _148.ValidatorParams): unknown;
            fromPartial(object: Partial<_148.ValidatorParams>): _148.ValidatorParams;
            fromAmino(object: _148.ValidatorParamsAmino): _148.ValidatorParams;
            toAmino(message: _148.ValidatorParams): _148.ValidatorParamsAmino;
            fromAminoMsg(object: _148.ValidatorParamsAminoMsg): _148.ValidatorParams;
            fromProtoMsg(message: _148.ValidatorParamsProtoMsg): _148.ValidatorParams;
            toProto(message: _148.ValidatorParams): Uint8Array;
            toProtoMsg(message: _148.ValidatorParams): _148.ValidatorParamsProtoMsg;
        };
        VersionParams: {
            typeUrl: string;
            encode(message: _148.VersionParams, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number | undefined): _148.VersionParams;
            fromJSON(object: any): _148.VersionParams;
            toJSON(message: _148.VersionParams): unknown;
            fromPartial(object: Partial<_148.VersionParams>): _148.VersionParams;
            fromAmino(object: _148.VersionParamsAmino): _148.VersionParams;
            toAmino(message: _148.VersionParams): _148.VersionParamsAmino;
            fromAminoMsg(object: _148.VersionParamsAminoMsg): _148.VersionParams;
            fromProtoMsg(message: _148.VersionParamsProtoMsg): _148.VersionParams;
            toProto(message: _148.VersionParams): Uint8Array;
            toProtoMsg(message: _148.VersionParams): _148.VersionParamsProtoMsg;
        };
        HashedParams: {
            typeUrl: string;
            encode(message: _148.HashedParams, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number | undefined): _148.HashedParams;
            fromJSON(object: any): _148.HashedParams;
            toJSON(message: _148.HashedParams): unknown;
            fromPartial(object: Partial<_148.HashedParams>): _148.HashedParams;
            fromAmino(object: _148.HashedParamsAmino): _148.HashedParams;
            toAmino(message: _148.HashedParams): _148.HashedParamsAmino;
            fromAminoMsg(object: _148.HashedParamsAminoMsg): _148.HashedParams;
            fromProtoMsg(message: _148.HashedParamsProtoMsg): _148.HashedParams;
            toProto(message: _148.HashedParams): Uint8Array;
            toProtoMsg(message: _148.HashedParams): _148.HashedParamsProtoMsg;
        };
        Evidence: {
            typeUrl: string;
            encode(message: _147.Evidence, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number | undefined): _147.Evidence;
            fromJSON(object: any): _147.Evidence;
            toJSON(message: _147.Evidence): unknown;
            fromPartial(object: Partial<_147.Evidence>): _147.Evidence;
            fromAmino(object: _147.EvidenceAmino): _147.Evidence;
            toAmino(message: _147.Evidence): _147.EvidenceAmino;
            fromAminoMsg(object: _147.EvidenceAminoMsg): _147.Evidence;
            fromProtoMsg(message: _147.EvidenceProtoMsg): _147.Evidence;
            toProto(message: _147.Evidence): Uint8Array;
            toProtoMsg(message: _147.Evidence): _147.EvidenceProtoMsg;
        };
        DuplicateVoteEvidence: {
            typeUrl: string;
            encode(message: _147.DuplicateVoteEvidence, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number | undefined): _147.DuplicateVoteEvidence;
            fromJSON(object: any): _147.DuplicateVoteEvidence;
            toJSON(message: _147.DuplicateVoteEvidence): unknown;
            fromPartial(object: Partial<_147.DuplicateVoteEvidence>): _147.DuplicateVoteEvidence;
            fromAmino(object: _147.DuplicateVoteEvidenceAmino): _147.DuplicateVoteEvidence;
            toAmino(message: _147.DuplicateVoteEvidence): _147.DuplicateVoteEvidenceAmino;
            fromAminoMsg(object: _147.DuplicateVoteEvidenceAminoMsg): _147.DuplicateVoteEvidence;
            fromProtoMsg(message: _147.DuplicateVoteEvidenceProtoMsg): _147.DuplicateVoteEvidence;
            toProto(message: _147.DuplicateVoteEvidence): Uint8Array;
            toProtoMsg(message: _147.DuplicateVoteEvidence): _147.DuplicateVoteEvidenceProtoMsg;
        };
        LightClientAttackEvidence: {
            typeUrl: string;
            encode(message: _147.LightClientAttackEvidence, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number | undefined): _147.LightClientAttackEvidence;
            fromJSON(object: any): _147.LightClientAttackEvidence;
            toJSON(message: _147.LightClientAttackEvidence): unknown;
            fromPartial(object: Partial<_147.LightClientAttackEvidence>): _147.LightClientAttackEvidence;
            fromAmino(object: _147.LightClientAttackEvidenceAmino): _147.LightClientAttackEvidence;
            toAmino(message: _147.LightClientAttackEvidence): _147.LightClientAttackEvidenceAmino;
            fromAminoMsg(object: _147.LightClientAttackEvidenceAminoMsg): _147.LightClientAttackEvidence;
            fromProtoMsg(message: _147.LightClientAttackEvidenceProtoMsg): _147.LightClientAttackEvidence;
            toProto(message: _147.LightClientAttackEvidence): Uint8Array;
            toProtoMsg(message: _147.LightClientAttackEvidence): _147.LightClientAttackEvidenceProtoMsg;
        };
        EvidenceList: {
            typeUrl: string;
            encode(message: _147.EvidenceList, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number | undefined): _147.EvidenceList;
            fromJSON(object: any): _147.EvidenceList;
            toJSON(message: _147.EvidenceList): unknown;
            fromPartial(object: Partial<_147.EvidenceList>): _147.EvidenceList;
            fromAmino(object: _147.EvidenceListAmino): _147.EvidenceList;
            toAmino(message: _147.EvidenceList): _147.EvidenceListAmino;
            fromAminoMsg(object: _147.EvidenceListAminoMsg): _147.EvidenceList;
            fromProtoMsg(message: _147.EvidenceListProtoMsg): _147.EvidenceList;
            toProto(message: _147.EvidenceList): Uint8Array;
            toProtoMsg(message: _147.EvidenceList): _147.EvidenceListProtoMsg;
        };
        Block: {
            typeUrl: string;
            encode(message: _146.Block, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number | undefined): _146.Block;
            fromJSON(object: any): _146.Block;
            toJSON(message: _146.Block): unknown;
            fromPartial(object: Partial<_146.Block>): _146.Block;
            fromAmino(object: _146.BlockAmino): _146.Block;
            toAmino(message: _146.Block): _146.BlockAmino;
            fromAminoMsg(object: _146.BlockAminoMsg): _146.Block;
            fromProtoMsg(message: _146.BlockProtoMsg): _146.Block;
            toProto(message: _146.Block): Uint8Array;
            toProtoMsg(message: _146.Block): _146.BlockProtoMsg;
        };
    };
    const version: {
        App: {
            typeUrl: string;
            encode(message: _151.App, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number | undefined): _151.App;
            fromJSON(object: any): _151.App;
            toJSON(message: _151.App): unknown;
            fromPartial(object: Partial<_151.App>): _151.App;
            fromAmino(object: _151.AppAmino): _151.App;
            toAmino(message: _151.App): _151.AppAmino;
            fromAminoMsg(object: _151.AppAminoMsg): _151.App;
            fromProtoMsg(message: _151.AppProtoMsg): _151.App;
            toProto(message: _151.App): Uint8Array;
            toProtoMsg(message: _151.App): _151.AppProtoMsg;
        };
        Consensus: {
            typeUrl: string;
            encode(message: _151.Consensus, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number | undefined): _151.Consensus;
            fromJSON(object: any): _151.Consensus;
            toJSON(message: _151.Consensus): unknown;
            fromPartial(object: Partial<_151.Consensus>): _151.Consensus;
            fromAmino(object: _151.ConsensusAmino): _151.Consensus;
            toAmino(message: _151.Consensus): _151.ConsensusAmino;
            fromAminoMsg(object: _151.ConsensusAminoMsg): _151.Consensus;
            fromProtoMsg(message: _151.ConsensusProtoMsg): _151.Consensus;
            toProto(message: _151.Consensus): Uint8Array;
            toProtoMsg(message: _151.Consensus): _151.ConsensusProtoMsg;
        };
    };
}
