import * as _101 from "./protobuf/any";
import * as _102 from "./protobuf/descriptor";
import * as _103 from "./protobuf/duration";
import * as _104 from "./protobuf/empty";
import * as _105 from "./protobuf/timestamp";
export declare namespace google {
    const api: {};
    const protobuf: {
        Timestamp: {
            encode(message: _105.Timestamp, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number | undefined): _105.Timestamp;
            fromJSON(object: any): _105.Timestamp;
            toJSON(message: _105.Timestamp): unknown;
            fromPartial(object: Partial<_105.Timestamp>): _105.Timestamp;
            fromAmino(object: string): _105.Timestamp;
            toAmino(message: _105.Timestamp): string;
            fromAminoMsg(object: _105.TimestampAminoMsg): _105.Timestamp;
            fromProtoMsg(message: _105.TimestampProtoMsg): _105.Timestamp;
            toProto(message: _105.Timestamp): Uint8Array;
            toProtoMsg(message: _105.Timestamp): _105.TimestampProtoMsg;
        };
        Empty: {
            encode(_: _104.Empty, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number | undefined): _104.Empty;
            fromJSON(_: any): _104.Empty;
            toJSON(_: _104.Empty): unknown;
            fromPartial(_: Partial<_104.Empty>): _104.Empty;
            fromAmino(_: _104.EmptyAmino): _104.Empty;
            toAmino(_: _104.Empty): _104.EmptyAmino;
            fromAminoMsg(object: _104.EmptyAminoMsg): _104.Empty;
            fromProtoMsg(message: _104.EmptyProtoMsg): _104.Empty;
            toProto(message: _104.Empty): Uint8Array;
            toProtoMsg(message: _104.Empty): _104.EmptyProtoMsg;
        };
        Duration: {
            encode(message: _103.Duration, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number | undefined): _103.Duration;
            fromJSON(object: any): _103.Duration;
            toJSON(message: _103.Duration): unknown;
            fromPartial(object: Partial<_103.Duration>): _103.Duration;
            fromAmino(object: string): _103.Duration;
            toAmino(message: _103.Duration): string;
            fromAminoMsg(object: _103.DurationAminoMsg): _103.Duration;
            fromProtoMsg(message: _103.DurationProtoMsg): _103.Duration;
            toProto(message: _103.Duration): Uint8Array;
            toProtoMsg(message: _103.Duration): _103.DurationProtoMsg;
        };
        fieldDescriptorProto_TypeFromJSON(object: any): _102.FieldDescriptorProto_Type;
        fieldDescriptorProto_TypeToJSON(object: _102.FieldDescriptorProto_Type): string;
        fieldDescriptorProto_LabelFromJSON(object: any): _102.FieldDescriptorProto_Label;
        fieldDescriptorProto_LabelToJSON(object: _102.FieldDescriptorProto_Label): string;
        fileOptions_OptimizeModeFromJSON(object: any): _102.FileOptions_OptimizeMode;
        fileOptions_OptimizeModeToJSON(object: _102.FileOptions_OptimizeMode): string;
        fieldOptions_CTypeFromJSON(object: any): _102.FieldOptions_CType;
        fieldOptions_CTypeToJSON(object: _102.FieldOptions_CType): string;
        fieldOptions_JSTypeFromJSON(object: any): _102.FieldOptions_JSType;
        fieldOptions_JSTypeToJSON(object: _102.FieldOptions_JSType): string;
        methodOptions_IdempotencyLevelFromJSON(object: any): _102.MethodOptions_IdempotencyLevel;
        methodOptions_IdempotencyLevelToJSON(object: _102.MethodOptions_IdempotencyLevel): string;
        FieldDescriptorProto_Type: typeof _102.FieldDescriptorProto_Type;
        FieldDescriptorProto_TypeSDKType: typeof _102.FieldDescriptorProto_Type;
        FieldDescriptorProto_TypeAmino: typeof _102.FieldDescriptorProto_Type;
        FieldDescriptorProto_Label: typeof _102.FieldDescriptorProto_Label;
        FieldDescriptorProto_LabelSDKType: typeof _102.FieldDescriptorProto_Label;
        FieldDescriptorProto_LabelAmino: typeof _102.FieldDescriptorProto_Label;
        FileOptions_OptimizeMode: typeof _102.FileOptions_OptimizeMode;
        FileOptions_OptimizeModeSDKType: typeof _102.FileOptions_OptimizeMode;
        FileOptions_OptimizeModeAmino: typeof _102.FileOptions_OptimizeMode;
        FieldOptions_CType: typeof _102.FieldOptions_CType;
        FieldOptions_CTypeSDKType: typeof _102.FieldOptions_CType;
        FieldOptions_CTypeAmino: typeof _102.FieldOptions_CType;
        FieldOptions_JSType: typeof _102.FieldOptions_JSType;
        FieldOptions_JSTypeSDKType: typeof _102.FieldOptions_JSType;
        FieldOptions_JSTypeAmino: typeof _102.FieldOptions_JSType;
        MethodOptions_IdempotencyLevel: typeof _102.MethodOptions_IdempotencyLevel;
        MethodOptions_IdempotencyLevelSDKType: typeof _102.MethodOptions_IdempotencyLevel;
        MethodOptions_IdempotencyLevelAmino: typeof _102.MethodOptions_IdempotencyLevel;
        FileDescriptorSet: {
            encode(message: _102.FileDescriptorSet, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number | undefined): _102.FileDescriptorSet;
            fromJSON(object: any): _102.FileDescriptorSet;
            toJSON(message: _102.FileDescriptorSet): unknown;
            fromPartial(object: Partial<_102.FileDescriptorSet>): _102.FileDescriptorSet;
            fromAmino(object: _102.FileDescriptorSetAmino): _102.FileDescriptorSet;
            toAmino(message: _102.FileDescriptorSet): _102.FileDescriptorSetAmino;
            fromAminoMsg(object: _102.FileDescriptorSetAminoMsg): _102.FileDescriptorSet;
            fromProtoMsg(message: _102.FileDescriptorSetProtoMsg): _102.FileDescriptorSet;
            toProto(message: _102.FileDescriptorSet): Uint8Array;
            toProtoMsg(message: _102.FileDescriptorSet): _102.FileDescriptorSetProtoMsg;
        };
        FileDescriptorProto: {
            encode(message: _102.FileDescriptorProto, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number | undefined): _102.FileDescriptorProto;
            fromJSON(object: any): _102.FileDescriptorProto;
            toJSON(message: _102.FileDescriptorProto): unknown;
            fromPartial(object: Partial<_102.FileDescriptorProto>): _102.FileDescriptorProto;
            fromAmino(object: _102.FileDescriptorProtoAmino): _102.FileDescriptorProto;
            toAmino(message: _102.FileDescriptorProto): _102.FileDescriptorProtoAmino;
            fromAminoMsg(object: _102.FileDescriptorProtoAminoMsg): _102.FileDescriptorProto;
            fromProtoMsg(message: _102.FileDescriptorProtoProtoMsg): _102.FileDescriptorProto;
            toProto(message: _102.FileDescriptorProto): Uint8Array;
            toProtoMsg(message: _102.FileDescriptorProto): _102.FileDescriptorProtoProtoMsg;
        };
        DescriptorProto: {
            encode(message: _102.DescriptorProto, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number | undefined): _102.DescriptorProto;
            fromJSON(object: any): _102.DescriptorProto;
            toJSON(message: _102.DescriptorProto): unknown;
            fromPartial(object: Partial<_102.DescriptorProto>): _102.DescriptorProto;
            fromAmino(object: _102.DescriptorProtoAmino): _102.DescriptorProto;
            toAmino(message: _102.DescriptorProto): _102.DescriptorProtoAmino;
            fromAminoMsg(object: _102.DescriptorProtoAminoMsg): _102.DescriptorProto;
            fromProtoMsg(message: _102.DescriptorProtoProtoMsg): _102.DescriptorProto;
            toProto(message: _102.DescriptorProto): Uint8Array;
            toProtoMsg(message: _102.DescriptorProto): _102.DescriptorProtoProtoMsg;
        };
        DescriptorProto_ExtensionRange: {
            encode(message: _102.DescriptorProto_ExtensionRange, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number | undefined): _102.DescriptorProto_ExtensionRange;
            fromJSON(object: any): _102.DescriptorProto_ExtensionRange;
            toJSON(message: _102.DescriptorProto_ExtensionRange): unknown;
            fromPartial(object: Partial<_102.DescriptorProto_ExtensionRange>): _102.DescriptorProto_ExtensionRange;
            fromAmino(object: _102.DescriptorProto_ExtensionRangeAmino): _102.DescriptorProto_ExtensionRange;
            toAmino(message: _102.DescriptorProto_ExtensionRange): _102.DescriptorProto_ExtensionRangeAmino;
            fromAminoMsg(object: _102.DescriptorProto_ExtensionRangeAminoMsg): _102.DescriptorProto_ExtensionRange;
            fromProtoMsg(message: _102.DescriptorProto_ExtensionRangeProtoMsg): _102.DescriptorProto_ExtensionRange;
            toProto(message: _102.DescriptorProto_ExtensionRange): Uint8Array;
            toProtoMsg(message: _102.DescriptorProto_ExtensionRange): _102.DescriptorProto_ExtensionRangeProtoMsg;
        };
        DescriptorProto_ReservedRange: {
            encode(message: _102.DescriptorProto_ReservedRange, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number | undefined): _102.DescriptorProto_ReservedRange;
            fromJSON(object: any): _102.DescriptorProto_ReservedRange;
            toJSON(message: _102.DescriptorProto_ReservedRange): unknown;
            fromPartial(object: Partial<_102.DescriptorProto_ReservedRange>): _102.DescriptorProto_ReservedRange;
            fromAmino(object: _102.DescriptorProto_ReservedRangeAmino): _102.DescriptorProto_ReservedRange;
            toAmino(message: _102.DescriptorProto_ReservedRange): _102.DescriptorProto_ReservedRangeAmino;
            fromAminoMsg(object: _102.DescriptorProto_ReservedRangeAminoMsg): _102.DescriptorProto_ReservedRange;
            fromProtoMsg(message: _102.DescriptorProto_ReservedRangeProtoMsg): _102.DescriptorProto_ReservedRange;
            toProto(message: _102.DescriptorProto_ReservedRange): Uint8Array;
            toProtoMsg(message: _102.DescriptorProto_ReservedRange): _102.DescriptorProto_ReservedRangeProtoMsg;
        };
        ExtensionRangeOptions: {
            encode(message: _102.ExtensionRangeOptions, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number | undefined): _102.ExtensionRangeOptions;
            fromJSON(object: any): _102.ExtensionRangeOptions;
            toJSON(message: _102.ExtensionRangeOptions): unknown;
            fromPartial(object: Partial<_102.ExtensionRangeOptions>): _102.ExtensionRangeOptions;
            fromAmino(object: _102.ExtensionRangeOptionsAmino): _102.ExtensionRangeOptions;
            toAmino(message: _102.ExtensionRangeOptions): _102.ExtensionRangeOptionsAmino;
            fromAminoMsg(object: _102.ExtensionRangeOptionsAminoMsg): _102.ExtensionRangeOptions;
            fromProtoMsg(message: _102.ExtensionRangeOptionsProtoMsg): _102.ExtensionRangeOptions;
            toProto(message: _102.ExtensionRangeOptions): Uint8Array;
            toProtoMsg(message: _102.ExtensionRangeOptions): _102.ExtensionRangeOptionsProtoMsg;
        };
        FieldDescriptorProto: {
            encode(message: _102.FieldDescriptorProto, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number | undefined): _102.FieldDescriptorProto;
            fromJSON(object: any): _102.FieldDescriptorProto;
            toJSON(message: _102.FieldDescriptorProto): unknown;
            fromPartial(object: Partial<_102.FieldDescriptorProto>): _102.FieldDescriptorProto;
            fromAmino(object: _102.FieldDescriptorProtoAmino): _102.FieldDescriptorProto;
            toAmino(message: _102.FieldDescriptorProto): _102.FieldDescriptorProtoAmino;
            fromAminoMsg(object: _102.FieldDescriptorProtoAminoMsg): _102.FieldDescriptorProto;
            fromProtoMsg(message: _102.FieldDescriptorProtoProtoMsg): _102.FieldDescriptorProto;
            toProto(message: _102.FieldDescriptorProto): Uint8Array;
            toProtoMsg(message: _102.FieldDescriptorProto): _102.FieldDescriptorProtoProtoMsg;
        };
        OneofDescriptorProto: {
            encode(message: _102.OneofDescriptorProto, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number | undefined): _102.OneofDescriptorProto;
            fromJSON(object: any): _102.OneofDescriptorProto;
            toJSON(message: _102.OneofDescriptorProto): unknown;
            fromPartial(object: Partial<_102.OneofDescriptorProto>): _102.OneofDescriptorProto;
            fromAmino(object: _102.OneofDescriptorProtoAmino): _102.OneofDescriptorProto;
            toAmino(message: _102.OneofDescriptorProto): _102.OneofDescriptorProtoAmino;
            fromAminoMsg(object: _102.OneofDescriptorProtoAminoMsg): _102.OneofDescriptorProto;
            fromProtoMsg(message: _102.OneofDescriptorProtoProtoMsg): _102.OneofDescriptorProto;
            toProto(message: _102.OneofDescriptorProto): Uint8Array;
            toProtoMsg(message: _102.OneofDescriptorProto): _102.OneofDescriptorProtoProtoMsg;
        };
        EnumDescriptorProto: {
            encode(message: _102.EnumDescriptorProto, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number | undefined): _102.EnumDescriptorProto;
            fromJSON(object: any): _102.EnumDescriptorProto;
            toJSON(message: _102.EnumDescriptorProto): unknown;
            fromPartial(object: Partial<_102.EnumDescriptorProto>): _102.EnumDescriptorProto;
            fromAmino(object: _102.EnumDescriptorProtoAmino): _102.EnumDescriptorProto;
            toAmino(message: _102.EnumDescriptorProto): _102.EnumDescriptorProtoAmino;
            fromAminoMsg(object: _102.EnumDescriptorProtoAminoMsg): _102.EnumDescriptorProto;
            fromProtoMsg(message: _102.EnumDescriptorProtoProtoMsg): _102.EnumDescriptorProto;
            toProto(message: _102.EnumDescriptorProto): Uint8Array;
            toProtoMsg(message: _102.EnumDescriptorProto): _102.EnumDescriptorProtoProtoMsg;
        };
        EnumDescriptorProto_EnumReservedRange: {
            encode(message: _102.EnumDescriptorProto_EnumReservedRange, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number | undefined): _102.EnumDescriptorProto_EnumReservedRange;
            fromJSON(object: any): _102.EnumDescriptorProto_EnumReservedRange;
            toJSON(message: _102.EnumDescriptorProto_EnumReservedRange): unknown;
            fromPartial(object: Partial<_102.EnumDescriptorProto_EnumReservedRange>): _102.EnumDescriptorProto_EnumReservedRange;
            fromAmino(object: _102.EnumDescriptorProto_EnumReservedRangeAmino): _102.EnumDescriptorProto_EnumReservedRange;
            toAmino(message: _102.EnumDescriptorProto_EnumReservedRange): _102.EnumDescriptorProto_EnumReservedRangeAmino;
            fromAminoMsg(object: _102.EnumDescriptorProto_EnumReservedRangeAminoMsg): _102.EnumDescriptorProto_EnumReservedRange;
            fromProtoMsg(message: _102.EnumDescriptorProto_EnumReservedRangeProtoMsg): _102.EnumDescriptorProto_EnumReservedRange;
            toProto(message: _102.EnumDescriptorProto_EnumReservedRange): Uint8Array;
            toProtoMsg(message: _102.EnumDescriptorProto_EnumReservedRange): _102.EnumDescriptorProto_EnumReservedRangeProtoMsg;
        };
        EnumValueDescriptorProto: {
            encode(message: _102.EnumValueDescriptorProto, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number | undefined): _102.EnumValueDescriptorProto;
            fromJSON(object: any): _102.EnumValueDescriptorProto;
            toJSON(message: _102.EnumValueDescriptorProto): unknown;
            fromPartial(object: Partial<_102.EnumValueDescriptorProto>): _102.EnumValueDescriptorProto;
            fromAmino(object: _102.EnumValueDescriptorProtoAmino): _102.EnumValueDescriptorProto;
            toAmino(message: _102.EnumValueDescriptorProto): _102.EnumValueDescriptorProtoAmino;
            fromAminoMsg(object: _102.EnumValueDescriptorProtoAminoMsg): _102.EnumValueDescriptorProto;
            fromProtoMsg(message: _102.EnumValueDescriptorProtoProtoMsg): _102.EnumValueDescriptorProto;
            toProto(message: _102.EnumValueDescriptorProto): Uint8Array;
            toProtoMsg(message: _102.EnumValueDescriptorProto): _102.EnumValueDescriptorProtoProtoMsg;
        };
        ServiceDescriptorProto: {
            encode(message: _102.ServiceDescriptorProto, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number | undefined): _102.ServiceDescriptorProto;
            fromJSON(object: any): _102.ServiceDescriptorProto;
            toJSON(message: _102.ServiceDescriptorProto): unknown;
            fromPartial(object: Partial<_102.ServiceDescriptorProto>): _102.ServiceDescriptorProto;
            fromAmino(object: _102.ServiceDescriptorProtoAmino): _102.ServiceDescriptorProto;
            toAmino(message: _102.ServiceDescriptorProto): _102.ServiceDescriptorProtoAmino;
            fromAminoMsg(object: _102.ServiceDescriptorProtoAminoMsg): _102.ServiceDescriptorProto;
            fromProtoMsg(message: _102.ServiceDescriptorProtoProtoMsg): _102.ServiceDescriptorProto;
            toProto(message: _102.ServiceDescriptorProto): Uint8Array;
            toProtoMsg(message: _102.ServiceDescriptorProto): _102.ServiceDescriptorProtoProtoMsg;
        };
        MethodDescriptorProto: {
            encode(message: _102.MethodDescriptorProto, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number | undefined): _102.MethodDescriptorProto;
            fromJSON(object: any): _102.MethodDescriptorProto;
            toJSON(message: _102.MethodDescriptorProto): unknown;
            fromPartial(object: Partial<_102.MethodDescriptorProto>): _102.MethodDescriptorProto;
            fromAmino(object: _102.MethodDescriptorProtoAmino): _102.MethodDescriptorProto;
            toAmino(message: _102.MethodDescriptorProto): _102.MethodDescriptorProtoAmino;
            fromAminoMsg(object: _102.MethodDescriptorProtoAminoMsg): _102.MethodDescriptorProto;
            fromProtoMsg(message: _102.MethodDescriptorProtoProtoMsg): _102.MethodDescriptorProto;
            toProto(message: _102.MethodDescriptorProto): Uint8Array;
            toProtoMsg(message: _102.MethodDescriptorProto): _102.MethodDescriptorProtoProtoMsg;
        };
        FileOptions: {
            encode(message: _102.FileOptions, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number | undefined): _102.FileOptions;
            fromJSON(object: any): _102.FileOptions;
            toJSON(message: _102.FileOptions): unknown;
            fromPartial(object: Partial<_102.FileOptions>): _102.FileOptions;
            fromAmino(object: _102.FileOptionsAmino): _102.FileOptions;
            toAmino(message: _102.FileOptions): _102.FileOptionsAmino;
            fromAminoMsg(object: _102.FileOptionsAminoMsg): _102.FileOptions;
            fromProtoMsg(message: _102.FileOptionsProtoMsg): _102.FileOptions;
            toProto(message: _102.FileOptions): Uint8Array;
            toProtoMsg(message: _102.FileOptions): _102.FileOptionsProtoMsg;
        };
        MessageOptions: {
            encode(message: _102.MessageOptions, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number | undefined): _102.MessageOptions;
            fromJSON(object: any): _102.MessageOptions;
            toJSON(message: _102.MessageOptions): unknown;
            fromPartial(object: Partial<_102.MessageOptions>): _102.MessageOptions;
            fromAmino(object: _102.MessageOptionsAmino): _102.MessageOptions;
            toAmino(message: _102.MessageOptions): _102.MessageOptionsAmino;
            fromAminoMsg(object: _102.MessageOptionsAminoMsg): _102.MessageOptions;
            fromProtoMsg(message: _102.MessageOptionsProtoMsg): _102.MessageOptions;
            toProto(message: _102.MessageOptions): Uint8Array;
            toProtoMsg(message: _102.MessageOptions): _102.MessageOptionsProtoMsg;
        };
        FieldOptions: {
            encode(message: _102.FieldOptions, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number | undefined): _102.FieldOptions;
            fromJSON(object: any): _102.FieldOptions;
            toJSON(message: _102.FieldOptions): unknown;
            fromPartial(object: Partial<_102.FieldOptions>): _102.FieldOptions;
            fromAmino(object: _102.FieldOptionsAmino): _102.FieldOptions;
            toAmino(message: _102.FieldOptions): _102.FieldOptionsAmino;
            fromAminoMsg(object: _102.FieldOptionsAminoMsg): _102.FieldOptions;
            fromProtoMsg(message: _102.FieldOptionsProtoMsg): _102.FieldOptions;
            toProto(message: _102.FieldOptions): Uint8Array;
            toProtoMsg(message: _102.FieldOptions): _102.FieldOptionsProtoMsg;
        };
        OneofOptions: {
            encode(message: _102.OneofOptions, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number | undefined): _102.OneofOptions;
            fromJSON(object: any): _102.OneofOptions;
            toJSON(message: _102.OneofOptions): unknown;
            fromPartial(object: Partial<_102.OneofOptions>): _102.OneofOptions;
            fromAmino(object: _102.OneofOptionsAmino): _102.OneofOptions;
            toAmino(message: _102.OneofOptions): _102.OneofOptionsAmino;
            fromAminoMsg(object: _102.OneofOptionsAminoMsg): _102.OneofOptions;
            fromProtoMsg(message: _102.OneofOptionsProtoMsg): _102.OneofOptions;
            toProto(message: _102.OneofOptions): Uint8Array;
            toProtoMsg(message: _102.OneofOptions): _102.OneofOptionsProtoMsg;
        };
        EnumOptions: {
            encode(message: _102.EnumOptions, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number | undefined): _102.EnumOptions;
            fromJSON(object: any): _102.EnumOptions;
            toJSON(message: _102.EnumOptions): unknown;
            fromPartial(object: Partial<_102.EnumOptions>): _102.EnumOptions;
            fromAmino(object: _102.EnumOptionsAmino): _102.EnumOptions;
            toAmino(message: _102.EnumOptions): _102.EnumOptionsAmino;
            fromAminoMsg(object: _102.EnumOptionsAminoMsg): _102.EnumOptions;
            fromProtoMsg(message: _102.EnumOptionsProtoMsg): _102.EnumOptions;
            toProto(message: _102.EnumOptions): Uint8Array;
            toProtoMsg(message: _102.EnumOptions): _102.EnumOptionsProtoMsg;
        };
        EnumValueOptions: {
            encode(message: _102.EnumValueOptions, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number | undefined): _102.EnumValueOptions;
            fromJSON(object: any): _102.EnumValueOptions;
            toJSON(message: _102.EnumValueOptions): unknown;
            fromPartial(object: Partial<_102.EnumValueOptions>): _102.EnumValueOptions;
            fromAmino(object: _102.EnumValueOptionsAmino): _102.EnumValueOptions;
            toAmino(message: _102.EnumValueOptions): _102.EnumValueOptionsAmino;
            fromAminoMsg(object: _102.EnumValueOptionsAminoMsg): _102.EnumValueOptions;
            fromProtoMsg(message: _102.EnumValueOptionsProtoMsg): _102.EnumValueOptions;
            toProto(message: _102.EnumValueOptions): Uint8Array;
            toProtoMsg(message: _102.EnumValueOptions): _102.EnumValueOptionsProtoMsg;
        };
        ServiceOptions: {
            encode(message: _102.ServiceOptions, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number | undefined): _102.ServiceOptions;
            fromJSON(object: any): _102.ServiceOptions;
            toJSON(message: _102.ServiceOptions): unknown;
            fromPartial(object: Partial<_102.ServiceOptions>): _102.ServiceOptions;
            fromAmino(object: _102.ServiceOptionsAmino): _102.ServiceOptions;
            toAmino(message: _102.ServiceOptions): _102.ServiceOptionsAmino;
            fromAminoMsg(object: _102.ServiceOptionsAminoMsg): _102.ServiceOptions;
            fromProtoMsg(message: _102.ServiceOptionsProtoMsg): _102.ServiceOptions;
            toProto(message: _102.ServiceOptions): Uint8Array;
            toProtoMsg(message: _102.ServiceOptions): _102.ServiceOptionsProtoMsg;
        };
        MethodOptions: {
            encode(message: _102.MethodOptions, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number | undefined): _102.MethodOptions;
            fromJSON(object: any): _102.MethodOptions;
            toJSON(message: _102.MethodOptions): unknown;
            fromPartial(object: Partial<_102.MethodOptions>): _102.MethodOptions;
            fromAmino(object: _102.MethodOptionsAmino): _102.MethodOptions;
            toAmino(message: _102.MethodOptions): _102.MethodOptionsAmino;
            fromAminoMsg(object: _102.MethodOptionsAminoMsg): _102.MethodOptions;
            fromProtoMsg(message: _102.MethodOptionsProtoMsg): _102.MethodOptions;
            toProto(message: _102.MethodOptions): Uint8Array;
            toProtoMsg(message: _102.MethodOptions): _102.MethodOptionsProtoMsg;
        };
        UninterpretedOption: {
            encode(message: _102.UninterpretedOption, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number | undefined): _102.UninterpretedOption;
            fromJSON(object: any): _102.UninterpretedOption;
            toJSON(message: _102.UninterpretedOption): unknown;
            fromPartial(object: Partial<_102.UninterpretedOption>): _102.UninterpretedOption;
            fromAmino(object: _102.UninterpretedOptionAmino): _102.UninterpretedOption;
            toAmino(message: _102.UninterpretedOption): _102.UninterpretedOptionAmino;
            fromAminoMsg(object: _102.UninterpretedOptionAminoMsg): _102.UninterpretedOption;
            fromProtoMsg(message: _102.UninterpretedOptionProtoMsg): _102.UninterpretedOption;
            toProto(message: _102.UninterpretedOption): Uint8Array;
            toProtoMsg(message: _102.UninterpretedOption): _102.UninterpretedOptionProtoMsg;
        };
        UninterpretedOption_NamePart: {
            encode(message: _102.UninterpretedOption_NamePart, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number | undefined): _102.UninterpretedOption_NamePart;
            fromJSON(object: any): _102.UninterpretedOption_NamePart;
            toJSON(message: _102.UninterpretedOption_NamePart): unknown;
            fromPartial(object: Partial<_102.UninterpretedOption_NamePart>): _102.UninterpretedOption_NamePart;
            fromAmino(object: _102.UninterpretedOption_NamePartAmino): _102.UninterpretedOption_NamePart;
            toAmino(message: _102.UninterpretedOption_NamePart): _102.UninterpretedOption_NamePartAmino;
            fromAminoMsg(object: _102.UninterpretedOption_NamePartAminoMsg): _102.UninterpretedOption_NamePart;
            fromProtoMsg(message: _102.UninterpretedOption_NamePartProtoMsg): _102.UninterpretedOption_NamePart;
            toProto(message: _102.UninterpretedOption_NamePart): Uint8Array;
            toProtoMsg(message: _102.UninterpretedOption_NamePart): _102.UninterpretedOption_NamePartProtoMsg;
        };
        SourceCodeInfo: {
            encode(message: _102.SourceCodeInfo, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number | undefined): _102.SourceCodeInfo;
            fromJSON(object: any): _102.SourceCodeInfo;
            toJSON(message: _102.SourceCodeInfo): unknown;
            fromPartial(object: Partial<_102.SourceCodeInfo>): _102.SourceCodeInfo;
            fromAmino(object: _102.SourceCodeInfoAmino): _102.SourceCodeInfo;
            toAmino(message: _102.SourceCodeInfo): _102.SourceCodeInfoAmino;
            fromAminoMsg(object: _102.SourceCodeInfoAminoMsg): _102.SourceCodeInfo;
            fromProtoMsg(message: _102.SourceCodeInfoProtoMsg): _102.SourceCodeInfo;
            toProto(message: _102.SourceCodeInfo): Uint8Array;
            toProtoMsg(message: _102.SourceCodeInfo): _102.SourceCodeInfoProtoMsg;
        };
        SourceCodeInfo_Location: {
            encode(message: _102.SourceCodeInfo_Location, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number | undefined): _102.SourceCodeInfo_Location;
            fromJSON(object: any): _102.SourceCodeInfo_Location;
            toJSON(message: _102.SourceCodeInfo_Location): unknown;
            fromPartial(object: Partial<_102.SourceCodeInfo_Location>): _102.SourceCodeInfo_Location;
            fromAmino(object: _102.SourceCodeInfo_LocationAmino): _102.SourceCodeInfo_Location;
            toAmino(message: _102.SourceCodeInfo_Location): _102.SourceCodeInfo_LocationAmino;
            fromAminoMsg(object: _102.SourceCodeInfo_LocationAminoMsg): _102.SourceCodeInfo_Location;
            fromProtoMsg(message: _102.SourceCodeInfo_LocationProtoMsg): _102.SourceCodeInfo_Location;
            toProto(message: _102.SourceCodeInfo_Location): Uint8Array;
            toProtoMsg(message: _102.SourceCodeInfo_Location): _102.SourceCodeInfo_LocationProtoMsg;
        };
        GeneratedCodeInfo: {
            encode(message: _102.GeneratedCodeInfo, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number | undefined): _102.GeneratedCodeInfo;
            fromJSON(object: any): _102.GeneratedCodeInfo;
            toJSON(message: _102.GeneratedCodeInfo): unknown;
            fromPartial(object: Partial<_102.GeneratedCodeInfo>): _102.GeneratedCodeInfo;
            fromAmino(object: _102.GeneratedCodeInfoAmino): _102.GeneratedCodeInfo;
            toAmino(message: _102.GeneratedCodeInfo): _102.GeneratedCodeInfoAmino;
            fromAminoMsg(object: _102.GeneratedCodeInfoAminoMsg): _102.GeneratedCodeInfo;
            fromProtoMsg(message: _102.GeneratedCodeInfoProtoMsg): _102.GeneratedCodeInfo;
            toProto(message: _102.GeneratedCodeInfo): Uint8Array;
            toProtoMsg(message: _102.GeneratedCodeInfo): _102.GeneratedCodeInfoProtoMsg;
        };
        GeneratedCodeInfo_Annotation: {
            encode(message: _102.GeneratedCodeInfo_Annotation, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number | undefined): _102.GeneratedCodeInfo_Annotation;
            fromJSON(object: any): _102.GeneratedCodeInfo_Annotation;
            toJSON(message: _102.GeneratedCodeInfo_Annotation): unknown;
            fromPartial(object: Partial<_102.GeneratedCodeInfo_Annotation>): _102.GeneratedCodeInfo_Annotation;
            fromAmino(object: _102.GeneratedCodeInfo_AnnotationAmino): _102.GeneratedCodeInfo_Annotation;
            toAmino(message: _102.GeneratedCodeInfo_Annotation): _102.GeneratedCodeInfo_AnnotationAmino;
            fromAminoMsg(object: _102.GeneratedCodeInfo_AnnotationAminoMsg): _102.GeneratedCodeInfo_Annotation;
            fromProtoMsg(message: _102.GeneratedCodeInfo_AnnotationProtoMsg): _102.GeneratedCodeInfo_Annotation;
            toProto(message: _102.GeneratedCodeInfo_Annotation): Uint8Array;
            toProtoMsg(message: _102.GeneratedCodeInfo_Annotation): _102.GeneratedCodeInfo_AnnotationProtoMsg;
        };
        Any: {
            encode(message: _101.Any, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number | undefined): _101.Any;
            fromJSON(object: any): _101.Any;
            toJSON(message: _101.Any): unknown;
            fromPartial(object: Partial<_101.Any>): _101.Any;
            fromAmino(object: _101.AnyAmino): _101.Any;
            toAmino(message: _101.Any): _101.AnyAmino;
            fromAminoMsg(object: _101.AnyAminoMsg): _101.Any;
            fromProtoMsg(message: _101.AnyProtoMsg): _101.Any;
            toProto(message: _101.Any): Uint8Array;
            toProtoMsg(message: _101.Any): _101.AnyProtoMsg;
        };
    };
}
