import * as _100 from "./api/http";
import * as _101 from "./protobuf/descriptor";
import * as _102 from "./protobuf/any";
import * as _103 from "./protobuf/timestamp";
import * as _104 from "./protobuf/duration";
export declare namespace google {
    const api: {
        Http: {
            typeUrl: string;
            encode(message: _100.Http, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number | undefined): _100.Http;
            fromJSON(object: any): _100.Http;
            toJSON(message: _100.Http): unknown;
            fromPartial(object: Partial<_100.Http>): _100.Http;
            fromAmino(object: _100.HttpAmino): _100.Http;
            toAmino(message: _100.Http): _100.HttpAmino;
            fromAminoMsg(object: _100.HttpAminoMsg): _100.Http;
            fromProtoMsg(message: _100.HttpProtoMsg): _100.Http;
            toProto(message: _100.Http): Uint8Array;
            toProtoMsg(message: _100.Http): _100.HttpProtoMsg;
        };
        HttpRule: {
            typeUrl: string;
            encode(message: _100.HttpRule, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number | undefined): _100.HttpRule;
            fromJSON(object: any): _100.HttpRule;
            toJSON(message: _100.HttpRule): unknown;
            fromPartial(object: Partial<_100.HttpRule>): _100.HttpRule;
            fromAmino(object: _100.HttpRuleAmino): _100.HttpRule;
            toAmino(message: _100.HttpRule): _100.HttpRuleAmino;
            fromAminoMsg(object: _100.HttpRuleAminoMsg): _100.HttpRule;
            fromProtoMsg(message: _100.HttpRuleProtoMsg): _100.HttpRule;
            toProto(message: _100.HttpRule): Uint8Array;
            toProtoMsg(message: _100.HttpRule): _100.HttpRuleProtoMsg;
        };
        CustomHttpPattern: {
            typeUrl: string;
            encode(message: _100.CustomHttpPattern, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number | undefined): _100.CustomHttpPattern;
            fromJSON(object: any): _100.CustomHttpPattern;
            toJSON(message: _100.CustomHttpPattern): unknown;
            fromPartial(object: Partial<_100.CustomHttpPattern>): _100.CustomHttpPattern;
            fromAmino(object: _100.CustomHttpPatternAmino): _100.CustomHttpPattern;
            toAmino(message: _100.CustomHttpPattern): _100.CustomHttpPatternAmino;
            fromAminoMsg(object: _100.CustomHttpPatternAminoMsg): _100.CustomHttpPattern;
            fromProtoMsg(message: _100.CustomHttpPatternProtoMsg): _100.CustomHttpPattern;
            toProto(message: _100.CustomHttpPattern): Uint8Array;
            toProtoMsg(message: _100.CustomHttpPattern): _100.CustomHttpPatternProtoMsg;
        };
    };
    const protobuf: {
        Duration: {
            typeUrl: string;
            encode(message: _104.Duration, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number | undefined): _104.Duration;
            fromJSON(object: any): _104.Duration;
            toJSON(message: _104.Duration): unknown;
            fromPartial(object: Partial<_104.Duration>): _104.Duration;
            fromAmino(object: string): _104.Duration;
            toAmino(message: _104.Duration): string;
            fromAminoMsg(object: _104.DurationAminoMsg): _104.Duration;
            fromProtoMsg(message: _104.DurationProtoMsg): _104.Duration;
            toProto(message: _104.Duration): Uint8Array;
            toProtoMsg(message: _104.Duration): _104.DurationProtoMsg;
        };
        Timestamp: {
            typeUrl: string;
            encode(message: _103.Timestamp, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number | undefined): _103.Timestamp;
            fromJSON(object: any): _103.Timestamp;
            toJSON(message: _103.Timestamp): unknown;
            fromPartial(object: Partial<_103.Timestamp>): _103.Timestamp;
            fromAmino(object: string): _103.Timestamp;
            toAmino(message: _103.Timestamp): string;
            fromAminoMsg(object: _103.TimestampAminoMsg): _103.Timestamp;
            fromProtoMsg(message: _103.TimestampProtoMsg): _103.Timestamp;
            toProto(message: _103.Timestamp): Uint8Array;
            toProtoMsg(message: _103.Timestamp): _103.TimestampProtoMsg;
        };
        Any: {
            typeUrl: string;
            encode(message: _102.Any, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number | undefined): _102.Any;
            fromJSON(object: any): _102.Any;
            toJSON(message: _102.Any): unknown;
            fromPartial(object: Partial<_102.Any>): _102.Any;
            fromAmino(object: _102.AnyAmino): _102.Any;
            toAmino(message: _102.Any): _102.AnyAmino;
            fromAminoMsg(object: _102.AnyAminoMsg): _102.Any;
            fromProtoMsg(message: _102.AnyProtoMsg): _102.Any;
            toProto(message: _102.Any): Uint8Array;
            toProtoMsg(message: _102.Any): _102.AnyProtoMsg;
        };
        fieldDescriptorProto_TypeFromJSON(object: any): _101.FieldDescriptorProto_Type;
        fieldDescriptorProto_TypeToJSON(object: _101.FieldDescriptorProto_Type): string;
        fieldDescriptorProto_LabelFromJSON(object: any): _101.FieldDescriptorProto_Label;
        fieldDescriptorProto_LabelToJSON(object: _101.FieldDescriptorProto_Label): string;
        fileOptions_OptimizeModeFromJSON(object: any): _101.FileOptions_OptimizeMode;
        fileOptions_OptimizeModeToJSON(object: _101.FileOptions_OptimizeMode): string;
        fieldOptions_CTypeFromJSON(object: any): _101.FieldOptions_CType;
        fieldOptions_CTypeToJSON(object: _101.FieldOptions_CType): string;
        fieldOptions_JSTypeFromJSON(object: any): _101.FieldOptions_JSType;
        fieldOptions_JSTypeToJSON(object: _101.FieldOptions_JSType): string;
        methodOptions_IdempotencyLevelFromJSON(object: any): _101.MethodOptions_IdempotencyLevel;
        methodOptions_IdempotencyLevelToJSON(object: _101.MethodOptions_IdempotencyLevel): string;
        FieldDescriptorProto_Type: typeof _101.FieldDescriptorProto_Type;
        FieldDescriptorProto_TypeSDKType: typeof _101.FieldDescriptorProto_Type;
        FieldDescriptorProto_TypeAmino: typeof _101.FieldDescriptorProto_Type;
        FieldDescriptorProto_Label: typeof _101.FieldDescriptorProto_Label;
        FieldDescriptorProto_LabelSDKType: typeof _101.FieldDescriptorProto_Label;
        FieldDescriptorProto_LabelAmino: typeof _101.FieldDescriptorProto_Label;
        FileOptions_OptimizeMode: typeof _101.FileOptions_OptimizeMode;
        FileOptions_OptimizeModeSDKType: typeof _101.FileOptions_OptimizeMode;
        FileOptions_OptimizeModeAmino: typeof _101.FileOptions_OptimizeMode;
        FieldOptions_CType: typeof _101.FieldOptions_CType;
        FieldOptions_CTypeSDKType: typeof _101.FieldOptions_CType;
        FieldOptions_CTypeAmino: typeof _101.FieldOptions_CType;
        FieldOptions_JSType: typeof _101.FieldOptions_JSType;
        FieldOptions_JSTypeSDKType: typeof _101.FieldOptions_JSType;
        FieldOptions_JSTypeAmino: typeof _101.FieldOptions_JSType;
        MethodOptions_IdempotencyLevel: typeof _101.MethodOptions_IdempotencyLevel;
        MethodOptions_IdempotencyLevelSDKType: typeof _101.MethodOptions_IdempotencyLevel;
        MethodOptions_IdempotencyLevelAmino: typeof _101.MethodOptions_IdempotencyLevel;
        FileDescriptorSet: {
            typeUrl: string;
            encode(message: _101.FileDescriptorSet, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number | undefined): _101.FileDescriptorSet;
            fromJSON(object: any): _101.FileDescriptorSet;
            toJSON(message: _101.FileDescriptorSet): unknown;
            fromPartial(object: Partial<_101.FileDescriptorSet>): _101.FileDescriptorSet;
            fromAmino(object: _101.FileDescriptorSetAmino): _101.FileDescriptorSet;
            toAmino(message: _101.FileDescriptorSet): _101.FileDescriptorSetAmino;
            fromAminoMsg(object: _101.FileDescriptorSetAminoMsg): _101.FileDescriptorSet;
            fromProtoMsg(message: _101.FileDescriptorSetProtoMsg): _101.FileDescriptorSet;
            toProto(message: _101.FileDescriptorSet): Uint8Array;
            toProtoMsg(message: _101.FileDescriptorSet): _101.FileDescriptorSetProtoMsg;
        };
        FileDescriptorProto: {
            typeUrl: string;
            encode(message: _101.FileDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number | undefined): _101.FileDescriptorProto;
            fromJSON(object: any): _101.FileDescriptorProto;
            toJSON(message: _101.FileDescriptorProto): unknown;
            fromPartial(object: Partial<_101.FileDescriptorProto>): _101.FileDescriptorProto;
            fromAmino(object: _101.FileDescriptorProtoAmino): _101.FileDescriptorProto;
            toAmino(message: _101.FileDescriptorProto): _101.FileDescriptorProtoAmino;
            fromAminoMsg(object: _101.FileDescriptorProtoAminoMsg): _101.FileDescriptorProto;
            fromProtoMsg(message: _101.FileDescriptorProtoProtoMsg): _101.FileDescriptorProto;
            toProto(message: _101.FileDescriptorProto): Uint8Array;
            toProtoMsg(message: _101.FileDescriptorProto): _101.FileDescriptorProtoProtoMsg;
        };
        DescriptorProto: {
            typeUrl: string;
            encode(message: _101.DescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number | undefined): _101.DescriptorProto;
            fromJSON(object: any): _101.DescriptorProto;
            toJSON(message: _101.DescriptorProto): unknown;
            fromPartial(object: Partial<_101.DescriptorProto>): _101.DescriptorProto;
            fromAmino(object: _101.DescriptorProtoAmino): _101.DescriptorProto;
            toAmino(message: _101.DescriptorProto): _101.DescriptorProtoAmino;
            fromAminoMsg(object: _101.DescriptorProtoAminoMsg): _101.DescriptorProto;
            fromProtoMsg(message: _101.DescriptorProtoProtoMsg): _101.DescriptorProto;
            toProto(message: _101.DescriptorProto): Uint8Array;
            toProtoMsg(message: _101.DescriptorProto): _101.DescriptorProtoProtoMsg;
        };
        DescriptorProto_ExtensionRange: {
            typeUrl: string;
            encode(message: _101.DescriptorProto_ExtensionRange, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number | undefined): _101.DescriptorProto_ExtensionRange;
            fromJSON(object: any): _101.DescriptorProto_ExtensionRange;
            toJSON(message: _101.DescriptorProto_ExtensionRange): unknown;
            fromPartial(object: Partial<_101.DescriptorProto_ExtensionRange>): _101.DescriptorProto_ExtensionRange;
            fromAmino(object: _101.DescriptorProto_ExtensionRangeAmino): _101.DescriptorProto_ExtensionRange;
            toAmino(message: _101.DescriptorProto_ExtensionRange): _101.DescriptorProto_ExtensionRangeAmino;
            fromAminoMsg(object: _101.DescriptorProto_ExtensionRangeAminoMsg): _101.DescriptorProto_ExtensionRange;
            fromProtoMsg(message: _101.DescriptorProto_ExtensionRangeProtoMsg): _101.DescriptorProto_ExtensionRange;
            toProto(message: _101.DescriptorProto_ExtensionRange): Uint8Array;
            toProtoMsg(message: _101.DescriptorProto_ExtensionRange): _101.DescriptorProto_ExtensionRangeProtoMsg;
        };
        DescriptorProto_ReservedRange: {
            typeUrl: string;
            encode(message: _101.DescriptorProto_ReservedRange, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number | undefined): _101.DescriptorProto_ReservedRange;
            fromJSON(object: any): _101.DescriptorProto_ReservedRange;
            toJSON(message: _101.DescriptorProto_ReservedRange): unknown;
            fromPartial(object: Partial<_101.DescriptorProto_ReservedRange>): _101.DescriptorProto_ReservedRange;
            fromAmino(object: _101.DescriptorProto_ReservedRangeAmino): _101.DescriptorProto_ReservedRange;
            toAmino(message: _101.DescriptorProto_ReservedRange): _101.DescriptorProto_ReservedRangeAmino;
            fromAminoMsg(object: _101.DescriptorProto_ReservedRangeAminoMsg): _101.DescriptorProto_ReservedRange;
            fromProtoMsg(message: _101.DescriptorProto_ReservedRangeProtoMsg): _101.DescriptorProto_ReservedRange;
            toProto(message: _101.DescriptorProto_ReservedRange): Uint8Array;
            toProtoMsg(message: _101.DescriptorProto_ReservedRange): _101.DescriptorProto_ReservedRangeProtoMsg;
        };
        ExtensionRangeOptions: {
            typeUrl: string;
            encode(message: _101.ExtensionRangeOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number | undefined): _101.ExtensionRangeOptions;
            fromJSON(object: any): _101.ExtensionRangeOptions;
            toJSON(message: _101.ExtensionRangeOptions): unknown;
            fromPartial(object: Partial<_101.ExtensionRangeOptions>): _101.ExtensionRangeOptions;
            fromAmino(object: _101.ExtensionRangeOptionsAmino): _101.ExtensionRangeOptions;
            toAmino(message: _101.ExtensionRangeOptions): _101.ExtensionRangeOptionsAmino;
            fromAminoMsg(object: _101.ExtensionRangeOptionsAminoMsg): _101.ExtensionRangeOptions;
            fromProtoMsg(message: _101.ExtensionRangeOptionsProtoMsg): _101.ExtensionRangeOptions;
            toProto(message: _101.ExtensionRangeOptions): Uint8Array;
            toProtoMsg(message: _101.ExtensionRangeOptions): _101.ExtensionRangeOptionsProtoMsg;
        };
        FieldDescriptorProto: {
            typeUrl: string;
            encode(message: _101.FieldDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number | undefined): _101.FieldDescriptorProto;
            fromJSON(object: any): _101.FieldDescriptorProto;
            toJSON(message: _101.FieldDescriptorProto): unknown;
            fromPartial(object: Partial<_101.FieldDescriptorProto>): _101.FieldDescriptorProto;
            fromAmino(object: _101.FieldDescriptorProtoAmino): _101.FieldDescriptorProto;
            toAmino(message: _101.FieldDescriptorProto): _101.FieldDescriptorProtoAmino;
            fromAminoMsg(object: _101.FieldDescriptorProtoAminoMsg): _101.FieldDescriptorProto;
            fromProtoMsg(message: _101.FieldDescriptorProtoProtoMsg): _101.FieldDescriptorProto;
            toProto(message: _101.FieldDescriptorProto): Uint8Array;
            toProtoMsg(message: _101.FieldDescriptorProto): _101.FieldDescriptorProtoProtoMsg;
        };
        OneofDescriptorProto: {
            typeUrl: string;
            encode(message: _101.OneofDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number | undefined): _101.OneofDescriptorProto;
            fromJSON(object: any): _101.OneofDescriptorProto;
            toJSON(message: _101.OneofDescriptorProto): unknown;
            fromPartial(object: Partial<_101.OneofDescriptorProto>): _101.OneofDescriptorProto;
            fromAmino(object: _101.OneofDescriptorProtoAmino): _101.OneofDescriptorProto;
            toAmino(message: _101.OneofDescriptorProto): _101.OneofDescriptorProtoAmino;
            fromAminoMsg(object: _101.OneofDescriptorProtoAminoMsg): _101.OneofDescriptorProto;
            fromProtoMsg(message: _101.OneofDescriptorProtoProtoMsg): _101.OneofDescriptorProto;
            toProto(message: _101.OneofDescriptorProto): Uint8Array;
            toProtoMsg(message: _101.OneofDescriptorProto): _101.OneofDescriptorProtoProtoMsg;
        };
        EnumDescriptorProto: {
            typeUrl: string;
            encode(message: _101.EnumDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number | undefined): _101.EnumDescriptorProto;
            fromJSON(object: any): _101.EnumDescriptorProto;
            toJSON(message: _101.EnumDescriptorProto): unknown;
            fromPartial(object: Partial<_101.EnumDescriptorProto>): _101.EnumDescriptorProto;
            fromAmino(object: _101.EnumDescriptorProtoAmino): _101.EnumDescriptorProto;
            toAmino(message: _101.EnumDescriptorProto): _101.EnumDescriptorProtoAmino;
            fromAminoMsg(object: _101.EnumDescriptorProtoAminoMsg): _101.EnumDescriptorProto;
            fromProtoMsg(message: _101.EnumDescriptorProtoProtoMsg): _101.EnumDescriptorProto;
            toProto(message: _101.EnumDescriptorProto): Uint8Array;
            toProtoMsg(message: _101.EnumDescriptorProto): _101.EnumDescriptorProtoProtoMsg;
        };
        EnumDescriptorProto_EnumReservedRange: {
            typeUrl: string;
            encode(message: _101.EnumDescriptorProto_EnumReservedRange, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number | undefined): _101.EnumDescriptorProto_EnumReservedRange;
            fromJSON(object: any): _101.EnumDescriptorProto_EnumReservedRange;
            toJSON(message: _101.EnumDescriptorProto_EnumReservedRange): unknown;
            fromPartial(object: Partial<_101.EnumDescriptorProto_EnumReservedRange>): _101.EnumDescriptorProto_EnumReservedRange;
            fromAmino(object: _101.EnumDescriptorProto_EnumReservedRangeAmino): _101.EnumDescriptorProto_EnumReservedRange;
            toAmino(message: _101.EnumDescriptorProto_EnumReservedRange): _101.EnumDescriptorProto_EnumReservedRangeAmino;
            fromAminoMsg(object: _101.EnumDescriptorProto_EnumReservedRangeAminoMsg): _101.EnumDescriptorProto_EnumReservedRange;
            fromProtoMsg(message: _101.EnumDescriptorProto_EnumReservedRangeProtoMsg): _101.EnumDescriptorProto_EnumReservedRange;
            toProto(message: _101.EnumDescriptorProto_EnumReservedRange): Uint8Array;
            toProtoMsg(message: _101.EnumDescriptorProto_EnumReservedRange): _101.EnumDescriptorProto_EnumReservedRangeProtoMsg;
        };
        EnumValueDescriptorProto: {
            typeUrl: string;
            encode(message: _101.EnumValueDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number | undefined): _101.EnumValueDescriptorProto;
            fromJSON(object: any): _101.EnumValueDescriptorProto;
            toJSON(message: _101.EnumValueDescriptorProto): unknown;
            fromPartial(object: Partial<_101.EnumValueDescriptorProto>): _101.EnumValueDescriptorProto;
            fromAmino(object: _101.EnumValueDescriptorProtoAmino): _101.EnumValueDescriptorProto;
            toAmino(message: _101.EnumValueDescriptorProto): _101.EnumValueDescriptorProtoAmino;
            fromAminoMsg(object: _101.EnumValueDescriptorProtoAminoMsg): _101.EnumValueDescriptorProto;
            fromProtoMsg(message: _101.EnumValueDescriptorProtoProtoMsg): _101.EnumValueDescriptorProto;
            toProto(message: _101.EnumValueDescriptorProto): Uint8Array;
            toProtoMsg(message: _101.EnumValueDescriptorProto): _101.EnumValueDescriptorProtoProtoMsg;
        };
        ServiceDescriptorProto: {
            typeUrl: string;
            encode(message: _101.ServiceDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number | undefined): _101.ServiceDescriptorProto;
            fromJSON(object: any): _101.ServiceDescriptorProto;
            toJSON(message: _101.ServiceDescriptorProto): unknown;
            fromPartial(object: Partial<_101.ServiceDescriptorProto>): _101.ServiceDescriptorProto;
            fromAmino(object: _101.ServiceDescriptorProtoAmino): _101.ServiceDescriptorProto;
            toAmino(message: _101.ServiceDescriptorProto): _101.ServiceDescriptorProtoAmino;
            fromAminoMsg(object: _101.ServiceDescriptorProtoAminoMsg): _101.ServiceDescriptorProto;
            fromProtoMsg(message: _101.ServiceDescriptorProtoProtoMsg): _101.ServiceDescriptorProto;
            toProto(message: _101.ServiceDescriptorProto): Uint8Array;
            toProtoMsg(message: _101.ServiceDescriptorProto): _101.ServiceDescriptorProtoProtoMsg;
        };
        MethodDescriptorProto: {
            typeUrl: string;
            encode(message: _101.MethodDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number | undefined): _101.MethodDescriptorProto;
            fromJSON(object: any): _101.MethodDescriptorProto;
            toJSON(message: _101.MethodDescriptorProto): unknown;
            fromPartial(object: Partial<_101.MethodDescriptorProto>): _101.MethodDescriptorProto;
            fromAmino(object: _101.MethodDescriptorProtoAmino): _101.MethodDescriptorProto;
            toAmino(message: _101.MethodDescriptorProto): _101.MethodDescriptorProtoAmino;
            fromAminoMsg(object: _101.MethodDescriptorProtoAminoMsg): _101.MethodDescriptorProto;
            fromProtoMsg(message: _101.MethodDescriptorProtoProtoMsg): _101.MethodDescriptorProto;
            toProto(message: _101.MethodDescriptorProto): Uint8Array;
            toProtoMsg(message: _101.MethodDescriptorProto): _101.MethodDescriptorProtoProtoMsg;
        };
        FileOptions: {
            typeUrl: string;
            encode(message: _101.FileOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number | undefined): _101.FileOptions;
            fromJSON(object: any): _101.FileOptions;
            toJSON(message: _101.FileOptions): unknown;
            fromPartial(object: Partial<_101.FileOptions>): _101.FileOptions;
            fromAmino(object: _101.FileOptionsAmino): _101.FileOptions;
            toAmino(message: _101.FileOptions): _101.FileOptionsAmino;
            fromAminoMsg(object: _101.FileOptionsAminoMsg): _101.FileOptions;
            fromProtoMsg(message: _101.FileOptionsProtoMsg): _101.FileOptions;
            toProto(message: _101.FileOptions): Uint8Array;
            toProtoMsg(message: _101.FileOptions): _101.FileOptionsProtoMsg;
        };
        MessageOptions: {
            typeUrl: string;
            encode(message: _101.MessageOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number | undefined): _101.MessageOptions;
            fromJSON(object: any): _101.MessageOptions;
            toJSON(message: _101.MessageOptions): unknown;
            fromPartial(object: Partial<_101.MessageOptions>): _101.MessageOptions;
            fromAmino(object: _101.MessageOptionsAmino): _101.MessageOptions;
            toAmino(message: _101.MessageOptions): _101.MessageOptionsAmino;
            fromAminoMsg(object: _101.MessageOptionsAminoMsg): _101.MessageOptions;
            fromProtoMsg(message: _101.MessageOptionsProtoMsg): _101.MessageOptions;
            toProto(message: _101.MessageOptions): Uint8Array;
            toProtoMsg(message: _101.MessageOptions): _101.MessageOptionsProtoMsg;
        };
        FieldOptions: {
            typeUrl: string;
            encode(message: _101.FieldOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number | undefined): _101.FieldOptions;
            fromJSON(object: any): _101.FieldOptions;
            toJSON(message: _101.FieldOptions): unknown;
            fromPartial(object: Partial<_101.FieldOptions>): _101.FieldOptions;
            fromAmino(object: _101.FieldOptionsAmino): _101.FieldOptions;
            toAmino(message: _101.FieldOptions): _101.FieldOptionsAmino;
            fromAminoMsg(object: _101.FieldOptionsAminoMsg): _101.FieldOptions;
            fromProtoMsg(message: _101.FieldOptionsProtoMsg): _101.FieldOptions;
            toProto(message: _101.FieldOptions): Uint8Array;
            toProtoMsg(message: _101.FieldOptions): _101.FieldOptionsProtoMsg;
        };
        OneofOptions: {
            typeUrl: string;
            encode(message: _101.OneofOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number | undefined): _101.OneofOptions;
            fromJSON(object: any): _101.OneofOptions;
            toJSON(message: _101.OneofOptions): unknown;
            fromPartial(object: Partial<_101.OneofOptions>): _101.OneofOptions;
            fromAmino(object: _101.OneofOptionsAmino): _101.OneofOptions;
            toAmino(message: _101.OneofOptions): _101.OneofOptionsAmino;
            fromAminoMsg(object: _101.OneofOptionsAminoMsg): _101.OneofOptions;
            fromProtoMsg(message: _101.OneofOptionsProtoMsg): _101.OneofOptions;
            toProto(message: _101.OneofOptions): Uint8Array;
            toProtoMsg(message: _101.OneofOptions): _101.OneofOptionsProtoMsg;
        };
        EnumOptions: {
            typeUrl: string;
            encode(message: _101.EnumOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number | undefined): _101.EnumOptions;
            fromJSON(object: any): _101.EnumOptions;
            toJSON(message: _101.EnumOptions): unknown;
            fromPartial(object: Partial<_101.EnumOptions>): _101.EnumOptions;
            fromAmino(object: _101.EnumOptionsAmino): _101.EnumOptions;
            toAmino(message: _101.EnumOptions): _101.EnumOptionsAmino;
            fromAminoMsg(object: _101.EnumOptionsAminoMsg): _101.EnumOptions;
            fromProtoMsg(message: _101.EnumOptionsProtoMsg): _101.EnumOptions;
            toProto(message: _101.EnumOptions): Uint8Array;
            toProtoMsg(message: _101.EnumOptions): _101.EnumOptionsProtoMsg;
        };
        EnumValueOptions: {
            typeUrl: string;
            encode(message: _101.EnumValueOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number | undefined): _101.EnumValueOptions;
            fromJSON(object: any): _101.EnumValueOptions;
            toJSON(message: _101.EnumValueOptions): unknown;
            fromPartial(object: Partial<_101.EnumValueOptions>): _101.EnumValueOptions;
            fromAmino(object: _101.EnumValueOptionsAmino): _101.EnumValueOptions;
            toAmino(message: _101.EnumValueOptions): _101.EnumValueOptionsAmino;
            fromAminoMsg(object: _101.EnumValueOptionsAminoMsg): _101.EnumValueOptions;
            fromProtoMsg(message: _101.EnumValueOptionsProtoMsg): _101.EnumValueOptions;
            toProto(message: _101.EnumValueOptions): Uint8Array;
            toProtoMsg(message: _101.EnumValueOptions): _101.EnumValueOptionsProtoMsg;
        };
        ServiceOptions: {
            typeUrl: string;
            encode(message: _101.ServiceOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number | undefined): _101.ServiceOptions;
            fromJSON(object: any): _101.ServiceOptions;
            toJSON(message: _101.ServiceOptions): unknown;
            fromPartial(object: Partial<_101.ServiceOptions>): _101.ServiceOptions;
            fromAmino(object: _101.ServiceOptionsAmino): _101.ServiceOptions;
            toAmino(message: _101.ServiceOptions): _101.ServiceOptionsAmino;
            fromAminoMsg(object: _101.ServiceOptionsAminoMsg): _101.ServiceOptions;
            fromProtoMsg(message: _101.ServiceOptionsProtoMsg): _101.ServiceOptions;
            toProto(message: _101.ServiceOptions): Uint8Array;
            toProtoMsg(message: _101.ServiceOptions): _101.ServiceOptionsProtoMsg;
        };
        MethodOptions: {
            typeUrl: string;
            encode(message: _101.MethodOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number | undefined): _101.MethodOptions;
            fromJSON(object: any): _101.MethodOptions;
            toJSON(message: _101.MethodOptions): unknown;
            fromPartial(object: Partial<_101.MethodOptions>): _101.MethodOptions;
            fromAmino(object: _101.MethodOptionsAmino): _101.MethodOptions;
            toAmino(message: _101.MethodOptions): _101.MethodOptionsAmino;
            fromAminoMsg(object: _101.MethodOptionsAminoMsg): _101.MethodOptions;
            fromProtoMsg(message: _101.MethodOptionsProtoMsg): _101.MethodOptions;
            toProto(message: _101.MethodOptions): Uint8Array;
            toProtoMsg(message: _101.MethodOptions): _101.MethodOptionsProtoMsg;
        };
        UninterpretedOption: {
            typeUrl: string;
            encode(message: _101.UninterpretedOption, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number | undefined): _101.UninterpretedOption;
            fromJSON(object: any): _101.UninterpretedOption;
            toJSON(message: _101.UninterpretedOption): unknown;
            fromPartial(object: Partial<_101.UninterpretedOption>): _101.UninterpretedOption;
            fromAmino(object: _101.UninterpretedOptionAmino): _101.UninterpretedOption;
            toAmino(message: _101.UninterpretedOption): _101.UninterpretedOptionAmino;
            fromAminoMsg(object: _101.UninterpretedOptionAminoMsg): _101.UninterpretedOption;
            fromProtoMsg(message: _101.UninterpretedOptionProtoMsg): _101.UninterpretedOption;
            toProto(message: _101.UninterpretedOption): Uint8Array;
            toProtoMsg(message: _101.UninterpretedOption): _101.UninterpretedOptionProtoMsg;
        };
        UninterpretedOption_NamePart: {
            typeUrl: string;
            encode(message: _101.UninterpretedOption_NamePart, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number | undefined): _101.UninterpretedOption_NamePart;
            fromJSON(object: any): _101.UninterpretedOption_NamePart;
            toJSON(message: _101.UninterpretedOption_NamePart): unknown;
            fromPartial(object: Partial<_101.UninterpretedOption_NamePart>): _101.UninterpretedOption_NamePart;
            fromAmino(object: _101.UninterpretedOption_NamePartAmino): _101.UninterpretedOption_NamePart;
            toAmino(message: _101.UninterpretedOption_NamePart): _101.UninterpretedOption_NamePartAmino;
            fromAminoMsg(object: _101.UninterpretedOption_NamePartAminoMsg): _101.UninterpretedOption_NamePart;
            fromProtoMsg(message: _101.UninterpretedOption_NamePartProtoMsg): _101.UninterpretedOption_NamePart;
            toProto(message: _101.UninterpretedOption_NamePart): Uint8Array;
            toProtoMsg(message: _101.UninterpretedOption_NamePart): _101.UninterpretedOption_NamePartProtoMsg;
        };
        SourceCodeInfo: {
            typeUrl: string;
            encode(message: _101.SourceCodeInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number | undefined): _101.SourceCodeInfo;
            fromJSON(object: any): _101.SourceCodeInfo;
            toJSON(message: _101.SourceCodeInfo): unknown;
            fromPartial(object: Partial<_101.SourceCodeInfo>): _101.SourceCodeInfo;
            fromAmino(object: _101.SourceCodeInfoAmino): _101.SourceCodeInfo;
            toAmino(message: _101.SourceCodeInfo): _101.SourceCodeInfoAmino;
            fromAminoMsg(object: _101.SourceCodeInfoAminoMsg): _101.SourceCodeInfo;
            fromProtoMsg(message: _101.SourceCodeInfoProtoMsg): _101.SourceCodeInfo;
            toProto(message: _101.SourceCodeInfo): Uint8Array;
            toProtoMsg(message: _101.SourceCodeInfo): _101.SourceCodeInfoProtoMsg;
        };
        SourceCodeInfo_Location: {
            typeUrl: string;
            encode(message: _101.SourceCodeInfo_Location, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number | undefined): _101.SourceCodeInfo_Location;
            fromJSON(object: any): _101.SourceCodeInfo_Location;
            toJSON(message: _101.SourceCodeInfo_Location): unknown;
            fromPartial(object: Partial<_101.SourceCodeInfo_Location>): _101.SourceCodeInfo_Location;
            fromAmino(object: _101.SourceCodeInfo_LocationAmino): _101.SourceCodeInfo_Location;
            toAmino(message: _101.SourceCodeInfo_Location): _101.SourceCodeInfo_LocationAmino;
            fromAminoMsg(object: _101.SourceCodeInfo_LocationAminoMsg): _101.SourceCodeInfo_Location;
            fromProtoMsg(message: _101.SourceCodeInfo_LocationProtoMsg): _101.SourceCodeInfo_Location;
            toProto(message: _101.SourceCodeInfo_Location): Uint8Array;
            toProtoMsg(message: _101.SourceCodeInfo_Location): _101.SourceCodeInfo_LocationProtoMsg;
        };
        GeneratedCodeInfo: {
            typeUrl: string;
            encode(message: _101.GeneratedCodeInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number | undefined): _101.GeneratedCodeInfo;
            fromJSON(object: any): _101.GeneratedCodeInfo;
            toJSON(message: _101.GeneratedCodeInfo): unknown;
            fromPartial(object: Partial<_101.GeneratedCodeInfo>): _101.GeneratedCodeInfo;
            fromAmino(object: _101.GeneratedCodeInfoAmino): _101.GeneratedCodeInfo;
            toAmino(message: _101.GeneratedCodeInfo): _101.GeneratedCodeInfoAmino;
            fromAminoMsg(object: _101.GeneratedCodeInfoAminoMsg): _101.GeneratedCodeInfo;
            fromProtoMsg(message: _101.GeneratedCodeInfoProtoMsg): _101.GeneratedCodeInfo;
            toProto(message: _101.GeneratedCodeInfo): Uint8Array;
            toProtoMsg(message: _101.GeneratedCodeInfo): _101.GeneratedCodeInfoProtoMsg;
        };
        GeneratedCodeInfo_Annotation: {
            typeUrl: string;
            encode(message: _101.GeneratedCodeInfo_Annotation, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: Uint8Array | import("..").BinaryReader, length?: number | undefined): _101.GeneratedCodeInfo_Annotation;
            fromJSON(object: any): _101.GeneratedCodeInfo_Annotation;
            toJSON(message: _101.GeneratedCodeInfo_Annotation): unknown;
            fromPartial(object: Partial<_101.GeneratedCodeInfo_Annotation>): _101.GeneratedCodeInfo_Annotation;
            fromAmino(object: _101.GeneratedCodeInfo_AnnotationAmino): _101.GeneratedCodeInfo_Annotation;
            toAmino(message: _101.GeneratedCodeInfo_Annotation): _101.GeneratedCodeInfo_AnnotationAmino;
            fromAminoMsg(object: _101.GeneratedCodeInfo_AnnotationAminoMsg): _101.GeneratedCodeInfo_Annotation;
            fromProtoMsg(message: _101.GeneratedCodeInfo_AnnotationProtoMsg): _101.GeneratedCodeInfo_Annotation;
            toProto(message: _101.GeneratedCodeInfo_Annotation): Uint8Array;
            toProtoMsg(message: _101.GeneratedCodeInfo_Annotation): _101.GeneratedCodeInfo_AnnotationProtoMsg;
        };
    };
}
