import { Client as TendermintClient } from '@cosmjs/tendermint-rpc';
import { Client, credentials } from '@grpc/grpc-js';
import { RPCImpl } from 'protobufjs';

import protoImpl from './generated/protoImpl';

export interface RegenApiOptions {
	grpcUrl: string;
	tendermintUrl: string;
}

export class RegenApi {
	private readonly grpcClient: Client;
	/**
	 * Raw protobuf implementation generated by protobufjs.
	 */
	readonly protoImpl = protoImpl;
	readonly tendermintClient: TendermintClient;

	constructor(grpcClient: Client, tendermintClient: TendermintClient) {
		this.grpcClient = grpcClient;
		this.tendermintClient = tendermintClient;
	}

	/**
	 * Create a RegenApi object which connects to the gRPC and Tendermint
	 * endpoints.
	 *
	 * @param options - Options to pass into RegenAPI.
	 */
	public static async connect(options: RegenApiOptions): Promise<RegenApi> {
		const grpcClient = new Client(
			options.grpcUrl,
			credentials.createInsecure()
		);
		const tendermintClient = await TendermintClient.connect(
			options.tendermintUrl
		);

		return new RegenApi(grpcClient, tendermintClient);
	}

	/**
	 * A RPC implementation using gRPC to pass into protobuf services.
	 *
	 * @todo Make this private, and create helper functions that will use this
	 * implementation under the hood.
	 */
	public rpcImpl: RPCImpl = (method, requestData, callback) => {
		this.grpcClient.makeUnaryRequest<Uint8Array, Uint8Array>(
			method.name,
			(arg) => Buffer.from(arg),
			(arg) => arg,
			requestData,
			callback
		);
	};
}
